### ISSUE TITLE
TcpClientCredentialType_Certificate_EchoString fails with new self-hosted WCF service

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1057]
Start the new self-hosted WCF services and run OuterLoops to see this failure.  If you don't see it, please try it on a different machine or VM.  My net.tcp port sharing service and listener adapter were both confirmed running when this failed.

```
                 c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\ClientCredentialTypeTests.cs(157,0): at Https_ClientCredentialTypeTests.NtlmAuthentication_RoundTrips_Echo()
            Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString [FAIL]
               System.ServiceModel.EndpointNotFoundException : There was no endpoint listening at net.tcp://localhost:809//TcpTransportSecuritySslClientCredentialTypeCertificate.svc//tcp-server-ssl-security-clientcredentialtype-certificate that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
               Stack Trace:
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs(469,0): at System.ServiceModel.Channels.ConnectionUpgradeHelper.<DecodeFramingFaultAsync>d__0.MoveNext()
```

**Comment by zhenlan** [comment]
@mconnew has a PR #1086 that may fix this.
