### ISSUE TITLE
TCP_ServiceCertExpired_Throw_MessageSecurityException fails in ToF with new test infrastructure

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1058]
Running ToF tests against CoreCLR, this test now fails with a new exception.  Note we now use WCFCORESRV4.cloudapp.net for default ToF runs.

```
  --------------------------------
  Running Test: ExpectedExceptionTests.TCP_ServiceCertExpired_Throw_MessageSecurityException
  Assert.True:Expected message contains WCFCORESRV4.cloudapp.net, actual message: A call to SSPI failed, see inner exception.
  Xunit.AssertTestException: Assert.True: Expected message contains WCFCORESRV4.cloudapp.net, actual message: A call to SSPI failed, see inner exception.
     at Xunit.Assert.HandleFail(String assertionName, String message) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.True(Boolean condition, String message) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at ExpectedExceptionTests.TCP_ServiceCertExpired_Throw_MessageSecurityException() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 483
     at EntryPointMain.<>c.b__0_11() in E:\ProjectK\src\QA\ToF\PK\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ExpectedExceptions\Client.ExpectedExceptions.Tests\Client.ExpectedExceptions.Tests.main.cs:line 24
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------
```

**Comment by zhenlan** [comment]
@roncain can you please check if we have this failure in Helix run? If yes, we should take a further look. If no, we can close this out.

**Comment by roncain** [comment]
I no longer see this failure in ToF or Helix, so I am closing this.  Note that this test uses only [Fact] so this means it is running in both ToF and Helix
