### ISSUE TITLE
Basic authentication tests fail in CI when using IIS-hosted services

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1111]
The Basic authentication tests fail on CI runs against IIS-hosted WCF services but pass in self-hosted.  Likely cause is that Basic Authentication is not enabled for the CI web sites in IIS.
These are the 2 failing tests:
```
Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException 
Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo
```

Failure looks like this:
```
Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ServiceModel.Security.MessageSecurityException)
        Actual:   typeof(System.ServiceModel.CommunicationException): The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.
        Stack Trace:
           D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(764,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
           D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(371,0): at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
           D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(136,0): at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
              at generatedProxy_2.Echo(String )
           D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\ClientCredentialTypeTests.cs(82,0): at Https_ClientCredentialTypeTests.<>c.<BasicAuthenticationInvalidPwd_throw_MessageSecurityException>b__4_0()
     Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo [FAIL]
        Test Case: BasicAuthentication FAILED with the following errors: Basic echo test.
  Test variation:...
  BasicAuthentication_RoundTrips_Echo
  Using address: 'https://wcfcoresrv2.cloudapp.net/WcfService15//BasicAuth.svc//https-basic'
        Unexpected exception was caught: System.ServiceModel.CommunicationException: The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.
           at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 764
           at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) in D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
           at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) in D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 136
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
           at generatedProxy_2.Echo(String )
           at Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo() in D:\j\workspace\outerloop_win---1452b487\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\ClientCredentialTypeTests.cs:line 40

```

**Comment by zhenlan** [comment]
@roncain will add new ConditionalFact for Digest
@hongdai will come up a complete proposal of how we need to break down current IIS hosted test service.

**Comment by zhenlan** [comment]
@hongdai @roncain It's my understanding this is a test bug instead of a product bug. Please chime in if this is not the case.

**Comment by roncain** [comment]
@Zhenlan and @hongdai -- yes, this is probably only a test bug.  Right now, the ConditionalFact for Basic_Authentication_Available is true only for self-host, so this is skipped in CI runs using IIS.  I believe we are waiting for Hong to tell me how to write a ConditionalFact that will allow it to work against IIS now that the security folder PR is in.  Example: does the Util service need and endpoint to query?  Is it true only on Windows?  etc.

**Comment by hongdai** [comment]
Matt and I have just discussed it. Create a local account on service for basic auth imposes a security risk. Instead we can have a test similar to Digest no domain.

Reassign the bug to Matt. Matt will implement a basic auth test without the need of a local user account created in the IIS hosted test server machine.
