### ISSUE TITLE
4 MessageContractTests Failed in Latest Library + RTM Net Native Tools

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#1121]
The following tests used to pass with Latest Library + RTM Net Native Tools. I started seeing the failures since I rebased my repo to latest. Not sure if this is related to the recent infrastructure changes.

  Failed tests:
    MessageContractTests.MessageContract_IsWrapped_True
    MessageContractTests.MessageContract_IsWrapped_False
    MessageContractTests.MessageBody_Elements_Ordered
    MessageContractTests.MessageBody_Elements_CustomerElement_Value_Matches
```

  --------------------------------
  Running Test: MessageContractTests.MessageContract_IsWrapped_False
  Caught Unexpected exception:System.ObjectDisposedException: ObjectDisposed_Generic
  ObjectDisposed_ObjectName_Name
     at System.Net.Http.HttpContent.CheckDisposed() in f:\dd\ndp\fxcore\Open\src\System.Net.Http\src\System\Net\HttpContent.cs:line 472
     at System.Net.Http.HttpContent.GetComputedOrBufferLength() in f:\dd\ndp\fxcore\Open\src\System.Net.Http\src\System\Net\HttpContent.cs:line 379
     at System.Func$1>.Invoke()
     at System.Net.Http.Headers.HttpContentHeaders.get_ContentLength() in f:\dd\ndp\fxcore\Open\src\System.Net.Http\src\System\Net\Headers\HttpContentHeaders.cs:line 84
     at System.ServiceModel.Channels.HttpResponseMessageProperty.HttpResponseMessageBackedProperty.get_SuppressEntityBody() in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageProperty.cs:line 347
     at System.ServiceModel.Channels.HttpResponseMessageProperty.HttpResponseMessageBackedProperty.CreateTraditionalResponseMessageProperty() in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageProperty.cs:line 397
     at System.ServiceModel.Channels.HttpResponseMessageProperty.System.ServiceModel.Channels.IMessageProperty.CreateCopy() in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageProperty.cs:line 192
     at System.ServiceModel.Channels.MessageProperties.CreateCopyOfPropertyValue(Object propertyValue) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageProperties.cs:line 418
     at System.ServiceModel.Channels.MessageProperties.System.Collections.Generic.ICollection>.CopyTo(KeyValuePair$2[] array, Int32 index) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageProperties.cs:line 712
     at System.ServiceModel.Channels.DefaultMessageBuffer..ctor($Message message, $XmlBuffer msgBuffer) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageBuffer.cs:line 67
     at System.ServiceModel.Channels.Message.OnCreateBufferedCopy(Int32 maxBufferSize, $XmlDictionaryReaderQuotas quotas) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Message.cs:line 337
     at System.ServiceModel.Channels.BufferedMessage.OnCreateBufferedCopy(Int32 maxBufferSize) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Message.cs:line 1707
     at System.ServiceModel.Channels.Message.CreateBufferedCopy(Int32 maxBufferSize) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Message.cs:line 104
     at MessageContractCommon.MyInspector.AfterReceiveReply($Message& reply, Object correlationState) in d:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Contract\Message\Released\MessageContractCommon.cs:line 154
     at System.ServiceModel.Dispatcher.ImmutableClientRuntime.AfterReceiveReply() in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\ImmutableClientRuntime.cs:line 109
     at System.ServiceModel.Channels.ServiceChannel.HandleReply($ProxyOperationRuntime operation, $ProxyRpc rpc) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 933
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 788
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 728
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 139
     at __InterfaceProxies.ServiceChannelProxy_IMessageContract.MessageContractCommon.MessageContractHelpers_P.IMessageContract_P.MessageContractRequestReplyNotWrapped($RequestBankingData bt) in c:\Users\shmao\AppData\Local\Temp\Ilc1260082035\Contract.Message.Tests.ITFProxy\Contract.Message.Tests.ITFProxy.g.cs:line 379
     at MessageContractTests.MessageContract_IsWrapped_False() in d:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Contract\Message\Released\MessageContractTests.cs:line 37
     at EntryPointMain.<>c.b__0_1() in D:\dd\ProjectK\src\QA\ToF\PN\x86\dbg\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Contract\Message\Contract.Message.Tests.main.cs:line 14
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod() in d:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t) in d:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------
```

**Comment by roncain** [comment]
Thanks @shmao .  Do you see these same tests fail using latest NET Native toolchain too?  The error looks like it is in the System.Net.Http library or our use of it.

**Comment by shmao** [comment]
Currently the test project doesn't build with the latest toolchain + latest library. The build failed with the following errors,

```
c:\Users\shmao\AppData\Local\Temp\Ilc1977765914\Contract.Message.Tests.McgInterop\PInvoke.g.cs(920,21): error CS1502: The best overloaded method match for 'McgInterop.api_ms_win_core_localization_l1_2_0_dll_PInvokes.IdnToAscii(uint, ushort*, int, ushort*, int)' has some invalid arguments [D:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Contract\Message\Contract.Message.Tests.csproj]
c:\Users\shmao\AppData\Local\Temp\Ilc1977765914\Contract.Message.Tests.McgInterop\PInvoke.g.cs(924,9): error CS1503: Argument 4: cannot convert from 'char*' to 'ushort*' [D:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Contract\Message\Contract.Message.Tests.csproj]
```

I'll give this a try later.

**Comment by shmao** [comment]
These tests passed with latest packages, they only failed with RTM libraries. I will move these tests to latest test files.
