### ISSUE TITLE
TypedProxyTests.ServiceContract_TypedProxy_AsyncBeginEnd_Call Failed

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#1151]
This test failed for me once. I was running N from K using the ILC built from N branch. I couldn't repro the failure.

```
Running Test: TypedProxyTests.ServiceContract_TypedProxy_AsyncBeginEnd_Call
  Assert.True:Test Scenario: ServiceContract_TypedProxy_AsyncBeginEnd_Call FAILED with the following errors: AsyncCallback was not called.
  Expected response from Service: Hello Actual was: 

  Xunit.AssertTestException: Assert.True: Test Scenario: ServiceContract_TypedProxy_AsyncBeginEnd_Call FAILED with the following errors: AsyncCallback was not called.
  Expected response from Service: Hello Actual was: 

     at Xunit.Assert.HandleFail(String assertionName, String message) in D:\dd\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.True(Boolean condition, String message) in D:\dd\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at TypedProxyTests.ServiceContract_TypedProxy_AsyncBeginEnd_Call($Binding binding, String endpoint, String testName) in d:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\TypedClient\TypedProxyTests.4.0.0.cs:line 468
     at TypedProxyTests.ServiceContract_TypedProxy_AsyncBeginEnd_Call() in d:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\TypedClient\TypedProxyTests.4.0.0.cs:line 33
     at EntryPointMain.<>c.b__0_1() in D:\dd\ProjectK\src\QA\ToF\PN\x86\dbg\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\TypedClient\Client.TypedClient.Tests.main.cs:line 14
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod() in D:\dd\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------
```

**Comment by zhenlan** [comment]
@shmao only saw this once so far. Keep the issue open to see if we see this more often.

**Comment by roncain** [comment]
Closing because we have not seen this issue repro for several months.  I verified the test does, in fact, pass and is not just skipped.
