### ISSUE TITLE
Duplex on http not working.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1157]
On full framework WCF uses two Request/Reply channel shapes to make Duplex work on Http. The functionality to setup a Request/Reply channel where the Service initiates the Request is missing on the client side.

**Comment by huangjinshe** [comment]
I think even TCP duplex not finish yet.

**Comment by zhenlan** [comment]
@StephenBonikowsky can you please update test case names here?

**Comment by StephenBonikowsky** [comment]
New tests...
Scenarios.Client.ChannelLayer.DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding
Scenarios.Client.ChannelLayer.DuplexChannelShapeTests.IDuplexSessionChannel_Http_BasicHttpBinding

**Comment by mconnew** [comment]
Scenarios.Client.ChannelLayer.DuplexChannelShapeTests.IDuplexSessionChannel_Http_BasicHttpBinding is working once I take the active issue off. Scenarios.Client.ChannelLayer.DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding is failing because it's service is configured to not use WebSockets. When I set it to use WebSockets, some other tests start failing so we have a conflict of use on the endpoint and we'll likely need to add a new endpoint.

**Comment by zhenlan** [comment]
@StephenBonikowsky, can you please fix these tests as @mconnew explained?

**Comment by roncain** [comment]
These don't pass for me when I run them with IncludeTestsWithIssues=true (easier than commenting out the [Issue]).

I am just running them locally self-hosted.  I set PSEXEC_PATH to get the self-hosted service launched with psexec.exe, but otherwise just ran all outerloops.

Stack traces:

```
           DuplexChannelShapeTests.IDuplexSessionChannel_Http_BasicHttpBinding [FAIL]
               System.ArgumentException : Channel type 'System.ServiceModel.Channels.IDuplexSessionChannel' was requested, but Binding 'BasicHttpBinding' doesn't support it or isn't configured properly to support it.
               Parameter name: TChannel
               Stack Trace:
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpTransportBindingElement.cs(474,0): at System.ServiceModel.Channels.HttpTransportBindingElement.BuildChannelFactory[TChannel](BindingContext context)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\BindingContext.cs(83,0): at System.ServiceModel.Channels.BindingContext.BuildInnerChannelFactory[TChannel]()
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageEncodingBindingElement.cs(35,0): at System.ServiceModel.Channels.MessageEncodingBindingElement.InternalBuildChannelFactory[TChannel](BindingContext context)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TextMessageEncodingBindingElement.cs(141,0): at System.ServiceModel.Channels.TextMessageEncodingBindingElement.BuildChannelFactory[TChannel](BindingContext context)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\BindingContext.cs(83,0): at System.ServiceModel.Channels.BindingContext.BuildInnerChannelFactory[TChannel]()
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Binding.cs(174,0): at System.ServiceModel.Channels.Binding.BuildChannelFactory[TChannel](BindingParameterCollection parameters)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\BasicHttpBinding.cs(72,0): at System.ServiceModel.BasicHttpBinding.BuildChannelFactory[TChannel](BindingParameterCollection parameters)
                  c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\ChannelLayer\DuplexChannelShapeTests.4.1.0.cs(120,0): at DuplexChannelShapeTests.IDuplexSessionChannel_Http_BasicHttpBinding()
 
```
```
            DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding [FAIL]
    32>RunTestsForProject:
         Invoking http://localhost/TestHost.svc/Fqdn ...
    42>RunTestsForProject:
               System.InvalidOperationException : An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details.
               ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
    40>RunTestsForProject:
         Finished running tests.  End time=10:34:37.13, Exit code = 0
    42>RunTestsForProject:
               -------- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
         ---ETW Trace for Test DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding Begins---
         DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding: WebSocket connection request to 'wss://localhost:44285//NetHttps.svc//NetHttps' send start.
         DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding: Creating the client WebSocket with a factory of type 'System.ServiceModel.Channels.CoreClrClientWebSocketFactory'.
         DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding: Throwing an exception. Source: System.ServiceModel 4.0.0.0. Exception details: System.InvalidOperationException: An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details. ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server
            at System.Net.WebSockets.WinHttpWebSocket.ThrowOnInvalidConnectState()
            at System.Net.WebSockets.WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__20.MoveNext()
    40>RunTestsForProject:
         Creating "c:\OSS\wcf\bin/tests/Windows_NT.AnyCPU.Debug/Binding.Http.Tests/netcoreapp1.0/tests.passed.with.OuterLoop.without.failing" because "AlwaysCreate" was specified.
    40>Done Building Project "c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Binding\Http\Binding.Http.Tests.csproj" (PrepareForRun;Test target(s)).
    42>RunTestsForProject:
            --- End of inner exception stack trace ---
            at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__20.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__16.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at System.ServiceModel.Channels.CoreClrClientWebSocketFactory.<CreateWebSocketAsync>d__0.MoveNext() in c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CoreClrClientWebSocketFactory.cs:line 35
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    45>RunTestsForProject:
         Invoking http://localhost/TestHost.svc/RootCert ...
    42>RunTestsForProject:
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.ServiceModel.Channels.ClientWebSocketTransportDuplexSessionChannel.<CreateWebSocketWithFactoryAsync>d__17.MoveNext() in c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ClientWebSocketTransportDuplexSessionChannel.cs:line 216
            --- End of inner exception stack trace ---
         DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding: WebSocketId:-1 connection is aborted.
         ---ETW Trace for Test DuplexChannelShapeTests.IDuplexSessionChannel_Https_NetHttpsBinding Ends---

```

**Comment by StephenBonikowsky** [comment]
Both tests continue to fail, same call stacks as @roncain provided as well.
Until the http variation is fixed there isn't much reason for adding a new endpoint for the https variation.

Adding @mconnew as assignee.
