### ISSUE TITLE
System.ObjectDisposedException: The CancellationTokenSource has been disposed.

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1169]

**Comment by KKhurin** [comment]
OS: Ubuntu.
Transport: Http 
Test: async HelloWorld
We get the following exception while trying to measure perf on Ubuntu VM:
~~~
System.IO.IOException: The read operation failed, see inner exception.
 ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
at System.Threading.CancellationToken.Register(Action`1 callback, Object state)
at System.Net.Http.CurlHandler.HttpContentAsyncStream.RegisterCancellation(CancellationToken cancellationToken)
at System.Net.Http.CurlHandler.HttpContentAsyncStream.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)
at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
--- End of inner exception stack trace ---
   
at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by KKhurin** [comment]
This actually reproduces on both sync and async, http Hello and http Streaming.

**Comment by roncain** [comment]
@KKhurin does this happen immediately or after some load is placed on the system? I'm wondering if we can make a standalone repro or a functional test trigger this.

**Comment by KKhurin** [comment]
Yes, it happens immediately for streaming over http.
It also happens on HelloWorld over http after ~300-400 seconds into the perf run (we iterate through all possible loads so typically the perf runs are quite lengthy).

**Comment by zhenlan** [comment]
@KKhurin is working with @stephentoub on this.

**Comment by stephentoub** [comment]
> @KKhurin is working with @stephentoub on this.

This is a very different call stack than what @KKhurin sent me offline; that one doesn't mention cancellation at all.

**Comment by stephentoub** [comment]
And I don't understand how this stack trace is happening at all.  Is WCF messing with app switches at all?  This call stack suggests that this line is being hit:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/CancellationTokenSource.cs#L628
but that line is behind an app context switch that should never be true on Linux.  @AlexGhiondea, do you know what's going on here?

**Comment by KKhurin** [comment]
I don't know if we have any app switches but @mconnew would know better.

**Comment by AlexGhiondea** [comment]
/cc @AlfredoMS as I think we talked about a very similar issue in the past.

If the test assembly is built such that it is targeting 4.5.2 or below then the switch could come in to play (assuming the host correctly reads the TFM from the assembly and sets it on the AppDomain).

Since we have introduced a way to override `AppContext` switches from the project.json with https://github.com/dotnet/coreclr/pull/5001, you can give that a try to see if explicitly setting the switch `SwitchThrowExceptionIfDisposedCancellationTokenSource ` to `false` removes this issue.

**Comment by AlexGhiondea** [comment]
I think I know why this is happening. If the app you are running does not have a TFM *and* the host you use does not set a flag requesting the test behavior from AppContext in the absence of a TFM, then you are going to be in compat mode with 4.0 where ALL the compat switches are set to true -- leading to this bug.

Do you know which host is used to run these tests?

Will reply with more info in a bit.

**Comment by AlexGhiondea** [comment]
@KKhurin can you point me to how you are running tests?

**Comment by KKhurin** [comment]
Actually keeping it to myself to provide Alex the call stack repro for now...
The underlying reason for the failure is likely the same as #1211.

**Comment by stephentoub** [comment]
> The underlying reason for the failure is likely the same as #1211.

It may be related, but this particular call stack is disconcerting, and even if it is related, highlights an additional issue: we should not be hitting ThrowObjectDisposedException in InternalRegister in these bits.

**Comment by KKhurin** [comment]
Can't repro on the latest RC3 and CLI host. Closing and will reactivate if we see it again.
