### ISSUE TITLE
Potential issue with channel extensibility

### ISSUE THREAD

**Issue by khdang** [dotnet/wcf#1170]
From https://github.com/dotnet/wcf/issues/623, I've made Custom Message Interceptor test to verify but it seems that it doesn't work with this error: 
```
Discovered:  Binding.Custom.Tests
  Starting:    Binding.Custom.Tests
     CustomBindingTests.CustomBinding_Message_Interceptor [FAIL]
        System.InvalidOperationException : A call to IChannelFactory.CreateChannel made on an object of type System.ServiceModel.Channels.HttpChannelFactory`1[System.ServiceModel.Channels.IRequestChannel] failed because Open has not bee
  n called on this object.
        Stack Trace:
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs(157,0): at System.ServiceModel.Channels.ChannelFactoryBase`1.ValidateCreateChannel()
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs(129,0): at System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs(124,0): at System.ServiceModel.Channels.ChannelFactoryBase`1.CreateChannel(EndpointAddress address, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\tests\Scenarios\Binding\Custom\InterceptingChannelFactory.cs(87,0): at Microsoft.Samples.MessageInterceptor.InterceptingChannelFactory`1.OnCreateChannel(EndpointAddress to, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs(130,0): at System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs(124,0): at System.ServiceModel.Channels.ChannelFactoryBase`1.CreateChannel(EndpointAddress address, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs(576,0): at System.ServiceModel.Channels.ServiceChannelFactory.ServiceChannelFactoryOverRequest.CreateInnerChannelBinder(End
  pointAddress to, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs(317,0): at System.ServiceModel.Channels.ServiceChannelFactory.CreateServiceChannel(EndpointAddress address, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs(349,0): at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs(559,0): at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs(569,0): at System.ServiceModel.ChannelFactory`1.CreateChannel()
           e:\Open\wcf\src\System.Private.ServiceModel\tests\Scenarios\Binding\Custom\CustomBindingTests.cs(91,0): at CustomBindingTests.CustomBinding_Message_Interceptor()
  Finished:    Binding.Custom.Tests
```

**Comment by zhenlan** [comment]
@khdang can you please take further look of this to see if these are test issues?

**Comment by khdang** [comment]
@zhenlan Yes, now it looks like a test issue indeed. Once the PR is merged we can close this issue.

**Comment by zhenlan** [comment]
Sounds great. Thanks @khdang.
