### ISSUE TITLE
CustomBinding_Message_Interceptor test shows we can modify communication object while it's in Opened state

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1241]
This test is passing in .netcore. However, it fails in Desktop because the test is modifying the communication object when it's already "Opened". 

In Desktop, it fails with below exception:
The communication object, System.ServiceModel.Channels.HttpChannelFactory`1[System.ServiceModel.Channels.IRequestChannel], cannot be modified while it is in the Opened state.

at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrImmutable()
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at InterceptingChannelFactory`1.OnOpen(TimeSpan timeout) in E:\test\GenerateTests\GenerateTests\scenarios\Extensibility\MessageInterceptor\InterceptingChannelFactory.cs:line 48
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelFactory.TypedServiceChannelFactory`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ChannelFactory.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at MessageInterceptorTests.CustomBinding_Message_Interceptor() in E:\test\GenerateTests\GenerateTests\scenarios\Extensibility\MessageInterceptor\MessageInterceptorTests.cs:line 49
   at ConsoleApplication1.Program.RunTests() in E:\test\GenerateTests\GenerateTests\Program.cs:line 37

**Comment by roncain** [comment]
Deeper investigation is required, but this test needs to be rewritten first.  It is not doing what it claims to do and not verifying that what it thinks it is doing, in fact, happened.  I recommend making a test-double of the message interceptor to verify it is being called as well as ensuring a modified message round-trips.
