### ISSUE TITLE
System.ServiceModel.Http should depend on System.Private.ServiceModel 

### ISSUE THREAD

**Issue by mjrousos** [dotnet/wcf#1242]
If I create a simple netcoreapp1.0 console app and add a dependency on System.ServiceModel.Http/4.1.0-rc2-24027, and then use a type from it (creating a `BasicHttpBinding`, for example), I get the following exception at run-time:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.ServiceModel, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at IdentityManager.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at IdentityManager.Startup.Main(String[] args)
```

Adding an explicit dependency on System.Private.ServiceModel in my project.json fixes the issue, but that shouldn't be necessary. 

From inspecting the ServiceModel.Http package, it appears that System.Private.ServiceModel is only depended on if the target Framework is NetStandard1.5 (but my 'hello world' app is pulling in 1.3 references.

**Comment by mjrousos** [comment]
Repro project.json:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-rc2-3002702",
          "type": "platform"
        },
        "System.ServiceModel.Http": "4.1.0-rc2-24027"
      },
      "net46": { }
    }
  }
}
```

Repro program.cs

```C#
public class Program
{
    public static void Main(string[] args)
    {
        var binding = new System.ServiceModel.BasicHttpBinding(System.ServiceModel.BasicHttpSecurityMode.Message);
    }
}
```

**Comment by zhenlan** [comment]
Thanks @mjrousos for reporting this.

I suppose [this commit](https://github.com/dotnet/wcf/commit/04c9c0e5aea9f40910909fb092ebb7443fe58ad3) has fixed the issue post RC2.
@weshaggard @ericstj, any suggestions what else need to be done?

**Comment by zhenlan** [comment]
@mjrousos - I just give this a try with RC3 packages and `System.Private.ServiceModel` is not a problem any more. (However, there is a problem related to `System.Runtime.Serialization.Xml`, which is tracked by #1245). 

Here is how my updated project.json look like.
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc3-004338"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
        "System.ServiceModel.Http": "4.1.0-rc3-24128-00",
        "System.Runtime.Serialization.Xml": "4.1.1-rc3-24128-00"
      }
    }
  }
}
```
and global.json
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-002911"
  }
}
```

**Comment by mjrousos** [comment]
Great, thanks @zhenlan!
