### ISSUE TITLE
A libcurl built with OpenSSL is required.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1295]
Test cases that fail...

HttpsTests.ClientCertificate_EchoString
HttpsTests.ServerCertificateValidation_EchoString

Error...

Stacktrace
MESSAGE:
System.PlatformNotSupportedException : The libcurl library in use (7.29.0) and its SSL backend ("NSS/3.15.4") do not support custom handling of certificates. A libcurl built with OpenSSL is required.
+++++++++++++++++++
STACK TRACE:
at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption) at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl() at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.ServiceModel.Channels.ServiceModelHttpMessageHandler.<SendAsync>d__37.MoveNext() in /mnt/resource/j/workspace/dotnet_wcf/master/outerloop_centos7.1_debug_prtest/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceModelHttpMessageHandler.cs:line 36 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext() in /mnt/resource/j/workspace/dotnet_wcf/master/outerloop_centos7.1_debug_prtest/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs:line 950 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__35.MoveNext() in /mnt/resource/j/workspace/dotnet_wcf/master/outerloop_centos7.1_debug_prtest/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs:line 298

**Comment by StephenBonikowsky** [comment]
These tests only fail for this reason on CentOS and OSX. The Conditional ActiveIssue does not have a CentOS PlatformID, so will use the "AnyUnix" option as it is necessary to have clean CI runs.

**Comment by StephenBonikowsky** [comment]
Test case HttpsTests.ClientCertificate_EchoString also fails on Ubuntu with a slightly different message but it might be related...

Stacktrace
MESSAGE:
System.ServiceModel.CommunicationException : An error occurred while sending the request.\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\n-------- System.Net.Http.CurlException : SSL peer certificate or SSH remote key was not OK
+++++++++++++++++++
STACK TRACE:
at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason) in /mnt/j/workspace/dotnet_wcf/master/outerloop_ubuntu14.04_debug_prtest/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs:line 121 at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext() in /mnt/j/workspace/dotnet_wcf/master/outerloop_ubuntu14.04_debug_prtest/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs:line 961

**Comment by roncain** [comment]
I believe this is the same issue being addressed by PR #1305, so I have updated that PR to make these tests use the new ConditionalFact.

**Comment by niemyjski** [comment]
So something was changed 11 days before rtm that broke me post rc2...

I'm getting `The libcurl library in use (7.43.0) and its SSL backend (\"SecureTransport\") do not support custom handling of certificates. A libcurl built with OpenSSL is required.` in stable latest everything on macOS...

```
5]  
blake@:~/Code/Exceptionless.Net$ brew info openssl
openssl: stable 1.0.2h (bottled) [keg-only]
SSL/TLS cryptography library

[2:16]  
lake@:~/Code/Exceptionless.Net$ brew install openssl
Warning: openssl-1.0.2h_1 already installed
blake@:~/Code/Exceptionless.Net$ brew link --force openssl
Warning: Already linked: /usr/local/Cellar/openssl/1.0.2h_1
To relink: brew unlink openssl && brew link openssl
blake@:~/Code/Exceptionless.Net$
```

**Comment by StephenBonikowsky** [comment]
@roncain @iamjasonp @hongdai 
Jason, Hong, do you have any insight into this? Is it related to what you have been working on?

**Comment by hongdai** [comment]
We need a WCF issue opened to disable 4 client certificate tests affected by this issue. Thus reopen the issue.

**Comment by roncain** [comment]
Reopening issue because it is causing the tests to be skipped on *nix machines.

**Comment by jmspring** [comment]
Is there a plan to fix this issue beyond "disabling tests"?
