### ISSUE TITLE
Different exception thrown NetNative vs NetCore

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1320]
Negative test case...
Security\TransportSecurity\Tcp\IdentityTests.cs\ServiceIdentityNotMatch_Throw_MessageSecurityException
Expects a MessageSecurityException which it gets in NetCore but on NetNative it gets a SecurityNegotiationException.

  --------------------------------
  Running Test: IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException
  Assert.True:Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.ServiceModel.Security.SecurityNegotiationException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.ServiceModel.Security.SecurityNegotiationException' was thrown.
     at Xunit.Assert.HandleFail(String assertionName, String message) in E:\dd\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.Throws(Action action, Exception exception) in E:\dd\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException($<>c__DisplayClass1_0 CS$<>8__locals0) in E:\dd\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\IdentityTests.cs:line 94
     at EntryPointMain.<>c.b__0_36() in E:\dd\ProjectK\src\QA\ToF\PN\amd64\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 49
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\dd\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by roncain** [comment]
This might be similar to #983 where we also get SecurityNegotiationException instead of the one we actually threw.  If we find a fix for either one, let's verify whether it fixes the other.
