### ISSUE TITLE
DigestAuthentication_Echo_RoundTrips_String_No_Domain test fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1336]
This test was recently re-enabled, but it fails in NET Native, both against the nightly build server as well as localhost.
```
 --------------------------------
  Running Test: Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain
  Caught Unexpected exception:System.ServiceModel.Security.MessageSecurityException: HttpAuthorizationFailed, Digest, Digest realm="1bf72", nonce="Ni8yNy8yMDE2IDk6NTY6MjIgQU0", opaque="0000000000000000", stale=false, algorithm=MD5, qop="auth"
     at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 360
     at System.ServiceModel.Channels.HttpResponseMessageHelper.d__7.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 39
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task, ExceptionDispatchInfo oceEdi) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182
     at System.Runtime.CompilerServices.TaskAwaiter$1.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 482
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__17.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task, ExceptionDispatchInfo oceEdi) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182
     at System.Runtime.CompilerServices.TaskAwaiter$1.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 482
     at System.ServiceModel.Channels.RequestChannel.d__35.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task, ExceptionDispatchInfo oceEdi) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182
     at System.Runtime.CompilerServices.TaskAwaiter$1.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 482
     at System.ServiceModel.Channels.RequestChannel.d__34.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task, ExceptionDispatchInfo oceEdi) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182
     at System.Runtime.TaskHelpers.WaitForCompletionNoSpin($Task$1<__Canon> task) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs:line 217
     at System.ServiceModel.Channels.RequestChannel.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 260
     at System.ServiceModel.Dispatcher.RequestChannelBinder.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\RequestChannelBinder.cs:line 107
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 765
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 369
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 141
     at __InterfaceProxies.ServiceChannelProxy_IWcfService.IWcfService_P.Echo(String message) in c:\Users\roncain\AppData\Local\Temp\Ilc1050478935\Security.TransportSecurity.Tests.ITFProxy\Security.TransportSecurity.Tests.ITFProxy.g.cs:line 59
     at Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain($ChannelFactory$1 factory) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Http\ClientCredentialTypeTests.cs:line 63
     at EntryPointMain.<>c.b__0_14() in E:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 27
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Exception ex) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------
  

```

**Comment by zhenlan** [comment]
We should disable this test with #1332 for NET Native.

**Comment by hongdai** [comment]
It's decided we will make the test pass by not supplying domain name. Will close the issue once it's done.

**Comment by StephenBonikowsky** [comment]
I am going to disable this test unconditionally with this Issue, this failure should not block upgrading to latest wcf package versions.

**Comment by hongdai** [comment]
The test is fixed by Matt, passing in the lab now.
