### ISSUE TITLE
Peer_Certificate_Installed is failing after change to use REST endpoint for certificates

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1360]
After PR #1352, the Peer_Certificate_Installed ConditionalFact began returning false because it fails to install the peer trust cert.  Prior to this PR, this condition returned true, and the PeerTrust tests ran and passed.  Now they are being skipped due to this issue.  The exception encountered by the detector is:
```
  Starting:    Infrastructure.Tests
     SetupValidationTests.Peer_Certificate_Correctly_Installed [FAIL]
        System.InvalidOperationException: The peer certificate could not be installed: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Cannot find the requested object
           at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags)
           at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
           at ServiceUtilHelper.InstallPeerCertificateFromServer() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Common\Infrastructure\ServiceUtilHelper.cs:line 286
           at ServiceUtilHelper.EnsurePeerCertificateInstalled() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Common\Infrastructure\ServiceUtilHelper.cs:line 236
           at ServiceUtilHelper.ThrowIfPeerCertificateInstallationError() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Common\Infrastructure\ServiceUtilHelper.cs:line 315
           at ServiceUtilHelper.get_PeerCertificate() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Common\Infrastructure\ServiceUtilHelper.cs:line 60
           at SetupValidationTests.Peer_Certificate_Correctly_Installed() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Infrastructure\SetupValidationTests.cs:line 113
        Expected: True
        Actual:   False
        Stack Trace:
           c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Infrastructure\SetupValidationTests.cs(123,0): at SetupValidationTests.Peer_Certificate_Correctly_Installed()
  Finished:    Infrastructure.Tests

```

**Comment by roncain** [comment]
Update: this fails on all OSes.  All Helix runs show Peer_Certificate_Installed tests are being skipped now.

**Comment by iamjasonp** [comment]
@roncain, do you want me to take a look at this one?

**Comment by roncain** [comment]
@iamjasonp PR #1361 has the fix -- thanks.
