### ISSUE TITLE
is kerberos authentication working using basichttpbinding on ubuntu? 

### ISSUE THREAD

**Issue by emailtowalter** [dotnet/wcf#1387]
The code works on windows, but not cloud foundry which is ubuntu. There is a document somewhere on this site that list all the security/binding support on different platform .But I cannot find it. 

Please help. 

Thanks.

**Comment by mconnew** [comment]
Do you have any exception messages? Kerberos should work on ubuntu, but you do need to configure the kerberos client on the host to authenticate against your kdc.

**Comment by zhenlan** [comment]
Hi @emailtowalter, sorry for running into this issue. Is this the doc you are looking for?
https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v1.0.0.md

As noted in the [1.0 release notes](https://github.com/dotnet/wcf/releases/tag/v1.0.0), Windows authentication is not supported by Http transport on Linux and OS X, so the scenario you described will not work. WCF issue #946 discussed more details. The root cause is tracked by dotnet/corefx#7325.

**Comment by emailtowalter** [comment]
zhenlan... too bad kerberos is not working on linux. I guess I will have to switch to client certificate. painful. 

Before closing this issue, any idea if it will be resolved at release 1.1 time?

**Comment by zhenlan** [comment]
@emailtowalter the root-cause issue in dotnet/corefx is marked as future at this point, but @mconnew and I took a look and think we may be able to workaround the issue in WCF code, so yes, we may be able to get this particular scenario unblocked sooner. We will have this thread updated.

cc: @iamjasonp

**Comment by zhenlan** [comment]
Hong to validate if this is passing now (or get further).

**Comment by hongdai** [comment]
Still not working. The same issue as https://github.com/dotnet/wcf/issues/1569

**Comment by zhenlan** [comment]
@hongdai can we get call stack of the failure?

**Comment by hongdai** [comment]
<stack-trace><![CDATA[   at System.Security.Principal.WindowsIdentity.GetCurrent()
   at System.ServiceModel.Security.SecurityUtils.NetworkCredentialHelper.GetCurrentUserIdAsString(NetworkCredential credential)
   at System.ServiceModel.Security.SecurityUtils.AppendWindowsAuthenticationInfo(String inputString, NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel)
   at System.ServiceModel.Channels.HttpChannelFactory`1.AppendWindowsAuthenticationInfo(String inputString, NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel)
   at System.ServiceModel.Channels.HttpChannelFactory`1.GetConnectionGroupName(NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel, SecurityTokenContainer clientCertificateToken)
   at System.ServiceModel.Channels.HttpChannelFactory`1.GetHttpClient(EndpointAddress to, NetworkCredential credential, TokenImpersonationLevel impersonationLevel, AuthenticationLevel authenticationLevel, SecurityTokenContainer clientCertificateToken)
   at System.ServiceModel.Channels.HttpChannelFactory`1.<GetHttpClientAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.<GetHttpClientAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.ServiceModel.Channels.HttpsChannelFactory`1.HttpsClientRequestChannel.<GetHttpClientAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.Echo(String )
   at NegotiateStream_Http_Tests.NegotiateStream_Http_AmbientCredentials()]]></stack-trace>

**Comment by zhenlan** [comment]
This is currently tracked by #1589 and the root cause is dotnet/corefx#12618.

**Comment by zhenlan** [comment]
This should be fixed now as both #1589 and dotnet/corefx#12618 are closed.
