### ISSUE TITLE
Unit tests for valid and invalid Encodings fail in UWP.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1450]
Theory test are now being run for the first time in a long time and several tests that use the 'ValidEncodings' and 'InvalidEncodings' properties from System.ServiceModel.Tests.Common.TestData are failing.

No call stack is currently available as no test case logging yet exists for UWP runs from git.

Test cases are...
System.ServiceModel.Primitives\tests\Channels: TextMessageEncodingBindingElementTest.WriteEncoding_Property_Sets
System.ServiceModel.Primitives\tests\Channels: TextMessageEncodingBindingElementTest.WriteEncoding_Property_Set_Throws_For_Invalid_Encodings
System.ServiceModel.Http\tests\ServiceModel: BasicHttpBindingTest.TextEncoding_Property_Sets
System.ServiceModel.Http\tests\ServiceModel: BasicHttpBindingTest.TextEncoding_Property_Set_Invalid_Value_Throws

**Comment by roncain** [comment]
Example stack trace from testResults.xml:
```
      <test name="TextMessageEncodingBindingElementTest.WriteEncoding_Property_Sets" type="TextMessageEncodingBindingElementTest" method="WriteEncoding_Property_Sets" time="0" result="Fail">
        <failure exception-type="$BlockedFromReflection_0_99d688d9">
          <message><![CDATA[$BlockedFromReflection_0_99d688d9 : Reflection_InsufficientMetadata_EdbNeeded: System.Text.UnicodeEncoding. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485]]></message>
          <stack-trace><![CDATA[   at System.Reflection.Runtime.TypeInfos.RuntimeNoMetadataNamedTypeInfo.get_AnchoringTypeDefinitionForDeclaredMembers() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\TypeInfos\RuntimeNoMetadataNamedTypeInfo.cs:line 124
   at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.get_DeclaredMethods() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\TypeInfos\RuntimeTypeInfo.cs:line 183
   at Internal.Reflection.Extensions.NonPortable.MethodPolicies.GetDeclaredMembers($TypeInfo typeInfo)
   at Internal.Reflection.Extensions.NonPortable.MemberEnumerator.<GetMembersWorker>d__1$1<System.__Canon>.MoveNext()
   at System.Linq.Buffer$1<System.__Canon>..ctor(IEnumerable$1<__Canon> source)
   at System.Linq.Enumerable.ToArray<System.__Canon>(IEnumerable$1<__Canon> source)
   at System.Reflection.TypeExtensions.Disambiguate<System.__Canon>(IEnumerable$1<__Canon> members, Type[] parameterTypes)
   at System.Reflection.TypeExtensions.GetMethod(Type type, String name, Type[] types)
   at System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethod(Type type, String name, Type[] parameters)]]></stack-trace>
        </failure>
      </test>
```
