### ISSUE TITLE
UpnEndpointIdentityTest.Ctor_UpnName throws PlatformNotSupported in UWP.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1454]
No call stack is currently available as no test case logging yet exists for UWP runs from git.

Test case...
System.ServiceModel.Security\tests\ServiceModel: UpnEndpointIdentityTest.Ctor_UpnName

**Comment by roncain** [comment]
Stack trace (from testResults.xml found in bin after running in UWP) is:
```
      <test name="UpnEndpointIdentityTest.Ctor_UpnName(upn: \&quot;\&quot;)" type="UpnEndpointIdentityTest" method="Ctor_UpnName" time="0.0000619" result="Fail">
        <failure exception-type="System.PlatformNotSupportedException">
          <message><![CDATA[System.PlatformNotSupportedException : UpnEndpointIdentity is not supported on this platform]]></message>
          <stack-trace><![CDATA[   at System.ServiceModel.UpnEndpointIdentity..ctor(String upnName) in c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\UpnEndpointIdentity.cs:line 30
   at UpnEndpointIdentityTest.Ctor_UpnName(String upn) in c:\OSS\wcf\src\System.ServiceModel.Security\tests\ServiceModel\UpnEndpointIdentityTest.cs:line 22
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetVI<System.__Canon>(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CallIHelperStaticCallWithInstantiation(Object thisPtr, IntPtr methodToCall, IntPtr dynamicInvokeHelperMethod, ArgSetupState argSetupState, Boolean isTargetThisCall, IntPtr dynamicInvokeHelperGenericDictionary)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, String defaultValueString, Object[] parameters, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 464]]></stack-trace>
        </failure>
      </test>

```

**Comment by roncain** [comment]
@StephenBonikowsky -- I was able to find the exception message inside a testResults.xml file produced in the bin folder for the test.  Based on that, I retitled this issue to reflect the root cause.

**Comment by StephenBonikowsky** [comment]
Great, thanks!

**Comment by zhenlan** [comment]
@hongdai can you please check if we have functional/scenario test coverage for this?
