### ISSUE TITLE
Vs 2015 MS Test Report error  Run Common Language Runtime detected an invalid program.

### ISSUE THREAD

**Issue by som-nitjsr** [dotnet/wcf#1480]
while  Debuging  the test it works OK. But if I Run the Test It give me this Error.

Result StackTrace:  
at System.ServiceModel.Security.X509CertificateRecipientClientCredential..ctor(X509CertificateRecipientClientCredential other)
   at System.ServiceModel.Description.ClientCredentials..ctor(ClientCredentials other)
   at System.ServiceModel.Description.ClientCredentials.CloneCore()
   at System.ServiceModel.Description.ClientCredentials.Clone()
   at System.ServiceModel.Description.ClientCredentials.CreateSecurityTokenManager()
   at System.ServiceModel.Channels.HttpChannelFactory`1.InitializeSecurityTokenManager()
   at System.ServiceModel.Channels.HttpChannelFactory`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpsChannelFactory`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelFactory.TypedServiceChannelFactory`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ChannelFactory.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannelInternal()
   at System.ServiceModel.ClientBase`1.get_Channel()
   at System.ServiceModel.ClientBase`1.get_InnerChannel()
   at VMS.SF.Gateway.Tests.GatewayTests.GetSimpleResponseUsingSoap(String userName, String password) in C:\vms\sourcecode\SFA\Server\Dev\Src\WSF2\SFServer\Tests\VMS.SF.Gateway.Tests\GatewayTests.cs:line 225
   at VMS.SF.Gateway.Tests.GatewayTests.Should_not_return_simple_response_for_invalid_credentials_soap() in GatewayTests.cs:line 216
Result Message: Test method VMS.SF.Gateway.Tests.GatewayTests.Should_not_return_simple_response_for_invalid_credentials_soap threw exception System.InvalidProgramException, but exception System.ServiceModel.Security.MessageSecurityException was expected. Exception message: System.InvalidProgramException: Common Language Runtime detected an invalid program.

**Comment by zhenlan** [comment]
@som-nitjsr, it's hard to tell what went wrong. It could be an environment issue. Did you try to repair your Visual Studio and install Visual Studio 2015 Update 3? Hope that can fix the issue for you.

**Comment by som-nitjsr** [comment]
I have update 3. and I am facing this issue in windows 7 and windows 10 both.

**Comment by roncain** [comment]
Hi @som-nitjsr -- just checking back to see if this is still an issue for you.  Does the thread at https://github.com/dotnet/corefx/issues/320 say anything that might be related to what you saw?
