### ISSUE TITLE
Create scenario test to validate HttpRequestHeader via ClientMessageInspector

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1491]
We need to create a new scenario test that verifies the property headers as we did before GitHub.
Prior to moving to GitHub, we had a Mahjong test that used a ClientMessageInspector to do this:

```
        public object BeforeSendRequest(ref Message request, IClientChannel channel)
        {
            HttpRequestMessageProperty property;
            object obj2;
            if (request.Properties.TryGetValue(HttpRequestMessageProperty.Name, out obj2))
            {
                property = obj2 as HttpRequestMessageProperty;
                property.Headers["authType"] = _authenticationType;
                property.Headers[HttpRequestHeader.Authorization] = _accessToken;
            }
            else
            {
                property = new HttpRequestMessageProperty();
                property.Headers["authType"] = _authenticationType;
                property.Headers[HttpRequestHeader.Authorization] = _accessToken;
                request.Properties.Add(HttpRequestMessageProperty.Name, property);
            }
            return null;
        }
```

In this case, _authenticationType was "1" and _accessToken was "fakeAccessToken".'
We never ported this test to GitHub, and now that old test is failing on nightly runs of the pre-GitHub TFS WCF tests.  The exception we see there is:

```
System.FormatException: 'net_http_headers_invalid_value'
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index) in D:\A\_work\21\s\src\System.Net.Http\src\System\Net\Http\Headers\HttpHeaderParser.cs:line 77
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, $HeaderStoreItemInfo info, String value) in D:\A\_work\21\s\src\System.Net.Http\src\System\Net\Http\Headers\HttpHeaders.cs:line 1061
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value) in D:\A\_work\21\s\src\System.Net.Http\src\System\Net\Http\Headers\HttpHeaders.cs:line 63
   at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.PrepareMessageHeaders($Message message) in f:\dd\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 1177]]>

```

We need to establish whether this code path works properly.  It is possible the original test was passing illegal values in the headers, so we may need to change them to be legal.

**Comment by StephenBonikowsky** [comment]
Completed with PR #1640 
This add 2 tests, both ran and passed over the weekend on all platforms.
