### ISSUE TITLE
Multiple tests using https binding failed in Helix

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1493]
Note: they seem share same root cause with three different kinds of error message as showed below

1. **Test case**
Binding.Htp.Tests/Binding_Http_NetHttpsBindingTests/DefaultCtor_NetHttps_Echo_RoundTrips_String  
**Error message**
System.ServiceModel.CommunicationException : An error occurred while sending the request.
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
-------- System.Net.Http.CurlException : SSL connect error
[Log link](https://mc.dot.net/#/product/netcore/master/source/official~2Fwcf~2Fmaster/type/test~2Fscenario~2Fselfhosted~2F/build/20160825.01/workItem/Binding.Http.Tests/analysis/xunit/Binding_Http_NetHttpsBindingTests~2FDefaultCtor_NetHttps_Echo_RoundTrips_String/log/419fe893-b1c4-4377-8ef7-bb8d117ee3e5)
**Stack Trace**
  at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.Echo(String )
   at Binding_Http_NetHttpsBindingTests.DefaultCtor_NetHttps_Echo_RoundTrips_String()
----- Inner Stack Trace -----
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.ServiceModelHttpMessageHandler.<SendAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
----- Inner Stack Trace -----
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)

2. **Test case sets**
WebSocketTests-https
**Error message**
System.InvalidOperationException : An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details.
---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
-------- System.IO.IOException : An internal WebSocket error occurred. Please see the innerException, if present, for more details. 
------------ System.Net.Sockets.SocketException : Connection reset by peer
[Log link](https://mc.dot.net/#/product/netcore/master/source/official~2Fwcf~2Fmaster/type/test~2Fscenario~2Fselfhosted~2F/build/20160825.01/workItem/Extensibility.WebSockets.Tests/analysis/xunit/WebSocketTests~2FWebSocket_Https_Duplex_TextBuffered_KeepAlive/log/2baabfc0-108a-4fc1-b272-92a24c73180f)

3. **Test case**
Security.TransportSecurity.Tests\HttpsTests/ClientCertificate_EchoString 
**Error message**
System.ServiceModel.CommunicationException : An error occurred while receiving the HTTP response to https://wcfcoresrv4.cloudapp.net/wcftestservice1//ClientCertificateAccepted/HttpsClientCertificate.svc/https-client-certificate. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details.\r
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r
-------- System.Net.Http.WinHttpException : The connection with the server was terminated abnormally
[Log link](https://mc.dot.net/#/product/netcore/master/source/official~2Fwcf~2Fmaster/type/test~2Fscenario~2Fselfhosted~2F/build/20160825.01/workItem/Security.TransportSecurity.Tests/analysis/xunit/HttpsTests~2FClientCertificate_EchoString/log/dd96d432-265a-4fd0-b755-c2819f6fbf0c)

**Comment by roncain** [comment]
I believe these errors occurred because work was being done on the servers to transition to WcfCoreSrv5, including refreshing certs, stopping and restarting the selfhost server, IISReset, etc.  Let's leave this issue open until we get a clean VSO run with the server in a healthy state.

**Comment by iamjasonp** [comment]
[20160912.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fwcf~2Fmaster/type/test~2Fscenario~2Fiishosted~2F/build/20160912.04)

* Security.TransportSecurity.Tests\HttpsTests/ClientCertificate_EchoString is passing/skipped as appropriate
* All 5 tests in Binding.Http.Tests are passing/skipped 
* WebSocketTests-https all passing (except Windows 7 platform, which is skipped, and WebSocket_Https_Duplex_TextStreamed, which is skipped) 
* Security.TransportSecurity.Tests/HttpsTests/ClientCertificate_EchoString no longer fails for Windows 

Given the new results after moving to wcfcoresrv5 and the new packages, I think this issue is safe to close
