### ISSUE TITLE
NegotiateStream_Tcp_With_ExplicitUserNameAndPassword test fails

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1499]
This test can only be run manually and is therefore skipped by both CI and Helix runs.

To run it:
- Set PSEXEC_PATH to the folder where psexec.exe resides
- Start the self hosted service
- Set environment variables:

```
set ExplicitUserName={valid domain user name}
set ExplicitPassword={valid domain user's password}
```
- Run the OuterLoop test

Stack trace (minus Task await stuff) is:

```
    NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword [FAIL]
  ---ETW Trace for Test NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword Begins---
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: ChannelFactory created .
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: ServiceChannelCall started.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: Client request serialization started.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: Client completed serialization of the request message.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: ServiceChannel Open Start.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: Outbound connections per endpoint ratio: 0/10
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: Pool for [LOCALHOST, 809] has no available connection and 0 busy connections.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '61' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '23' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: WindowsStreamSecurity initiating security upgrade.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '5' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '4329' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '5' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '4272' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '5' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: SocketId:26904055 writing '8' bytes to '::1:809'.
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: Throwing an exception. Source: System.ServiceModel 4.0.0.0. Exception details: System.ServiceModel.Security.SecurityNegotiationException: A call to SSPI failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect
     --- End of inner exception stack trace ---
     at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
     at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__12.MoveNext() in c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WindowsStreamSecurityUpgradeProvider.cs:line 288
     --- End of inner exception stack trace ---
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: Outbound connections per endpoint ratio: 0/10
  ---ETW Trace for Test NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword Ends---

        System.ServiceModel.Security.SecurityNegotiationException : A call to SSPI failed, see inner exception.
        ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
        -------- System.ComponentModel.Win32Exception : The target principal name is incorrect
        Stack Trace:
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WindowsStreamSecurityUpgradeProvider.cs(292,0): at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__12.MoveNext()
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs(590,0): at System.ServiceModel.Channels.ConnectionUpgradeHelper.<InitiateUpgradeAsync>d__3.MoveNext()
            c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs(259,0): at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<SendPreambleAsync>d__10.MoveNext()
            c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ConnectionPoolHelper.cs(115,0): at System.ServiceModel.Channels.ConnectionPoolHelper.<EstablishConnectionAsync>d__15.MoveNext()
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs(322,0): at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<OnOpenAsync>d__12.MoveNext()
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(353,0): at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__73.MoveNext()
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(1351,0): at System.ServiceModel.Channels.ServiceChannel.<OnOpenAsync>d__149.MoveNext()
         c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(353,0): at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__73.MoveNext()
         c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(328,0): at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__72.MoveNext()
           c:\OSS\wcf\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs(187,0): at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(322,0): at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(1976,0): at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(2067,0): at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(503,0): at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(747,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(722,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(369,0): at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(141,0): at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
              at generatedProxy_1.Echo(String )
           c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Negotiate\NegotiateStream_Tcp_Tests.4.1.0.cs(163,0): at NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword()
           ----- Inner Stack Trace -----
              at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WindowsStreamSecurityUpgradeProvider.cs(288,0): at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__12.MoveNext()
           ----- Inner Stack Trace -----
```

**Comment by roncain** [comment]
Closing this because it no longer repro's for me in private testing -- both self-host and IIS-hosted (run with manually provided credentials against a domain-joined machine).  Assume it was a spurious error.

**Comment by roncain** [comment]
Reopening because this test once again fails for me, this time using latest packages.  Repro steps were:
```
set PSEXEC_PATH={folder containing psexec.exe}
set Windows_Authentication_Available=true
set Digest_Authentication_Available=true
set Ambient_Credentials_Available=true
set SPN_Available=true
set UPN_Available=true
set NTLM_Available=true
set Server_Domain_Joined=true
set Client_Domain_Joined=true
set Domain_Available=true
set ExplicitUserName={some valid user name}
set ExplicitPassword={password for this user}
set IncludeTestsWithIssues=true

Start the WCF self-hosted service on the same (domain joined) machine where you will run the tests and observe psexec.exe is used to launch it.

Run the OuterLoop tests.
```

Stack trace is 

```
  NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword: ChannelFactory created .
     NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword [FAIL]
        System.ServiceModel.Security.SecurityNegotiationException : A call to SSPI failed, see inner exception.
        ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
        -------- System.ComponentModel.Win32Exception : The target principal name is incorrect
        Stack Trace:
           c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WindowsStreamSecurityUpgradeProvider.cs(292,0): at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__12.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
```

**Comment by zhenlan** [comment]
@imcarolwang can you please see if you can still repro this issue?

**Comment by imcarolwang** [comment]
Verified on release/2.0.0 branch,  issue not repro any more. 
The case passes when run cross-machine (Windows to Windows) using both self-host and iis-host. It also passes when the self-host services is running on the same machine as the tests.

**Comment by zhenlan** [comment]
Great. Thank you @imcarolwang!
