### ISSUE TITLE
TypeLoader.GetIOperationBehaviorAttributesFromType fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#153]
--------------------------------
  Running Test: TypedProxyTests.ServiceContract_TypedProxy_DuplexCallback
  Assert.True:Test Scenario: ServiceContract_TypedProxy_DuplexCallback FAILED with the following errors: Unexpected exception was caught: System.PlatformNotSupportedException: GetRuntimeInterfaceMap() is not supported on this runtime.
     at System.Reflection.RuntimeReflectionExtensions.GetRuntimeInterfaceMap($TypeInfo typeInfo, Type interfaceType) in E:\ProjectK\src\NDP\FxCore\src\System.Reflection.Extensions\System\Reflection\RuntimeReflectionExtensions.cs:line 108
     at System.ServiceModel.ReflectionExtensions.GetInterfaceMap(Type type, Type interfaceType) in e:\oss\wcf\src\System.Private.ServiceModel\src\Extensions\ReflectionExtensions.cs:line 95
     at System.ServiceModel.Description.TypeLoader.GetIOperationBehaviorAttributesFromType($OperationDescription opDesc, Type targetIface, Type implType) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Description\TypeLoader.cs:line 399
     at System.ServiceModel.Description.TypeLoader.<>c__DisplayClasse.b__b(Type currentType, $KeyedByTypeCollection$1<$IOperationBehavior> behaviors) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Description\TypeLoader.cs:line 535
     at System.ServiceModel.Description.TypeLoader.ServiceInheritanceCallback$2.Invoke(Type currentType, $KeyedByTypeCollection$1<__Canon> behaviors)
     at System.ServiceModel.Description.TypeLoader.AddBehaviorsAtOneScope(Void* InstParam, Type type, __Canon descriptionBehaviors, $ServiceInheritanceCallback$2<__Canon,__Canon> callback) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Description\TypeLoader.cs:line 1863
     at System.ServiceModel.Description.TypeLoader.ApplyServiceInheritance(Void* InstParam, Type serviceType, __Canon descriptionBehaviors, $ServiceInheritanceCallback$2<__Canon,__Canon> callback) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Description\TypeLoader.cs:line 1840
     at System.ServiceModel.Description.TypeLoader.AddBehaviorsFromImplementationType($ServiceEndpoint serviceEndpoint, Type implementationType) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Description\TypeLoader.cs:line 531
     at System.ServiceModel.ChannelFactory$1.ReflectOnCallbackInstance($ServiceEndpoint endpoint) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs:line 603
     at System.ServiceModel.ChannelFactory$1.CreateDescription() in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs:line 576
     at System.ServiceModel.ChannelFactory.InitializeEndpoint($Binding binding, $EndpointAddress address) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs:line 268
     at System.ServiceModel.DuplexChannelFactory$1..ctor(Object callbackObject, $Binding binding, $EndpointAddress remoteAddress) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\DuplexChannelFactory.cs:line 141
     at System.ServiceModel.DuplexChannelFactory$1..ctor($InstanceContext callbackInstance, $Binding binding, $EndpointAddress remoteAddress) in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\DuplexChannelFactory.cs:line 42
     at TypedProxyTests.ServiceContract_TypedProxy_DuplexCallback() in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\TypedClient\TypedProxyTests.cs:line 435

**Comment by roncain** [comment]
GetRuntimeInterfaceMap throws PlatformNotSupportedException.  Its usage in TypeLoader needs to be replaced.  This failure blocks use of Duplex in NET Native.
