### ISSUE TITLE
Nettcp binding accepting wrong ServerDnsEndpointIdentity  on Linux in stress test

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1637]
**Test command**

 ./CLITest Test:HelloWorld **Binding:Nettcp** BindingSecurityMode:Transport TcpClientCredentialType:Certificate **ServerDnsEndpointIdentity:"DO_NOT_TRUST_WcfBridgeRootCA 2016-10-31T17:54:46"** ClientCertThumbprintFile:CLIENT-CERT.txt HostName:wcfcoresrv1.redmond.corp.microsoft.com CertStoreName:My CertStoreLocation:CurrentUser

>**Note:**
>"DO_NOT_TRUST_WcfBridgeRootCA 2016-10-31T17:54:46" is the CN name of the server certificate. 
>if changed the commandline as the error log indicated to use ServerDnsEndpointIdentity:"wcfcoresrv1.redmond.corp.microsoft.com" , test command would pass.

**Stack Trace**

System.ServiceModel.Security.MessageSecurityException: **Identity check failed for outgoing message. The expected DNS identity of the remote endpoint was 'DO_NOT_TRUST_WcfBridgeRootCA 2016-10-31T17:54:46' but the remote endpoint provided DNS claim 'wcfcoresrv1.redmond.corp.microsoft.com'.** If this is a legitimate remote endpoint, you can fix the problem by explicitly specifying DNS identity 'wcfcoresrv1.redmond.corp.microsoft.com' as the Identity property of EndpointAddress when creating channel proxy.
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharedPoolsOfWCFObjects.CallStats.<CallAsyncFuncAndRecordStatsAsync>d__15`1.MoveNext()

**Comment by Lxiamail** [comment]
Looks like a setup error. Close it for now. Reactive it if we see it again.
