### ISSUE TITLE
FileLoadException loading assembly 'System.Diagnostics.Debug, Version=4.0.10.0' in stress test on Linux

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1678]
>**this error occurred intermittently on test run start**

**Test log**
Start
11/23/16 6:05:04 PM 5 0
11/23/16 6:05:04 PM 4 0
11/23/16 6:05:05 PM 2 0
11/23/16 6:05:06 PM 9 0
11/23/16 6:05:06 PM 1 0
11/23/16 6:05:06 PM 8 0
11/23/16 6:05:09 PM 3 0
11/23/16 6:05:19 PM 7 0
11/23/16 6:05:20 PM 6 0
11/23/16 6:05:20 PM 0 0

Unhandled Exception: System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)
   at SharedPoolsOfWCFObjects.TestUtils.ReportFailure(String message, Boolean debugBreak)
   at SharedPoolsOfWCFObjects.Program.<>c__DisplayClass48_1.<<DoTheStressRunImpl>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SharedPoolsOfWCFObjects.Program.DoTheStressRunImpl(Func`1 testAsync)
   at SharedPoolsOfWCFObjects.Program.RunStress()
   at SharedPoolsOfWCFObjects.Program.Main(String[] args)

**sometimes got similar exception with a bit more info "A device attached to the system is not functioning"**

Test:Streaming
Binding:NetTcp
BindingSecurityMode:Transport
TcpClientCredentialType:Certificate
... ...
CertStoreName:My
CertStoreLocation:CurrentUser
async:true
StressRunDuration:10
Using 24702_u_final as the stress run name.
Start
11/23/16 7:34:49 PM 6 0
11/23/16 7:34:49 PM 7 0
11/23/16 7:34:49 PM 0 0
11/23/16 7:34:49 PM 5 0
11/23/16 7:34:49 PM 1 0
11/23/16 7:34:49 PM 4 0
11/23/16 7:34:49 PM 8 0
11/23/16 7:34:49 PM 3 0
11/23/16 7:34:49 PM 9 0
11/23/16 7:34:50 PM 2 0

Unhandled Exception: System.AggregateException: One or more errors occurred. **(Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F))** (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) (Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)
   at SharedPoolsOfWCFObjects.TestUtils.ReportFailure(String message, Boolean debugBreak)
   at SharedPoolsOfWCFObjects.Program.<>c__DisplayClass48_1.<<DoTheStressRunImpl>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SharedPoolsOfWCFObjects.Program.DoTheStressRunImpl(Func`1 testAsync)
   at SharedPoolsOfWCFObjects.Program.RunStress()
   at SharedPoolsOfWCFObjects.Program.Main(String[] args)
Aborted (core dumped)

**Comment by imcarolwang** [comment]
This does not repro any more since the hit in old earlier builds.
