### ISSUE TITLE
OutOfMemoryException in Stress Streaming test on Linux 

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1679]
>When the OutOfMemoryException occurred, observing enough memory available on windows server

Test:Streaming
Binding:NetTcp
BindingSecurityMode:Transport
TcpClientCredentialType:Certificate
ServerDnsEndpointIdentity:wcfcoresrv3.redmond.corp.microsoft.com
ClientCertThumbprintFile:CLIENT-CERT.txt
... ...
**async:false**
**StressRunDuration:10**
Using 24702_u_final as the stress run name.
Start
11/23/16 6:40:41 PM 0 0
11/23/16 6:40:41 PM 3 0
11/23/16 6:40:43 PM 4 0
11/23/16 6:40:44 PM 5 0
11/23/16 6:40:44 PM 9 0
11/23/16 6:40:45 PM 7 0
11/23/16 6:40:45 PM 1 0
11/23/16 6:40:45 PM 6 0
11/23/16 6:40:46 PM 8 0
11/23/16 6:40:46 PM 2 0

Unhandled Exception: System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> **System.OutOfMemoryException**: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(Object parameter)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.TaskFactory.StartNew(Action`1 action, Object state, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at System.Runtime.IOThreadScheduler.ScheduleCallbackHelper(SendOrPostCallback callback, Object state)
   at System.Runtime.IOThreadScheduler.ScheduleCallbackNoFlow(SendOrPostCallback callback, Object state)
   at System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation(Action continuation, Boolean flowContext)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)

**Comment by imcarolwang** [comment]
"OutOfMemoryException" not repro but NetTcp streaming scenario test error change to below: 
> Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'The message containing this stream has been closed. '.
>    at System.ServiceModel.Dispatcher.StreamFormatter.MessageBodyStream.EnsureStreamIsOpen()
>    at System.ServiceModel.Dispatcher.StreamFormatter.MessageBodyStream.get_Position()
>    at SharedPoolsOfWCFObjects.StreamingTest`2.PrintRequestDetails(StreamingRequestContext`1 requestDetails) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\tests\Stress\SharedPoolsOfWCFObjects\Tests\StreamingTest.cs:line 176
>    at SharedPoolsOfWCFObjects.CommonTest`3.ReportTimeout(CapturedRequestContext[] requestList) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\tests\Stress\SharedPoolsOfWCFObjects\Tests\CommonTest.cs:line 289
>    at SharedPoolsOfWCFObjects.OperationTimeoutTracker`1.TimeoutTracker.NotifyTimeoutCallbackOnce(Object _) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\tests\Stress\SharedPoolsOfWCFObjects\OperationTimeoutTracker.cs:line 97
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.TimerQueueTimer.CallCallback()
>    at System.Threading.TimerQueueTimer.Fire()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> ./5s_NetTcpStreaming.sh: line 1: 65210 Aborted

**Comment by KKhurin** [comment]
The ObjectDisposedException above is caused by #2193
