### ISSUE TITLE
System.IO.IOException after installing WCF Connected Service

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/wcf#1687]
After installing the WCF Connected Service I started getting the error shown below.  While searching for a solution I stumbled acrross this post:

https://github.com/xunit/xunit/issues/900

Romanx (Jul 8) suggested placing netcoreapp1.0 before net46 in the frameworks section of project.json.  I tried it and presto it works.  I even undid than re-did it so I could reproduce the error message for this post.  I am using netcoreapp1.1 and net462 however the problem/solution appear to be the same.

New working project.json:

    "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "netcoreapp1.1",
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": "1.1.0",
        "System.ServiceModel.Duplex": "4.3.0",
        "System.ServiceModel.Http": "4.3.0",
        "System.ServiceModel.NetTcp": "4.3.0",
        "System.ServiceModel.Security": "4.3.0",
        "System.Xml.XmlSerializer": "4.3.0"
      }
    },
    "net462": {
      "frameworkAssemblies": {
        "System.Runtime.Serialization": "4.0.0.0",
        "System.ServiceModel": "4.0.0.0",
        "System.Xml": "4.0.0.0"
      }
    }
    }

Error message:

------ Discover test started ------

Unable to start C:\Program Files\dotnet\dotnet.exe
dotnet-test Error: 0 : [ReportingChannel]: Waiting for message failed System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
dotnet-test Error: 0 : [ReportingChannel]: Error sending System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)
dotnet-test Error: 0 : System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(String error)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(Exception ex)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.HandleDesignTimeMessages(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.BaseDotnetTestRunner.RunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams, BuildWorkspace workspace)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
========== Discover test finished: 0 found (0:00:00.6093739) ==========

**Comment by roncain** [comment]
Thanks for the investigation and report @sam-wheat .
I see there are other discussions at [stackoverflow](http://stackoverflow.com/questions/38708034/unit-testing-code-targeting-several-frameworks-at-once-with-net-core-and-xunit).

To be clear on your particular repro: did this start happening just by installing WCF Connected Service?  By adding a WCF Connected Service to an app?  I don't know the root issue yet, but it sounds unrelated to WCF itself -- unless something WCF Connected Service is doing triggers it.

**Comment by sam-wheat** [comment]
To be clear on your particular repro: did this start happening just by installing WCF Connected Service? 
yes

By adding a WCF Connected Service to an app? 
yes

I don't know the root issue yet, but it sounds unrelated to WCF itself -- unless something WCF Connected Service is doing triggers it.

Thanks Ron, hope my data point is of value.  Looks like core/net462 are not playing together.  I'm running into errors everywhere.  Very frustrating.  This is day three.

**Comment by roncain** [comment]
Thanks @sam-wheat .
I'm trying to discover more about this issue.  It sounds like it could be the same issue as https://github.com/dotnet/coreclr/issues/5951 which was moved to https://github.com/dotnet/cli/issues/3800 for further investigation.

**Comment by StingyJack** [comment]
FWIW, this happens with mstest also. 

Create a new solution, add an asp.net core project, add a class with some empty methods, add a unit test project, code a test, get annoyed with having to run command lines outside the best ide ever, install mstest and ms test runner instead of xunit, maybe update other packages that are out of date.... and then this.
 


```
------ Discover test started ------
Discovering tests in 'E:\Projects\Mermaider\test\Mermaider.UI.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "E:\Projects\Mermaider\test\Mermaider.UI.Tests\project.json" --output "E:\Projects\Mermaider\test\Mermaider.UI.Tests\bin\Debug\netcoreapp1.1" --port 50870 --parentProcessId 2516 --no-build]
Unable to start C:\Program Files\dotnet\dotnet.exe
dotnet-test Error: 0 : [ReportingChannel]: Waiting for message failed System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()
```

```
{

  "dependencies": {
    "Mermaider.UI": "1.0.0-*",
    "MSTest.TestAdapter": "1.1.12",
    "MSTest.TestFramework": "1.1.11",
    "NETStandard.Library": "1.6.1",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    }
  },
  "description": "crap default template",
  
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {

      },
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "testRunner": "mstest",
  "title": "Mernaider.UI.Tests",
  "version": "1.0.0-*"
}
```
![image](https://cloud.githubusercontent.com/assets/15381181/23443363/50733f38-fdfc-11e6-825d-f0ff42aa8b53.png)


This is the 3rd or fourth attempt at a simple .net core app in the last few months that will be getting abandoned because it gets hosed by adding a package or two.

**Comment by hongdai** [comment]
@sam-wheat  VS2017 just released and .net core project system has significant changes. I would recommend you give it a try. Let me know if you still hit issues. I'll help you to route issues to the right people to take a look.

**Comment by zhenlan** [comment]
Closing for now. Please let us know if you need any further assistance @sam-wheat.
