### ISSUE TITLE
UWP ILC Runs Test Failure: ExpectedExceptionTests/ServiceRestart_Throws_CommunicationException

### ISSUE THREAD

**Issue by willaimyou** [dotnet/wcf#1717]
**Note:** this case only failed on UWP ILC Runs until now. 
[Logs link](https://mc.dot.net/#/product/components/master/source/official~2Fwcf~2Fmaster~2F/type/test~2Fuwpilc~2Fselfhosted~2F/build/20170102.01/workItem/Client.ExpectedExceptions.Tests/analysis/xunit/ExpectedExceptionTests~2FServiceRestart_Throws_CommunicationException)

**Message**
Assert.Throws() Failure
    Expected: typeof(System.ServiceModel.CommunicationException)
    Actual:   typeof(System.ServiceModel.EndpointNotFoundException): EndpointNotFound, http://wcfcoresrv5.cloudapp.net/WindowsCommunicationFoundation/7b2fe39d-e9ba-45b3-b4f4-93ae7e3f875b

**Stack Trace:**
trace from previous location where exception was thrown ---
       at xunit.console.netcore!<BaseAddress>+0x726e51
       at xunit.console.netcore!<BaseAddress>+0x726dee
       at xunit.console.netcore!<BaseAddress>+0x726d68
       at xunit.console.netcore!<BaseAddress>+0x61a793
       at xunit.console.netcore!<BaseAddress>+0xa05fe4
    --- End of stack trace from previous location where exception was thrown ---
       at xunit.console.netcore!<BaseAddress>+0x726e51
       at xunit.console.netcore!<BaseAddress>+0x726dee
       at xunit.console.netcore!<BaseAddress>+0x726d68
       at xunit.console.netcore!<BaseAddress>+0x877b43
       at System.ServiceModel.Channels.RequestChannel.Request(ServiceModel.Channels.Message message, TimeSpan timeout)
       at xunit.console.netcore!<BaseAddress>+0xa26f14
       at xunit.console.netcore!<BaseAddress>+0x75f884
       at xunit.console.netcore!<BaseAddress>+0x8c498d
       at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(Reflection.MethodInfo targetMethod, Object[] args)
       at xunit.console.netcore!<BaseAddress>+0x9cc7ce
       at ExpectedExceptionTests.<>c__DisplayClass7_0.<ServiceRestart_Throws_CommunicationException>b__0()
       at System.Action.Invoke()

**Build :** Master - 20170102.01 (UWP ILC Self Hosted Tests && IIS Hosted Tests)

**Failing configurations:**
- Windows.10.Amd64
  - Debug && Release

**Comment by StephenBonikowsky** [comment]
The call stack we get from the F5 run is much more useful...
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateResponseStatusCode()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.<ParseIncomingResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<ReceiveReplyAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_2.RestartService(Guid )
   at ExpectedExceptionTests.<>c__DisplayClass7_0.<ServiceRestart_Throws_CommunicationException>b__0() in D:\A\_work\4\s\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.4.1.0.cs:line 110

**Comment by StephenBonikowsky** [comment]
Seems to indicate an issue within HttpResponseMessageHelper

**Comment by zhenlan** [comment]
@StephenBonikowsky can you see if the HResult (in the InnerExcpetion) returned is the one we are expecting in code by adding debug trace. If so, please add the 'case' for this.

**Comment by StephenBonikowsky** [comment]
I have updated the test case with a validation step to make sure that the newly created service host is there and working by calling a simple echo operation.

This validation step is working and the test case is still failing with endpoint not found. This tells us that there is no issue actually hitting the desired operation. When the host is closed in the middle of the operation the wrong exception is being returned to the client.

Will do some additional investigation to better understand where the bug lies.

**Comment by StephenBonikowsky** [comment]
After analyzing the failure using perfview we clearly see that a second request is sent to the same operation after the service returned a socket error on the first call due to the operation forcibly closing the host.

So the 404 that we eventually get back in WCF is technically correct, but the second call should never have been made. So either the WinRTHttpClient or the WCF version of HttpClientHandler incorrectly retried sending the initial request.

@mconnew is following-up on this to determine which of these two is responsible.

**Comment by StephenBonikowsky** [comment]
It looks like WinRTHttpClient is the winner. @mconnew will follow-up with the correct folks to get this looked at.

Leaving this issue open in the meantime and will use it as the active issue on the test.

**Comment by StephenBonikowsky** [comment]
Reopening as we need it for the ActiveIssue on the test case.

**Comment by mconnew** [comment]
I've tracked down the issue to a bug in Windows. The UAP native HttpClient is resubmitting the POST request when the server resets the socket after the entire request has been successfully received.
