### ISSUE TITLE
async NetTcp with CertAuth/WinAuth deadlock in Stress test

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1731]
**Test scenario**:  
- CertAuth\3a.NetTcpHello.cmd
- WinAuth\3a.NetTcpHello.cmd

**Scenarios with probably the same cause**: 
- CertAuth\4a.NetTcpDuplex.cmd
- CertAuth\4s.NetTcpDuplex.cmd
- WinAuth\4a.NetTcpDuplex.cmd
- WinAuth\4s.NetTcpDuplex.cmd

**Error log**:
Eating timeout #21
Eating timeout #15
System.TimeoutException: Opening the net.tcp://cspod222-10c1.xmlab.net/WcfService1/Service1.svc/netTcpCert channel timed out after 00:01:00. The time allotted to this operation may have been a portion of a longer timeout.
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharedPoolsOfWCFObjects.CallStats.<CallAsyncFuncAndRecordStatsAsync>d__15`1.MoveNext()

**Comment by zhenlan** [comment]
From @KKhurin 
- This happens even on single thread
- When this issue happens (async), it has the same stack trace as the sync case

**Comment by imcarolwang** [comment]
Issue not repro in recent builds. All mentioned affected scenarios now passed.
