### ISSUE TITLE
Error "XmlReflectionMember cannot be used on the current platform" caused by PR #1727

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1739]
The PR #1727 caused a significant increase in our F5 run test failures due to the following...

`System.InvalidOperationException : The API 'System.Xml.Serialization.XmlReflectionMember' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.`

Call Stack

```
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xml.Serialization.XmlMappingTypeReflectionWrapper..ctor(Type type, Object[] parameters)
   at System.Xml.Serialization.XmlMappingTypeReflectionWrapper..ctor(Type type)
   at System.Xml.Serialization.XmlMappingTypeReflectionWrapperFactory.GetWrapper(Type type)
   at System.Xml.Serialization.XmlMappingTypeWrapperFactory.GetWrapper(Type type)
   at System.Xml.Serialization.XmlReflectionMember..ctor()
   at System.ServiceModel.Description.XmlSerializerHelper.GetXmlReflectionMember(XmlName memberName, XmlName elementName, String ns, Type type, MemberInfo additionalAttributesProvider, Boolean isMultiple, Boolean isWrapped)
   at System.ServiceModel.Description.XmlSerializerHelper.GetXmlReflectionMember(MessagePartDescription part, Boolean isRpc, Boolean isWrapped)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.LoadHeadersMapping(MessageDescription message, String mappingKey)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.CreateMessageInfo(MessageDescription message, String key)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.EnsureMessageInfos()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.EnsureMessageInfos()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.get_Request()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.CreateFormatter()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.System.ServiceModel.Description.IOperationBehavior.ApplyClientBehavior(OperationDescription description, ClientOperation proxy)
   at System.ServiceModel.Description.DispatcherBuilder.BindOperations(ContractDescription contract, ClientRuntime proxy, DispatchRuntime dispatch)
   at System.ServiceModel.Description.DispatcherBuilder.ApplyClientBehavior(ServiceEndpoint serviceEndpoint, ClientRuntime clientRuntime)
   at System.ServiceModel.Description.DispatcherBuilder.BuildProxyBehavior(ServiceEndpoint serviceEndpoint, BindingParameterCollection& parameters)
   at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory(ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose)
   at System.ServiceModel.ChannelFactory.CreateFactory()
   at System.ServiceModel.ChannelFactory.OnOpening()
   at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at MessageContractTests_4_4_0.Message_With_MessageHeaders_RoundTrips() in D:\A\_work\68\s\src\System.Private.ServiceModel\tests\Scenarios\Contract\Message\MessageContractTests.4.4.0.cs:line 27

```

**Comment by shmao** [comment]
Here's the list of Contract.Message.Tests starting failing since [20170109.02](https://mc.dot.net/#/product/components/master/source/official~2Fwcf~2Fmaster~2F/type/test~2Fuwp~2Fselfhosted~2F/build/20170109.02).

```
MessageContract_IsWrapped_False	
MessageContract_IsWrapped_True	
MessageHeader_MustUnderstand_False	
MessageHeader_MustUnderstand_True
Message_With_MessageHeaders_RoundTrips
Echo_With_CustomClientMessageFormatter_RoundTrips_String
```

**Comment by shmao** [comment]
Closing the issue. The issue should have been resolved by the recent WCF UWP work.
