### ISSUE TITLE
Unable to ignore server certificate errors in Linux

### ISSUE THREAD

**Issue by TroelsL** [dotnet/wcf#1749]
I used the new Add Connected Service feature to add service references in my .NET Core project based on WDSLs.

Now, since the service I'm communicating with is a legacy device, its certificate is out of date/self-signed/broken chained.

I fixed this by adding:

`client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication()
            {
                CertificateValidationMode = X509CertificateValidationMode.None,
                RevocationMode = X509RevocationMode.NoCheck
            };`

This solved the issue on Windows, but when I deploy my solution to docker (using the official image), it doesn't. I have also tested on Ubuntu.

I get the following error:

`Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference'1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.ServiceModelHttpMessageHandler.<SendAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable'1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.HttpChannelFactory'1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at Asgard.Ihc.Controller.IhcController.<Connect>d__15.MoveNext() in /home/tvl/Asgard.Ihc.Api/src/Asgard.Ihc.Controller/IhcController.cs:line 72
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Asgard.Ihc.Api.IhcMonitor.Start() in /home/tvl/Asgard.Ihc.Api/src/Asgard.Ihc.Api/IhcMonitor.cs:line 23
   at Asgard.Ihc.Api.Program.Main(String[] args) in /home/tvl/Asgard.Ihc.Api/src/Asgard.Ihc.Api/Program.cs:line 18
Aborted (core dumped)`

Is this a known issue, am I doing it wrong, and is there a workaround in case of the former?

I have also tried adding the code below to no avail:

`client.ClientCredentials.ServiceCertificate.Authentication.CertificateValidationMode = X509CertificateValidationMode.None;
            client.ClientCredentials.ServiceCertificate.Authentication.RevocationMode = X509RevocationMode.NoCheck;`

**Comment by TroelsL** [comment]
After some investigation, I'm beginning to doubt that it is a SSL error. I installed the certificate on the Ubuntu machine, and I still get the same error.

**Comment by TroelsL** [comment]
Still digging into this. If I call my service 'https://myhost/ws/authentication' on ubuntu with:
curl https://myhost/ws/authentication
I get:
`curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.`

If I add -sssv3, I get an actual certificate validation error:
`*   Trying myhost...
* Connected to myhost (192.168.1.xx) port 443 (#0)
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
* found 700 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using SSL3.0 / RSA_AES_128_CBC_SHA1
*        server certificate verification OK
*        server certificate status verification SKIPPED
* SSL: certificate subject name (LK IHC Controller) does not match target host name 'myhost'
* Closing connection 0`

With `System.Net.ServicePointManager.SecurityProtocol` gone, how can I force it to accept SSLv3.

**Comment by mconnew** [comment]
Unfortunately, HttpClient doesn't support SSL3. If you check the source of `System.Net.Http.CurlHandler.SslProvider.SslCtxCallback` [here](https://github.com/dotnet/corefx/blob/28e8fdf7fb6717e29206a155abc6d92308ef3663/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.SslProvider.cs#L153), you'll see SSL3 is specifically disabled. There's nothing that can be done in WCF to enable this. SSL3 is now considered completely insecure and provides no real security over using plain HTTP. Can you switch to using HTTP or is there any means to upgrade the server to use a more secure protocol? If not, then my only suggestion is to open an issue in the corefx repo asking for a mechanism to allow SSL3 for connecting to legacy systems which have no means of upgrade. The only possible option I can think of for you to unblock yourself would be to build and install a modified version of libcurl which ignores the specified protocols and is hard coded to allow SSL3. This is potentially risky though as it could make any other application on the host which uses libcurl vulnerable to SSL3 attacks.

**Comment by TroelsL** [comment]
I feared as much. I read about how SSL is now persona non grata at .NET Core. I completely understand that SSL is open to many vulnerabilities, but unfortunately, as you already guessed, I have absolutely no control over the legacy device in the other end.

I think completely disabling SSL is a bad choice as it makes .NET Core non-functional for legacy systems. I'd have to resort to python or *shudder* Java.

I don't quite understand why my app works on Windows though... From what I read on corefx, it shouldn't work on any platform... I even ran the SSL test app someone made, and saw that SSL was disabled.
