### ISSUE TITLE
DuplexChannelShapeTests.IDuplexSessionChannel_Tcp_NetTcpBinding fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#192]
Unclear if this is a product or test bug.

  Running Test: DuplexChannelShapeTests.IDuplexSessionChannel_Tcp_NetTcpBinding
  Assert.True:Test Scenario: CustomBindingTest FAILED with the following errors: Unexpected exception was caught: System.IO.IOException: An existing connection was forcibly closed by the remote host. (Exception from HRESULT: 0x80072746) ---> System.Exception: An existing connection was forcibly closed by the remote host. (Exception from HRESULT: 0x80072746)
     --- End of inner exception stack trace ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\ProjectK\src\NDP\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.IO.StreamOperationAsyncResult.ThrowWithIOExceptionDispatchInfo(Exception e) in E:\ProjectK\src\NDP\fxcore\src\System.Runtime.WindowsRuntime\System\IO\StreamOperationAsyncResult.NETNative.cs:line 13
     at System.IO.StreamOperationAsyncResult.ProcessCompletedOperation() in E:\ProjectK\src\NDP\fxcore\src\System.Runtime.WindowsRuntime\System\IO\StreamOperationAsyncResult.cs:line 231
     at System.IO.WinRtToNetFxStreamAdapter.EndRead(IAsyncResult asyncResult) in E:\ProjectK\src\NDP\fxcore\src\System.Runtime.WindowsRuntime\System\IO\WinRtToNetFxStreamAdapter.cs:line 509
     at System.IO.WinRtToNetFxStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count) in E:\ProjectK\src\NDP\fxcore\src\System.Runtime.WindowsRuntime\System\IO\WinRtToNetFxStreamAdapter.cs:line 564
     at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count) in E:\ProjectK\src\NDP\fxcore\src\System.Runtime.WindowsRuntime\System\IO\BufferedStream.cs:line 555
     at System.ServiceModel.Channels.RTSocketConnection.ReadCore$catch$2() in e:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RTSocketConnection.cs:line 430
     at System.ServiceModel.Channels.SocketConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout) in e:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SocketConnection.cs:line 324
     at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout) in e:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Connection.cs:line 99
     at System.ServiceModel.Channels.SessionConnectionReader.Receive(TimeSpan timeout) in e:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SessionConnectionReader.cs:line 212
     at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout) in e:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SynchronizedMessageSource.cs:line 113
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.Receive(TimeSpan timeout) in e:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TransportDuplexSessionChannel.cs:line 92
     at DuplexChannelShapeTests.IDuplexSessionChannel_Tcp_NetTcpBinding() in e:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\ChannelLayer\DuplexChannelShapeTests.cs:line 52

**Comment by StephenBonikowsky** [comment]
Cannot reproduce this failure, ran the OSS tests in ToF against NET Native.
