### ISSUE TITLE
Certificate authentication Https-Async-Streaming scenario fail with ObjectDisposedExcpetion in stress test

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#2193]
Test command: CertAuth\2a.HttpStreaming.cmd

**Test paramters:**
> Binding:Https
> 	Async:true
> 	Test:Streaming
> 	BindingSecurityMode:Transport
> 	HttpClientCredentialType:Certificate
> 	ServerDnsEndpointIdentity:WCFStressServerCert
>         **Stresslevel: 10**
> 	StressRunDuration:915

**Restart test with just 2 stress threads – stressLevel=2 passed**
	
**Failure callstack:**
``Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The message containing this stream has been closed. '.
   at System.ServiceModel.Dispatcher.StreamFormatter.MessageBodyStream.EnsureStreamIsOpen()
   at System.ServiceModel.Dispatcher.StreamFormatter.MessageBodyStream.get_Position()
   at SharedPoolsOfWCFObjects.StreamingTest`2.PrintRequestDetails(StreamingRequestContext`1 requestDetails) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\
tests\Stress\SharedPoolsOfWCFObjects\Tests\StreamingTest.cs:line 176
   at SharedPoolsOfWCFObjects.CommonTest`3.ReportTimeout(CapturedRequestContext[] requestList) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\tests\Stress\
SharedPoolsOfWCFObjects\Tests\CommonTest.cs:line 289
   at SharedPoolsOfWCFObjects.OperationTimeoutTracker`1.TimeoutTracker.NotifyTimeoutCallbackOnce(Object _) in E:\OSS\carol\wcf\src\System.Private.ServiceModel\t
ests\Stress\SharedPoolsOfWCFObjects\OperationTimeoutTracker.cs:line 97
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()``

**Comment by Lxiamail** [comment]
Close it for now. Reactive it if we see it again.
