### ISSUE TITLE
Basic Authentication: empty user name should throw ArgumentException

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#224]
For the same empty user name scenario:
On desktop, it throws ArgumentException, message: "The username cannot be empty."
On ProjectK, it throws MessageSecurityException, message:"The HTTP request was forbidden with client authentication scheme 'Basic'."

The exception and the message does not help on ProjectK. It needs to be fixed to match desktop.

**Comment by hongdai** [comment]
Exception callstack from desktop:
System.ArgumentException: The username cannot be empty.

Server stack trace:
   at System.IdentityModel.Tokens.UserNameSecurityToken..ctor(String userName, S
tring password, String id)
   at System.IdentityModel.Tokens.UserNameSecurityToken..ctor(String userName, S
tring password)
   at System.IdentityModel.Selectors.UserNameSecurityTokenProvider..ctor(String
userName, String password)
   at System.ServiceModel.ClientCredentialsSecurityTokenManager.CreateSecurityTo
kenProvider(SecurityTokenRequirement tokenRequirement, Boolean disableInfoCard)
   at System.ServiceModel.ClientCredentialsSecurityTokenManager.CreateSecurityTo
kenProvider(SecurityTokenRequirement tokenRequirement)
   at System.ServiceModel.Channels.TransportSecurityHelpers.GetUserNameTokenProv
ider(SecurityTokenManager tokenManager, EndpointAddress target, Uri via, String
transportScheme, AuthenticationSchemes authenticationScheme, ChannelParameterCol
lection channelParameters)
   at System.ServiceModel.Channels.HttpChannelFactory`1.CreateAndOpenTokenProvid
er(TimeSpan timeout, AuthenticationSchemes authenticationScheme, EndpointAddress
 target, Uri via, ChannelParameterCollection channelParameters)
   at System.ServiceModel.Channels.HttpChannelFactory`1.CreateAndOpenTokenProvid
ersCore(EndpointAddress to, Uri via, ChannelParameterCollection channelParameter
s, TimeSpan timeout, SecurityTokenProviderContainer& tokenProvider, SecurityToke
nProviderContainer& proxyTokenProvider)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.Creat
eAndOpenTokenProviders(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpsChannelFactory`1.HttpsRequestChannel.OnO
pen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceMod
el.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeo
ut)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeS
pan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)

   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean on
eway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan tim
eout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCall
Message methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   at ConsoleApplication1.IWcfCustomUserNameService.Echo(String message)
   at ConsoleApplication1.Program.BasicAuthenticationInvalidPwd_throw_MessageSec
urityException() in C:\test\ConsoleApplication1\ConsoleApplication1\Program.cs:l
ine 42
