### ISSUE TITLE
11 failure with 'InvalidOperationException/PlatformNotSupportedException' on OSX in "the Weekly OSX Kerberos Tests"

### ISSUE THREAD

**Issue by willaimyou** [dotnet/wcf#2256]
OSX Kerberos Tests failure:  **total 11**, **5** 'InvalidOperationException', **6** 'PlatformNotSupportedException'

 1. Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString
 2. Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString
 3. Tcp_ClientCredentialTypeTests.NetTcp_SecModeTrans_Duplex_Callback_Succeeds
 4. HttpsTests.ServerCertificateValidation_EchoString
 5. HttpsTests.ClientCertificate_EchoString

1-5 Faiure callstack is below:

> - System.InvalidOperationException : The client certificate could not be installed: Interop+AppleCrypto+AppleCommonCryptoCryptographicException: User interaction is not allowed.
--- End of inner exception stack trace ---
 at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle) in /Users/buildagent/agent/_work/30/s/corefx/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.X509.cs:line 182\n   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in /Users/buildagent/agent/_work/30/s/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/CertificatePal.cs:line 117\n   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags) in /Users/buildagent/agent/_work/30/s/corefx/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs:line 81\n   at ServiceUtilHelper.InstallClientCertificateFromServer() in /Users/wcfcore/git/wcf/src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs:line 277\n   at ServiceUtilHelper.EnsureClientCertificateInstalled() in /Users/wcfcore/git/wcf/src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs:line 177]]></message>
--- End of inner exception stack trace ---
at ServiceUtilHelper.ThrowIfClientCertificateInstallationError() in /Users/wcfcore/git/wcf/src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs:line 306
   at ServiceUtilHelper.get_ClientCertificate() in /Users/wcfcore/git/wcf/src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs:line 51
   at Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString() in /Users/wcfcore/git/wcf/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs:line 35

 6. Tcp_ClientCredentialTypeTests.NetTcp_SecModeTrans_CertValMode_PeerTrust_Succeeds_In_TrustedPeople
 7. Tcp_ClientCredentialTypeTests.NetTcp_SecModeTrans_CertValMode_PeerOrChainTrust_Succeeds_ChainTrusted
 8. Tcp_ClientCredentialTypeTests.NetTcp_SecModeTrans_CertValMode_PeerTrust_Fails_Not_In_TrustedPeople
 9. HttpsTests.Https_SecModeTrans_CertValMode_PeerOrChainTrust_Succeeds_ChainTrusted
 10. HttpsTests.Https_SecModeTrans_CertValMode_ChainTrust_Succeeds_ChainTrusted
 11. HttpsTests.Https_SecModeTrans_CertValMode_PeerTrust_Fails_Not_In_TrustedPeople

6-11 Faiure callstack is below:

> - System.PlatformNotSupportedException : Peer Trust certificate validation is not supported on OSX. See https://go.microsoft.com/fwlink/?linkid=849976 for details.
--- End of inner exception stack trace ---
at System.ServiceModel.Security.X509ServiceCertificateAuthentication.set_CertificateValidationMode(X509CertificateValidationMode value) in /Users/wcfcore/git/wcf/src/System.Private.ServiceModel/src/System/ServiceModel/Security/X509ServiceCertificateAuthentication.cs:line 70
   at HttpsTests.Https_SecModeTrans_CertValMode_PeerOrChainTrust_Succeeds_ChainTrusted() in /Users/wcfcore/git/wcf/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs:line 152

**Comment by hongdai** [comment]
Checking with William if the machine enlistment is up to date. Some of the tests should not get run as they are disabled by the active issue, for example:
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs#L17

**Comment by willaimyou** [comment]
I checked the enlistment was up to date. And the 11 failures are still report.

**Comment by hongdai** [comment]
Update:
Failure 6-11 should be skipped by active issues. They get run because of test framework does not discover the actual OS correctly. This will be fixed by Matt.
Failure 1-5: those tests are not part of the manual run and should fail in the CI or Helix. All certificates tests did not get run in CI and Helix for various reasons. We will fix CI and Helix first to ensure the tests get run daily.

**Comment by hongdai** [comment]
I have verified all failures have been fixed in the manual run.
