### ISSUE TITLE
No match was found for the specified search criteria and package name 'System.Runtime.Serialization.Primitives'

### ISSUE THREAD

**Issue by StingyJack** [dotnet/wcf#2469]
This was working recently, but now its breaking builds as the package cannot be downloaded. 

I tried to push a copy to our private nugetserver repo, but it barks about the nuspec being somehow invalid 
```
 Process information: 
    Process ID: 5016 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\ASP.NET v4.0 
 
Exception information: 
    Exception type: InvalidOperationException 
    Exception message: 'System.Runtime.Serialization.Primitives' already has a dependency defined for 'System.Runtime'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest(Func`1 manifestStreamFactory)
   at NuGet.ZipPackage..ctor(Stream stream)
   at NuGet.Server.Publishing.PackageService.CreatePackage(HttpContextBase context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
``

**Comment by zhenlan** [comment]
Issue moved to [dotnet/corefx #26222](https://github.com/dotnet/corefx/issues/26222) via [**ZenHub**](https://www.zenhub.com/)
