### ISSUE TITLE
Test case failure on Windows 10 Nano - MessageSecurityException

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2563]
Message:
`System.ServiceModel.Security.MessageSecurityException : The HTTP request is unauthorized with client authentication scheme 'Digest'. The authentication header received from the server was 'Digest realm=\"f8f85\", nonce=\"Mi8xMy8yMDE4IDEyOjE2OjQ5IEFN\", opaque=\"0000000000000000\", stale=false, algorithm=MD5, qop=\"auth\"'.`

Stack Trace:
```
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_2.Echo(String )
   at Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain()
```

**Comment by StephenBonikowsky** [comment]
I don't have a way to tell Windows 10, Windows 10 Core and Windows 10 Nano apart at runtime so I can't use our test infrastructure to skip it only on Nano. So I either skip on all three in order to get clean runs or let it continue to fail.

RID and OS Description are identical on all three OS versions.

**Comment by StephenBonikowsky** [comment]
@zhenlan @mconnew Suggestions on how to handle this test while we investigate?

**Comment by zhenlan** [comment]
@mconnew will enable more logging on the server to capture the failed request so we can see what's the difference between the request sent from nano and sent from other platforms.

**Comment by Lxiamail** [comment]
SocketHttpHandler is available, the test may be fixed.

**Comment by StephenBonikowsky** [comment]
Haven't had a chance to check yet.

**Comment by StephenBonikowsky** [comment]
CoreFx is able to skip only Nano...
http://source.dot.net/#CoreFx.Private.TestUtilities/System/PlatformDetection.cs,13
