### ISSUE TITLE
Investigate and enhance SendTimeout_For_Long_Running_Operation_Throws_TimeoutException

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#273]
This scenario test recently failed with this exception, indicating possible product failure or incorrect test assumptions.

  --------------------------------
  Running Test: ExpectedExceptionTests.SendTimeout_For_Long_Running_Operation_Throws_TimeoutException
  Assert.InRange:Expect value between 5000 and 10000 inclusive. Actual: 4994
  Xunit.AssertTestException: Assert.InRange: Expect value between 5000 and 10000 inclusive. Actual: 4994
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.InRange(Int64 actual, Int64 low, Int64 high) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 576
     at ExpectedExceptionTests.SendTimeout_For_Long_Running_Operation_Throws_TimeoutException() in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 165
     at EntryPointMain.b__3() in e:\ProjectK\src\QA\ToF\PN\x86\dbg\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ExpectedExceptions\Client.ExpectedExceptions.Tests.main.cs:line 16
     at System.Action.InvokeOpenStaticThunk()
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

I recommend 3 things:
1. Investigate how the test might timeout before its SendTimeout
2. Hard-coded expectations of test execution time usually make tests that fail sporadically.  Find a better way to ensure the timeout exception happened due to the timeout mechanisms.  Don't assume a busy lab machine will behave the same as your dev machine.
3. Remove from the server code any hard coded time delay.  That information should flow from the client test to the server.  There should never be magic constants or behavior on the server that the test somehow knows about.

**Comment by roncain** [comment]
Incidentally, this has failed for me more than once.  The most recent time, the timeout value was 4999.

**Comment by iamjasonp** [comment]
The latest update to beta7 packages has started causing this test to fail - it's as if the request was on a 10 second timeout rather than a 5 second timeout

**Comment by roncain** [comment]
This test was failing sporadically with a timeout > 10 seconds before beta7, especially in ToF.

**Comment by roncain** [comment]
One interesting data point @iamjasonp, @mconnew and @StephenBonikowsky -- on NET Native this test fails because the elapsed time is unexpectedly short (<5000 ms) but on CoreCLR it fails because it is too long (>10000 ms).  This might imply CoreCLR-specific issues with the timeout exception not being thrown until the operation has completed.

**Comment by StephenBonikowsky** [comment]
I've been debugging in CoreCLR and the issue seems to be in mscorlib, still investigating.

**Comment by mconnew** [comment]
I've submitted a PR dotnet/corefx#3477 to fix this issue in HttpClient.

**Comment by StephenBonikowsky** [comment]
Opened Issue #3464 (https://github.com/dotnet/corefx/issues/3464) in fxcore.

**Comment by iamjasonp** [comment]
@mconnew, @StephenBonikowsky, should we re-enable this issue so we can continue to track this issue? Or is the underlying issue already fixed?

**Comment by roncain** [comment]
@davidsh said this was fixed in PR #3000 so I recommend we remove [ActiveIssue(273)] from the test and watch it for stability.
