### ISSUE TITLE
A call to SSPI failed: The target principal name is incorrect

### ISSUE THREAD

**Issue by vlmironoff** [dotnet/wcf#2805]
I have ported a simple method consuming MS Dynamics AX WCF Service from .net framework to .net core 2.0 (console application).

In .net core project I added the connected service with no problem. All types were auto-generated correctly and I didn't have to do much refactoring.
However when I call the client this is the exception I'm getting:
Could you assist me please?
I'm using VS 2017 v15.6.6

`Unhandled Exception: System.ServiceModel.Security.SecurityNegotiationException: A call to SSPI failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.CheckCompletionBeforeNextSend(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.ReadCallback(IAsyncResult transportResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.NegotiateStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WcfTest.Program.<CreateSalesOrder>d__1.MoveNext() in C:\Users\vmi\Source\Repos\WcfTest\WcfTest\Program.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at WcfTest.Program.<CreateSalesOrder>d__1.MoveNext() in C:\Users\vmi\Source\Repos\WcfTest\WcfTest\Program.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WcfTest.Program.<Main>d__0.MoveNext() in C:\Users\vmi\Source\Repos\WcfTest\WcfTest\Program.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WcfTest.Program.<Main>(String[] args)`

**Comment by mconnew** [comment]
You are using Windows authentication as your authentication mechanism. When using Windows authentication, the identity of the server is also validated. The way this happens is when you get an authentication token from the domain controller to give to the server, the token is obtained for a specific identity of the server. The default identity used is HOST/dnsname. This identity (or spn) can only be used by the `SYSTEM` or `NETWORK SERVICE` account (which includes the default identity used in IIS for the application pool user). If the server isn't running with one of these accounts (or equivalent in the case of IIS), then a different identity will be used. Either an explicit identity will be provided on the servers binding (in which case the user running the service needs permission to that identity) or the service will use the identity of the user it is running with. In the case of a user identity, this will be in the active directory username format of user@domain, e.g. dynamics@contoso.com.  
One of two things is happening. Either you need to specify the correct server identity in your client binding, or we might have a bug in the .Net core stack somewhere (WCF, corefx, WCF Connected Service tool etc). So now I've given you some background on what's happening, we need to narrow it down.  
Are you running on Linux or Windows?  
Can you generate a client running on the full framework which works correctly? If so, can you provide the binding config which is generated for the full framework and the binding code generated for .Net Core including the code which creates the endpoint. Feel free to anonymize any usernames, host names and domain names, just be consistent across the two sets of bindings. E.g. you could use hostname `myserver`, domain `contoso.com` and username `user`.

**Comment by vlmironoff** [comment]
I use Windows.
Here is the binding config from .Net Framework project (working):

`<endpoints>
    <endpoint normalizedDigest="<?xml version="1.0" encoding="utf-16"?><Data address="net.tcp://[MY_SERVER]:[PORT]/[URI]" binding="netTcpBinding" bindingConfiguration="NetTcpBinding_SalesOrderService" contract="SalesService.SalesOrderService" name="NetTcpBinding_SalesOrderService"><identity><userPrincipalName value="myuser@mydomain"/></identity></Data>" digest="<?xml version="1.0" encoding="utf-16"?><Data address="net.tcp://[MY_SERVER]:[PORT]/[URI]" binding="netTcpBinding" bindingConfiguration="NetTcpBinding_SalesOrderService" contract="SalesService.SalesOrderService" name="NetTcpBinding_SalesOrderService"><identity><userPrincipalName value="myuser@mydomain"/></identity></Data>" contractName="SalesService.SalesOrderService" name="NetTcpBinding_SalesOrderService" />
</endpoints>`

And this is the binding config from .Net Core 2.0 project (not working):

`{
  "ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf",
  "Version": "15.0.20119.1312",
  "ExtendedData": {
    "Uri": "http://[MY_SERVER]:[PORT]/[URI]",
    "Namespace": "SalesService",
    "SelectedAccessLevelForGeneratedClass": "Public",
    "GenerateMessageContract": false,
    "ReuseTypesinReferencedAssemblies": true,
    "ReuseTypesinAllReferencedAssemblies": true,
    "CollectionTypeReference": {
      "Item1": "System.Array",
      "Item2": "System.Runtime.dll"
    },
    "DictionaryCollectionTypeReference": {
      "Item1": "System.Collections.Generic.Dictionary`2",
      "Item2": "System.Collections.dll"
    },
    "CheckedReferencedAssemblies": [],
    "InstanceId": null,
    "Name": "SalesService",
    "Metadata": {}
  }
}`

Thank you.

**Comment by mconnew** [comment]
You didn't quite provide the information needed from the Connected Service output. The binding is done in code and not config file with Connected Services. The problem is caused by the service identity not being correctly set on the ChannelFactory. From your existing config the relevant section is:
```xml
<identity>
  <userPrincipalName value="myuser@mydomain"/>
</identity>
```
The error message in the exception is basically saying that the security token you got from the domain controller to authenticate to the server was for a server with a different identity. If the identity is missing, we use the dns hostname and generate an ServicePrincipleName with the value `HOST/hostname`.

**Comment by naojamg** [comment]
I'm having the same issue with an AIF Dynamics Service only in .net core, do you know how to set in code the userPrincipalName? or the needed service indentity on the channel factory as you mentioned? Thanks :)

**Comment by HongGit** [comment]
@mconnew could you please chime in?

**Comment by Dawiducik** [comment]
> I'm having the same issue with an AIF Dynamics Service only in .net core, do you know how to set in code the userPrincipalName? or the needed service indentity on the channel factory as you mentioned? Thanks :)

Did you find any solution? I have exactly the same problem

**Comment by naojamg** [comment]
As i can remember, there was a problem in the port of the soap service a was using, one url looks like this `x.x.x.x:8101/DynamicsAx/Services/TIFacturasServicios` and the other was `x.x.x.x:8201/DynamicsAx/Services/TIFacturasServicios` i was using the incorrect, i don't remember what was the correct... after thar i simply use the connected services tool in VS and everything worked fine

**Comment by Dawiducik** [comment]
Well, I've set my identity with `new UpnEndpointIdentity("dynamics@contoso.com")` (I guess UPN = UserPrincipalName) and now it works, thanks for good willings anyway @naojamg :)

**Comment by Dawiducik** [comment]
I don't know how, but it looks like you predicted my next problem and your advice with switching the ports was soooo helpful.
But why is AX generating "wrong" port? (Maybe not really wrong)
Many thanks @naojamg ❤️

**Comment by naojamg** [comment]
@Dawiducik hahaha AX is a little old, i was using 2012 version and the ports was generated automatically by AX, it seems like both ports are used but i never knew why one is only the correct for the connection (・_・ヾ

**Comment by chessdr** [comment]
Well, I've set my identity with new UpnEndpointIdentity("dynamics@contoso.com")

I think we're having the same issue as Dawiducik, as we're also trying to get an AIF services working using Net Core 3.1 in our Dynamics AX 2012 environment.  I see where he added the statement UpnEndPointIdentity("dynamics@contoso.com"), but where does this statement go?

**Comment by Dawiducik** [comment]
@chessdr 
This is part of my code with **TimesheetService** running.

```csharp
var timesheetServiceUrl = "net.tcp://<dynamics-address>:8201/DynamicsAx/Services/TimesheetServices";

// My binding, note that it doesn't have to be TCP, can be HTTP as well
var binding = new NetTcpBinding
{
	MaxReceivedMessageSize = 2000000 // Just to test, change if needed larger
};
binding.Security.Mode = SecurityMode.Transport;
binding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Windows;

// Prepare identity
var endpointIdentity = new UpnEndpointIdentity("dynamics@contoso.com"); // Where "dynamics@contoso.com" is the user running AOS instance on server

try
{
	var uri = new Uri(timesheetServiceUrl);
	var endpointAddress = new EndpointAddress(uri, endpointIdentity); // You can see "UpnEndpointIdentity" referenced here.
	var timesheetClient = new TSTimesheetClient(binding, endpointAddress);

	await timesheetClient.OpenAsync();

	// Prepare context to your company
	var context = new AxServices.Timesheet.CallContext
	{
		Company = "COM1" 
	};
	
	// and call the method
	var timesheet = await timesheetClient.getTimesheetDetailsByNumberAsync(context, "XYZ-281441");
	
	// you can also reference "null" as the first argument
	// var timesheet = await timesheetClient.getTimesheetDetailsByNumberAsync(null, "XYZ-281441");
	
	// then process timesheet as you like
	// "Dump" is my extension on object, serializing to JSON and streaming output to console
	timesheet.response.Dump();
	
	var timesheetId = timesheet.response.parmTimesheetNbr;
	Console.WriteLine($"Received timesheet: {timesheetId}.");

	await timesheetClient.CloseAsync();
}
catch (TimeoutException ex)
{
	// Handle exception
}
catch (CommunicationException ex)
{
	// Handle exception
}
```

**Comment by chessdr** [comment]
We were able to use the above code with just a few modifications as we were creating an AX Transfer Order, and it worked great!  Now we can go try and create AX Purchase Orders and AX Sales Orders.  Thank you so much, Dawiducik for the great example above!!

**Comment by mconnew** [comment]
@chessdr and @Dawiducik, FYI, UpnEndpointIdentity only works for NetTcpBinding. For HTTP, we are lacking functionality in HttpClient. If you need to use HTTP, I can point you to the open issue for you to add your voice.

**Comment by Dawiducik** [comment]
@mconnew Point me to the issue in HttpClient, I will look at it in free time

**Comment by mconnew** [comment]
The issue is dotnet/runtime#25320

**Comment by chekm8** [comment]
I am experiencing the same issue.  I have a WCF Service running as a Windows service and a WCF client calling that service.  The client is using Windows auth.  If I have the Windows Service running as 'Network Service' there are not issues.  Once I change that to run as a domain account I get "The target principal name is incorrect" exception on the client with "System.ServiceModel.Security.SecurityNegotiationException: Authentication failed on the remote side (the stream might still be available for additional authentication attempts)." on the server.

I changed my Client code to set the upn using the following:
```
var epId = new UpnEndpointIdentity("someuseraccount@my.domain");
var address = new EndpointAddress(new Uri("net.tcp:sdfgsadfasdfds"), epId);
```

But once I do that I get the below Client exception and the server no longer throws the SecurityNegotiationException but just "System.ServiceModel.CommunicationException: The socket connection was aborted."

```
Unhandled exception. System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. -2146892990
   at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)
   at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, Byte[] incomingBlob, ChannelBinding channelBinding, Byte[]& resultBlob, ContextFlagsPal& contextFlags)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.Security.NegotiateStream.GetOutgoingBlob(Byte[] incomingBlob, Exception& e)
   at System.Net.Security.NegotiateStream.SendBlobAsync[TAdapter](TAdapter adapter, Byte[] message)
   at System.Net.Security.NegotiateStream.ReceiveBlobAsync[TAdapter](TAdapter adapter)
   at System.Net.Security.NegotiateStream.SendBlobAsync[TAdapter](TAdapter adapter, Byte[] message)
   at System.Net.Security.NegotiateStream.AuthenticateAsync[TAdapter](TAdapter adapter, String callerName)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream, OutWrapper`1 remoteSecurity)
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgradeAsync(Stream stream)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgradeAsync(StreamUpgradeInitiator upgradeInitiator, OutWrapper`1 connectionWrapper, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreambleAsync(IConnection connection, ArraySegment`1 preamble, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnectionAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.Runtime.TaskHelpers.CallActionAsync[TArg](Action`1 action, TArg argument)
   at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.GetUserByName(String , String )
```
@mconnew Any Ideas?

**Comment by martinmueller4voice** [comment]
@chekm8 I assume "net.tcp:sdfgsadfasdfds" is not the real Uri and you have a correct and meaningful Uri in place in your actual code?
Is the user account you're using for the UpnEndpointIdentity the same your service is running under?
I've tried a user identity in my configuration and got it to work if I specified the correct user.
Do you get a meaningful error if you deliberately use a different (but existing) user for the UpnEndpointIdentity?

**Comment by mconnew** [comment]
@chekm8, I don't know if you resolved the issue, but error -2146892990 is 0x80090342 in hex which corresponds to the error SEC_E_KDC_UNKNOWN_ETYPE which has a description of "The encryption type requested is not supported by the KDC.". My best guess is the server is running on a really old version of Windows which only supports encryption protocols which are no longer supported. I saw this happen with TLS and HTTP before where the cipher suites on an old version of Windows Server didn't overlap with newer Windows OS versions when using TLS 1.2.  
What OS versions are you using on the client and the server? If you're still having this problem, I would suggest opening an issue in dotnet/runtime about NegotiateStream throwing this exception.

**Comment by chekm8** [comment]
> @chekm8 I assume "net.tcp:sdfgsadfasdfds" is not the real Uri and you have a correct and meaningful Uri in place in your actual code? Is the user account you're using for the UpnEndpointIdentity the same your service is running under? I've tried a user identity in my configuration and got it to work if I specified the correct user. Do you get a meaningful error if you deliberately use a different (but existing) user for the UpnEndpointIdentity?

The net.tcp is meaningful, I removed it for the post here.  I tried both the username the service is running as as well as an alternate user name.

**Comment by chekm8** [comment]
> @chekm8, I don't know if you resolved the issue, but error -2146892990 is 0x80090342 in hex which corresponds to the error SEC_E_KDC_UNKNOWN_ETYPE which has a description of "The encryption type requested is not supported by the KDC.". My best guess is the server is running on a really old version of Windows which only supports encryption protocols which are no longer supported. I saw this happen with TLS and HTTP before where the cipher suites on an old version of Windows Server didn't overlap with newer Windows OS versions when using TLS 1.2. What OS versions are you using on the client and the server? If you're still having this problem, I would suggest opening an issue in dotnet/runtime about NegotiateStream throwing this exception.

I am still having the issue and had to revert to using network service to run the windows service account.  All out servers are running WIndows 2019 and many of the old cipher suites have been removed as we are required to use TLS 1.2.   Is there a specific cipher suite that must exist?  I can verify that we still have that in our list.

**Comment by mconnew** [comment]
@chekm8, I'm not familiar enough with the implementation of NegotiateStream to know what ciphers it needs. Without engaging the owners of NegotiateStream (in the dotnet/runtime repo), my best suggestion is to use a binary search method to track it down. I.e. add half of the removed ciphers back and see if that fixes it, if not, add the other half back instead. Then drill down on the half that you identified contains the required cipher and repeat with half of those.

**Comment by mconnew** [comment]
@chekm8, I think this might be a useful blog post: https://learn.microsoft.com/en-us/archive/blogs/openspecification/windows-configurations-for-kerberos-supported-encryption-type
