### ISSUE TITLE
Create scenario tests for all supported MessageVersion's

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#2864]
Not all supported `MessageVersion`'s have a public static property on the `MessageVersion` class but the `MessageVersion` can still be used with the `MessageVersion.CreateVersion(EnvelopeVersion envelopeVersion, AddressingVersion addressingVersion)` static method. We already have some tests for some of the supported message versions, but we have some missing. Priority should be to write tests for Soap12 and Soap11WSAddressing10 as we have an open issue (#2711) for these not working.  

We need tests for HTTP and NetTcp as some of the message versions have special handling with HTTP (action gets placed in headers for example). The actual test workload only needs to be calling `Echo()` as it's the SOAP envelope and transport framing we're testing and not the body.  

Here is a list of the supported message versions and how they are created on Core and the full framework. The server side should use the full framework method although the Core version would also work:

Message Version | WCF Core | Full Framework
---|---|---
none|MessageVersion.None|MessageVersion.None
Soap11|MessageVersion.Soap11|MessageVersion.Soap11
Soap12|MessageVersion.CreateVersion(EnvelopeVersion.Soap12, AddressingVersion.None)|MessageVersion.Soap12
Soap11Addressing10|MessageVersion.CreateVersion(EnvelopeVersion.Soap11, AddressingVersion.WSAddressing10)|MessageVersion.Soap11WSAddressing10
Soap12Addressing10|MessageVersion.Soap12WSAddressing10|MessageVersion.Soap12WSAddressing10
Soap11Addressing200408|MessageVersion.Soap11WSAddressingAugust2004|MessageVersion.Soap11WSAddressingAugust2004
Soap12Addressing200408|MessageVersion.Soap12WSAddressingAugust2004|MessageVersion.Soap12WSAddressingAugust2004

**Comment by StephenBonikowsky** [comment]
Tests for Soap12 and Soap11Addressing10 are ready in PR #3132 

The Soap11Addressing10 tests are passing.
The Soap12 tests are both failing (http/tcp) with different errors.

Test: SameBinding_Soap12_EchoString_Http
This error reproduces the customer reported issue.
On the service I tried both ways of setting the version with no difference in the results.
   MessageVersion.Soap12 and MessageVersion.CreateVersion(EnvelopeVersion.Soap12, AddressingVersion.None)

```
System.ServiceModel.ActionNotSupportedException : The message with Action '' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).

   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1069
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 967
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 799
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 369
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.Echo(String )
   at MessageVersionTests.SameBinding_Soap12_EchoString_Http() in D:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Encoding\MessageVersion\MessageVersionTests.cs:line 108
```

Test: SameBinding_Soap12_EchoString_Tcp
This is the tcp variation of the same test.

```
System.InvalidOperationException : Addressing Version 'AddressingNone (http://schemas.microsoft.com/ws/2005/05/addressing/none)' does not support adding WS-Addressing headers.

   at System.ServiceModel.Channels.MessageHeaders.ValidateHeaderKind(HeaderKind headerKind) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageHeaders.cs:line 956
   at System.ServiceModel.Channels.MessageHeaders.InsertHeader(Int32 headerIndex, Header header) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageHeaders.cs:line 1233
   at System.ServiceModel.Channels.MessageHeaders.Insert(Int32 headerIndex, MessageHeader header, HeaderKind kind) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageHeaders.cs:line 1227
   at System.ServiceModel.Channels.RequestReplyCorrelator.PrepareRequest(Message request) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestReplyCorrelator.cs:line 139
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\DuplexChannelBinder.cs:line 450
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 782
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 369
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) in D:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.Echo(String )
   at MessageVersionTests.SameBinding_Soap12_EchoString_Tcp() in D:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Encoding\MessageVersion\MessageVersionTests.cs:line 144
```

**Comment by StephenBonikowsky** [comment]
I have updated PR #3132 to skip the two failing tests so that the PR can be merged while the failures are investigated.

Assigning to @mconnew
