### ISSUE TITLE
Cannot import wsdl:port Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.

### ISSUE THREAD

**Issue by flatproject** [dotnet/wcf#2933]
I'm trying to consume this service [https://secure.wasp.uat.uk.experian.com/WASPAuthenticator/tokenService.asmx?WSDL](url)
on a .Net Standard Console App using VS (15.7.3) but I keep getting the below warning when i click Go on the interface.

`Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://www.uk.experian.com/WASP/']/wsdl:binding[@name='TokenServiceHttpPost']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.uk.experian.com/WASP/']/wsdl:service[@name='TokenService']/wsdl:port[@name='TokenServiceHttpPost']
Cannot import wsdl:binding
Detail: The required WSDL extension element 'binding' from namespace 'http://schemas.xmlsoap.org/wsdl/http/' was not handled.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.uk.experian.com/WASP/']/wsdl:binding[@name='TokenServiceHttpPost']
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://www.uk.experian.com/WASP/']/wsdl:binding[@name='TokenServiceHttpGet']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.uk.experian.com/WASP/']/wsdl:service[@name='TokenService']/wsdl:port[@name='TokenServiceHttpGet']
Cannot import wsdl:binding
Detail: The required WSDL extension element 'binding' from namespace 'http://schemas.xmlsoap.org/wsdl/http/' was not handled.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.uk.experian.com/WASP/']/wsdl:binding[@name='TokenServiceHttpGet']
`

Does this mean the service is not compatible with .NET Standard/Core and i have to use the normal .Net?

Thank you

**Comment by mlacouture** [comment]
Hi @flatproject 
No, this error doesn't mean the service is not compatible with .NET Core. The error means there's a problem with the web service metadata authoring.  In many cases the generated client works just fine.

**Comment by pthorsley** [comment]
I am also having a similar problem with a service that I am trying to consume. 

Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://services']/wsdl:binding[@name='MainServiceHttpBinding']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://services']/wsdl:service[@name='MainService']/wsdl:port[@name='MainServiceHttpsEndpoint']
Cannot import wsdl:binding
Detail: The required WSDL extension element 'binding' from namespace 'http://schemas.xmlsoap.org/wsdl/http/' was not handled.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://services']/wsdl:binding[@name='MainServiceHttpBinding']

Any ideas?
Thanks

**Comment by mlacouture** [comment]
Hi @pthorsley!
Does the tool fail to generate the proxy code? if not, do you hit any errors when running the code? can you share the service address to try to reproduce the problem? or share the WSDL files?
thank you!
Miguel Lacouture

**Comment by pthorsley** [comment]
When I run my service proxy code even though it seems to have issues I get this result:

   at Microsoft.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping(XmlReflectionMember[] xmlReflectionMembers, String ns, Boolean hasWrapperElement, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at Microsoft.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping(String elementName, String ns, XmlReflectionMember[] members, Boolean hasWrapperElement, Boolean rpc, Boolean openModel, XmlMappingAccess access)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.XmlSerializerImporter.ImportMembersMapping(XmlName elementName, String ns, XmlReflectionMember[] members, Boolean hasWrapperElement, Boolean rpc, String mappingKey)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.LoadBodyMapping(MessageDescription message, String mappingKey, MessagePartDescriptionCollection& rpcEncodedTypedMessageBodyParts)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.CreateMessageInfo(MessageDescription message, String key)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.EnsureMessageInfos()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.EnsureMessageInfos()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.CreateFormatter()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.System.ServiceModel.Description.IOperationBehavior.ApplyClientBehavior(OperationDescription description, ClientOperation proxy)
   at System.ServiceModel.Description.DispatcherBuilder.BindOperations(ContractDescription contract, ClientRuntime proxy, DispatchRuntime dispatch)
   at System.ServiceModel.Description.DispatcherBuilder.BuildProxyBehavior(ServiceEndpoint serviceEndpoint, BindingParameterCollection& parameters)
   at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory(ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose)
   at System.ServiceModel.ChannelFactory.OnOpening()
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ClientBase`1.get_Channel()
   at MainServicePortTypeClient.MainServicePortType.loginAsync(loginRequest request) in Service\InnotasService.cs:line 8924
   at MainServicePortTypeClient.loginAsync(String username, String password, Boolean sendAlerts) in Service\InnotasService.cs:line 8933
   at DataAccess.<>c__DisplayClass12_1.<<Login>b__0>d.MoveNext() in \DataAccess.cs:line 140

**Comment by pthorsley** [comment]
It will create the proxy code, but when I try to run it, it fails with the error above. 
Can I send you personally the address?

**Comment by pthorsley** [comment]
@mlacouture if you have a private email, will send WSDL

**Comment by mlacouture** [comment]
You can send the wsdl to me at this address: mlacouture2017@outlook.com - thanks,

**Comment by pthorsley** [comment]
@mlacouture  sent it over, thanks for taking a look.

**Comment by flatproject** [comment]
Hi @mlacouture ,

Sorry for the delayed reply but I had only just started the project so I couldn't say if it worked or not.

I can now confirm that the client code works fine.

**Comment by mlacouture** [comment]
@flatproject  thank you for confirming your client works just fine.

**Comment by mlacouture** [comment]
@pthorsley, thank you for providing the WSDL doc, I took a look and found that it contains binding definitions that are not compliant with the [W3C standard for Bindings](https://www.w3.org/Submission/wsdl11soap12/) but it should not be a problem as these definitions won't affect the code generation phase.  What is the message for the exception that you get? judging by the callstack you provided I suspect you are hitting an authentication issue.

**Comment by mlacouture** [comment]
Hi @pthorsley! let us know if you still need help with this issue. thanks,

**Comment by OzBob** [comment]
I have the same problem but using the VS 2019 Preview WCF ... Provider wizard, which generates code with the same errors above, and these Build Errors:

The type or namespace name 'ServiceContractAttributeAttribute' does not exist in the namespace 'System.ServiceModel' (are you missing an assembly reference?)	

Do I need to add a dependency on Microsoft.Windows.Compatibility?

Would you like the publicly available WSDL definition that I used?

**Comment by simonprice33** [comment]
> I have the same problem but using the VS 2019 Preview WCF ... Provider wizard, which generates code with the same errors above, and these Build Errors:
> 
> The type or namespace name 'ServiceContractAttributeAttribute' does not exist in the namespace 'System.ServiceModel' (are you missing an assembly reference?)
> 
> Do I need to add a dependency on Microsoft.Windows.Compatibility?
> 
> Would you like the publicly available WSDL definition that I used?

Did you get a fix for this?
