### ISSUE TITLE
System.ServiceModel.Http Exceptions when using version 4.5.0 or higher

### ISSUE THREAD

**Issue by karelz** [dotnet/wcf#2960]
_From @smartcodinghub on June 19, 2018 16:42_

Hi all,

I was using the version 4.5.0-preview1-26228-01 of the System.ServiceModel.Http Nuget. After upgrading to 4.5.0 or 4.5.1 I'm getting some exceptions. I paste the message below. From th preview or .Net Framework I can use correctly the WebService.

Thanks in advance,
Óscar

### Exception
```
System.ServiceModel.CommunicationException
  HResult=0x80131500
  Mensaje = An error occurred while sending the request.
  Origen = System.Private.ServiceModel
  Seguimiento de la pila:
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.GetProfiles(GetProfilesRequest )
   at VigilanciaInteligente.Infraestructure.Cameras.OnvifMedia.MediaClient.VigilanciaInteligente.Infraestructure.Cameras.OnvifMedia.OnvifMedia.GetProfiles(GetProfilesRequest request) in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Infraestructure.Cameras\OnvifMedia.cs:line 17998
   at VigilanciaInteligente.Infraestructure.Cameras.OnvifMedia.MediaClient.GetProfiles() in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Infraestructure.Cameras\OnvifMedia.cs:line 18004
   at VigilanciaInteligente.Infraestructure.Cameras.OnvifController..ctor(CameraSettings settings) in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Infraestructure.Cameras\OnvifController.cs:line 91
   at VigilanciaInteligente.Playground.Program.<Run>d__1.MoveNext() in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Playground\Program.cs:line 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VigilanciaInteligente.Playground.Program.<Main>d__0.MoveNext() in D:\GIT\VigilanciaInteligente\VigilanciaInteligente.Playground\Program.cs:line 11
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VigilanciaInteligente.Playground.Program.<Main>()

Excepción interna 1:
HttpRequestException: An error occurred while sending the request.

Excepción interna 2:
IOException: The server returned an invalid or unrecognized response.

```

_Copied from original issue: dotnet/corefx#30517_

**Comment by karelz** [comment]
_From @davidsh on June 19, 2018 16:44_

System.ServiceModel.Http.* is part of the WCF APIs.  They are in the https://github.com/dotnet/wcf repo.  So, this bug should be moved there.

**Comment by Lxiamail** [comment]
@smartcodinghub Can you share repro to help us investigate the issue?

**Comment by smartcodinghub** [comment]
@Lxiamail 

Hi, sorry I can't share with you the WCF since I only consume it. All I know is that the preview works fine but the final release no (same code). Is there any log I can upload to help you?

**Comment by Lxiamail** [comment]
@smartcodinghub Can you share the WSDL file that your WCF client consumes to repro the problem?

**Comment by smartcodinghub** [comment]
Yes, its from some IP cameras using ONVIF.

https://www.onvif.org/ver10/media/wsdl/media.wsdl
https://www.onvif.org/ver20/ptz/wsdl/ptz.wsdl

As I said, from .Net framework or the net core 4.5.0-preview1-26228-01 it works, but from 4.5.0 or 4.5.1 it doesn't. In 4.5.1 the exception changed a bit to:

The server returned an invalid or unrecognized response.

**Comment by Lxiamail** [comment]
@smartcodinghub The WSDL files are large and it's hard to identify the problem. Can you share the simplified client code which repros the problem?

**Comment by smartcodinghub** [comment]
I have the same problem with all the methods. The example code:

```
/* Media Service */
var messageElement = new TextMessageEncodingBindingElement() { MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap12, AddressingVersion.None) };
HttpTransportBindingElement httpBinding = new HttpTransportBindingElement() { AuthenticationScheme = AuthenticationSchemes.Digest };
client = new MediaClient(new CustomBinding(messageElement, httpBinding), new EndpointAddress(settings.MediaAddress));

Profile[] profiles = client.GetProfiles();
```

**Comment by mconnew** [comment]
@smartcodinghub, can you verify whether this works when using the full .Net Framework? We had another developer who was using ONVIF with a UWP app who was having problems with an earlier version of WCF as we were sending a pre-emptive HEAD request to compensate for the lack of support for the Expect header. As he was doing his own authentication, he could set the AuthenticationScheme to None which turned off the pre-emptive HEAD request which solved his problem. He mentioned that some camera manufacturers have problems with the Expect header (he was concerned that when we add that it would break but we only add it when authentication is used). I see you are setting the authentication scheme to Digest, but you don't look to be providing any credentials. If you aren't providing credentials, can you try setting the authentication scheme to None as that will disable the Expect header.

**Comment by smartcodinghub** [comment]
@mconnew I was setting the wcf behavior and the user and password later, after the client creation. That's why you didn't see it. But, some of the cameras didn't have any Authentication and that was the problem.

As you said, in the previews it worked and I need to change to **AuthenticationScheme.None**. But using it I have the following error

`System.ArgumentException: The value specified for the AuthenticationScheme property on the HttpTransportBindingElement ('None') is not allowed when building a ChannelFactory. If you used a standard binding, ensure the ClientCredentialType is not set to HttpClientCredentialType.InheritedFromHost, a value which is invalid on a client. If you set the value to 'None' directly on the HttpTransportBindingElement, please set it to Digest, Negotiate, NTLM, Basic, or Anonymous.`

But I switched to **Anonymous** and now it's working.

I post some of the code for anyone that could need it in the future:

``` cs
PasswordDigestBehavior behavior = null;
AuthenticationSchemes authScheme = AuthenticationSchemes.None;

if (HasAuthentication())
{
    authScheme = AuthenticationSchemes.Digest;
    behavior = new PasswordDigestBehavior(settings.UserName, settings.Password);
}

/* Media Service */
var messageElement = new TextMessageEncodingBindingElement() { MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap12, AddressingVersion.None) };
HttpTransportBindingElement httpBinding = new HttpTransportBindingElement() { AuthenticationScheme = authScheme };
client = new MediaClient(new CustomBinding(messageElement, httpBinding), new EndpointAddress(settings.MediaAddress));

if (behavior != null)
{
    client.Endpoint.EndpointBehaviors.Add(behavior);
}
```

Thanks for all the help on this issue, that was an easy fix but hard to find one!

**Comment by mconnew** [comment]
Closing this issue as it looks like you have a solution.
