### ISSUE TITLE
Upgrading System.ServiceModel.Http to 4.5.0 from 4.4.2 breaks app

### ISSUE THREAD

**Issue by andre-ss6** [dotnet/wcf#2992]
I have a ASP.NET 2.0 Core web api that uses a WCF generated client (using Connected Services). My project settings are:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.4.2" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.2" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.2" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

</Project>
```

If I change `<PackageReference Include="System.ServiceModel.Http" Version="4.4.2" />` to `<PackageReference Include="System.ServiceModel.Http" Version="4.5.0" />`, the application stops working (I've tried multiple combinations of different versions, and found `System.ServiceModel.Http` to be the culprit). When I make a request to the web service, I get this exception:

> An unhandled exception was thrown by the application.
> System.ServiceModel.Security.SecurityNegotiationException: Could not establish trust relationship for the SSL/TLS secure channel with authority 'wssecprefeituras.jucemg.mg.gov.br'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
>    at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Santa_Luzia.Integracao.Jucemg.WebApi.JuntaComercialProducaoApiClient.<RecuperarViabilidadeEnderecoPendente>d__3.MoveNext() in C:\Users\andre\source\repos\santaluiza-web\Santa_Luzia.Services.ApiClient.JUCEMG\JuntaComercialProducaoApiClient.cs:line 68
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Santa_Luzia.Integracao.Jucemg.WebApi.Controllers.JucemgController.<ViabilidadesPendentes>d__2.MoveNext() in C:\Users\andre\source\repos\santaluiza-web\Santa_Luzia.Services.ApiClient.JUCEMG\Controllers\JucemgController.cs:line 20
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

Unfortunately I don't have time _right now_ to create a reproducible sample, however the application is really simple: it's just a simple wrapper around a WCF service. This is the client configuration:

```csharp
BasicHttpBinding basicHttpBinding = new BasicHttpBinding();
basicHttpBinding.Security.Mode = BasicHttpSecurityMode.Transport;
basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

EndpointAddress endpointAddress = new EndpointAddress("https://wssecprefeituras.jucemg.mg.gov.br/empreendimento/service/ViabilidadePrefeituraWS");

_ws = new ViabilidadePrefeituraWSClient(basicHttpBinding, endpointAddress);

_ws.ClientCredentials.ClientCertificate.SetCertificate(
	StoreLocation.LocalMachine,
	StoreName.My,
	X509FindType.FindBySubjectName,
	"www.santaluzia.mg.gov.br");

_ws.ClientCredentials.ServiceCertificate.SslCertificateAuthentication =
	new X509ServiceCertificateAuthentication()
	{
		CertificateValidationMode = X509CertificateValidationMode.PeerTrust,
		RevocationMode = X509RevocationMode.NoCheck
	};

ServicePointManager.SecurityProtocol =
	SecurityProtocolType.Tls12 |
	SecurityProtocolType.Tls11 |
	SecurityProtocolType.Tls;

ServicePointManager.ServerCertificateValidationCallback +=
	(se, cert, chain, sslerror) =>
	{
		return true;
	};
```

**Comment by StephenBonikowsky** [comment]
@KKhurin have you had a chance to take a look at this yet?

**Comment by KKhurin** [comment]
Not yet. Planning to do it next week.

**Comment by KKhurin** [comment]
Thank you @andre-ss6 for reporting this and sorry about the delay.

What OS version is this?

**Comment by andre-ss6** [comment]
It's okay. And, as mentioned in the OP, it's Windows server 2016

**Comment by KKhurin** [comment]
@andre-ss6, there are so many things that can happen and result in this error.

For starters lets try again version=4.5.0 of `System.ServiceModel.*`  and set
`AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false)`. 
You might as well want to change the target framework to `netcoreapp2.1`

If this does not change anything then I'd like to start with tracking down the exact IIS response status code (the easiest way is to look in IIS logs). The substatus and the assocuated error might be especially helpful:
  <...>  MyService.svc - 443 <...> __403__ __13__ __2148081683__ 1447 400 6610 800d ae06

And since you're using 2016 Server you might as well enable additional logging as [outlined here](https://cloudblogs.microsoft.com/microsoftsecure/2017/09/07/new-iis-functionality-to-help-identify-weak-tls-usage/) to rule out oudated ciphers.

**Comment by kentkost** [comment]
I would like to have this issue reopened reopen. I have a similar issue when I upgrade System.ServiceModel.Http from 4.4.4 to 4.5.0. 

It's a service that implements a third party SOAP API.

The client implementation:
```csharp
public partial class ServiceProviderWebPortClient
{
    public string UserId { get; }
    public string ProviderId { get; }
    public ServiceProviderWebPortClient(TimeSpan timeout, IHttpMessageHandlerFactory factory, string certSerial, string userId, string providerId) :
        base(ServiceProviderWebPortClient.GetBindingForEndpoint(timeout), ServiceProviderWebPortClient.GetDefaultEndpointAddress())
    {
        UserId = userId;
        ProviderId = providerId;
        this.Endpoint.EndpointBehaviors.Add(new HttpMessageHandlerBehavior(factory, "ThirdPartyService"));
        this.Endpoint.Name = EndpointConfiguration.ServiceProviderWebPort.ToString();
        this.ChannelFactory.Credentials.ClientCertificate.SetCertificate(StoreLocation.LocalMachine, StoreName.My, X509FindType.FindBySerialNumber, certSerial);
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(TimeSpan timeout)
    {
        var binding = new BasicHttpBinding();
        binding.Security.Mode = BasicHttpSecurityMode.Transport;
        binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

        binding.MaxBufferSize = int.MaxValue;
        binding.MaxReceivedMessageSize = int.MaxValue;
        binding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
        binding.AllowCookies = true;

        binding.ReceiveTimeout = timeout;
        binding.SendTimeout = timeout;
        binding.OpenTimeout = timeout;
        binding.CloseTimeout = timeout;

        return binding;
    }
}

public class HttpMessageHandlerBehavior : IEndpointBehavior
{
    private readonly Func<HttpMessageHandler> _httpMessageHandler;

    public HttpMessageHandlerBehavior(IHttpMessageHandlerFactory factory, string serviceName)
    {
        _httpMessageHandler = () => factory.CreateHandler(serviceName);
    }

    public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
    {
        bindingParameters.Add(new Func<HttpClientHandler, HttpMessageHandler>(handler => _httpMessageHandler()));
    }
    .
    .
    .
}
```

The exception I get when I now call any endpoint is the following:
```
Exception thrown: 'System.ServiceModel.FaultException' in System.Private.CoreLib.dll
```

![billede](https://user-images.githubusercontent.com/14237820/173814293-7714f593-6adf-403b-926c-bd74dd9518b0.png)

I am pretty sure that the failure happens because the nuget upgrade makes it impossible to decode certain SOAP messages because of how it interprets the SOAP envelope. 

The stacktrace I currently have reveals nothing new that @andre-ss6 hasn't already disclosed.
