### ISSUE TITLE
XAMARIN FORM consuming WCF error

### ISSUE THREAD

**Issue by Robertbe** [dotnet/wcf#3031]
Dear support,

I am register an DOT net WCF service, and trying to consume it through Xamarin CPL.  I got this error when start calling the service.  I have upgrade the System.ServiceModel.Primitives to 4.5.2 but still not help.

==================================

{System.IO.FileLoadException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.ServiceModel.Primitives, Version=4.5.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ADATimeSheet.ViewModels.TimesheetDetailViewModel.<>c.<<-ctor>b__9_2>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at ADATimeSheet.ViewModels.TimesheetDetailViewModel.<>c.<.ctor>b__9_2(TimesheetDetailPage obj, Timesheet tsheet)

}

**Comment by StephenBonikowsky** [comment]
@Robertbe WCF in Xamarin is a separate code base than what we support in this repo, but could you clarify your scenario a bit? Did your scenario work at all? If so, what version of System.ServiceModel.Primitives were you using when it worked?

**Comment by jupagose** [comment]
I have a similar issue trying to consume WCF The endpoint works great at WPF but on XAMARIN throws 

System.ServiceModel.EndpointNotFoundException: System error. ---> System.Net.WebException: Error: NameResolutionFailure at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <5a97d41d36694fb19855c17429527b10>:0 at System.ServiceModel.Channels.HttpRequestChannel+<>c__DisplayClass7_1.<BeginProcessRequest>b__0 (System.IAsyncResult r) [0x0001d] in <77b5ae473c554009a885ada52b2392f8>:0 --- End of inner exception stack trace --- at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr) at (wrapper remoting-invoke) ZamilahPublicApi.IZamilahPublicApi.GetIdentificationTypesAsync()

**Comment by jupagose** [comment]
I have a similar problem but in my case Async methods generated by Microsoft WCF Web service reference provider can't be consumed from XAMARIN 

If I made a call like this 

`string response = await client.GetIdentificationTypesAsync();`

I get this:

Error in deserializing body of request message for operation 'GetIdentificationTypes'. OperationFormatter encountered an invalid Message body. Expected to find node type 'Element' with name 'GetIdentificationTypes' and namespace 'http://tempuri.org/'. Found node type 'Element' with name 'GetIdentificationTypesAsync' and namespace 'http://tempuri.org/'


If I fix REFERENCES manually I can consume sync Methods but not Async ones.

**Comment by StephenBonikowsky** [comment]
@jupagose your issue is not the same as what @Robertbe is reporting. Your issue is because Xamarin actually has its own implementation of WCF taken from WCF full framework a number of years ago so while WCF in the full framework and WCF Core here in this repo has continued to evolve the code in Xamarin has not. What you are reporting is one of the affected areas.

This issue #2463 contains more info on this.

**Comment by yujayee** [comment]
Hi @Robertbe, could you provide us more details of this issue so we can understand your scenario better? Did your project work well before but the issue suddenly happen because of a recent upgrade of package? Could you try to upgrade the packages to 4.5.3 to see if it works?

**Comment by jupagose** [comment]
Actual xamarin versions doesn't work with latests version of wcf clients.

**Comment by Robertbe** [comment]
> Hi @Robertbe, could you provide us more details of this issue so we can understand your scenario better? Did your project work well before but the issue suddenly happen because of a recent upgrade of package? Could you try to upgrade the packages to 4.5.3 to see if it works?

Hi Lxiamail,  Thanks for replying to my issue.  I have upgrade to 4.5.3 and still not working.  I ends up abandoning WCF and rewrite the project to use Web API back-end instead.

Regards,

Robert

**Comment by Lxiamail** [comment]
@Robertbe I'm sorry to hear that. We have been working with UWP team to investigate the issue, but there is no conclusion yet.

**Comment by Robertbe** [comment]
Thanks for checking into the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lxiamail** [comment]
Created a UWP bug#727016 to track this issue

**Comment by KonstantinosP7** [comment]
I have the same issues with WCF. I have created succesfully the WCF service, tested it on browser, tested it on UWP , everything works, but when I set as start up project the android.app, it throws system error when trying to communicate with the service. (in away client command).
Any simple Web API example to communicate with xamarin android app? Thank you in advance, I am in really urgent situation.

**Comment by Lxiamail** [comment]
Looks like there are a few different problems reported in this issue.
1. We couldn’t repro the “assembly System.ServiceModel.Primitives load  error”, it is the original problem reported by Robertbe
2. The problem reported by @jupagose is the XAMARIN issue [#2463](https://github.com/dotnet/wcf/issues/2463) . 
3. @KonstantinosP7 Sorry for the delay response. Is your issue similar as the async method name mis-match as  @jupagose reported.

**Comment by pavloss** [comment]
I'm experiencing the same issue as the OP.
I have a PCL that has consumed a WCF service.
In the xamarin forms UWP project I have referenced this class library version 6.2.10.
On debugging or running this project i get the following:

`System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'`
