### ISSUE TITLE
My WCF project error in Ubuntu 17.1

### ISSUE THREAD

**Issue by shakeri** [dotnet/wcf#3093]
I create simple console app in .NET Core 2.1 and add WCF address with `svcutil ` command.
When I run the project, I encounter an error.
```
  An assembly specified in the application dependencies manifest (svc.deps.json) was not found:
    package: 'System.Net.Http.WinHttpHandler', version: '4.4.0'
    path: 'lib/netstandard2.0/System.Net.Http.WinHttpHandler.dll'
```
But in `Windows 10` it run without problems.

**Comment by mlacouture** [comment]
Hi @shakeri, thank you for reporting this issue.  @zhenlan, is this known? thanks,

**Comment by Lxiamail** [comment]
@shakeri Looks like you are referencing the old version of WCF package. Please update the WCF package reference to 4.5.*, and let us know if that resolves your problem.

**Comment by shakeri** [comment]
> Please update the WCF package reference to 4.5.*

@Lxiamail  I update to 4.5*, but this time i get this error:

```
An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.
```

**Comment by Lxiamail** [comment]
@shakeri Can you share the full exception call stack?

**Comment by Lxiamail** [comment]
@shakeri The other thing that you can try is to verify the service without WCF Core involved, does it work?

**Comment by shakeri** [comment]
> Can you share the full exception call stack?

```
Exception has occurred: CLR/System.AggregateException
An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__5.MoveNext()
```

> The other thing that you can try is to verify the service without WCF Core involved, does it work?

@Lxiamail I tested this project in Windows Server 2012 R2 and work without problems.

**Comment by Lxiamail** [comment]
@shaker "the project in Windows Server 2012 R2 and work without problems.", do you mean that you run the client program on full .NET Framework and the issue didn't repro? Can you try to access the service using httpclient on .NET Core without using WCF Core?

**Comment by Lxiamail** [comment]
@shakeri Hope you have worked on the issue. Closing the issue due to inactive for a while.
