### ISSUE TITLE
UAP - PNSE : 'System.Net.CredentialCache' is not supported for property 'Credentials'.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#3110]
After re-enabling UAP tests in Master, we are getting...

System.PlatformNotSupportedException : The value 'System.Net.CredentialCache' is not supported for property 'Credentials'.

```
   at System.Net.Http.HttpClientHandler.set_Credentials(ICredentials value) in E:\A\_work\2\s\corefx\src\System.Net.Http\src\uap\System\Net\HttpClientHandler.cs:line 203
   at System.ServiceModel.Channels.HttpChannelFactory`1.GetHttpClientAsync(EndpointAddress to, Uri via, SecurityTokenProviderContainer tokenProvider, SecurityTokenProviderContainer proxyTokenProvider, SecurityTokenContainer clientCertificateToken, CancellationToken cancellationToken)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.GetHttpClientAsync(EndpointAddress to, Uri via, SecurityTokenContainer clientCertificateToken, TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpsChannelFactory`1.HttpsClientRequestChannel.GetHttpClientAsync(EndpointAddress to, Uri via, TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args) in E:\A\_work\2\s\corefx\src\System.Reflection.DispatchProxy\src\System\Reflection\DispatchProxyGenerator.cs:line 162
   at generatedProxy_3.Echo(String )
   at Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo()
```

Test cases affected...
   Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException
   Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo
   Http_ClientCredentialTypeTests.HttpExpect100Continue_DigestAuthentication_True
   Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain

**Comment by StephenBonikowsky** [comment]
This has been fixed by #2668 
Need to re-enable the test to verify.

**Comment by StephenBonikowsky** [comment]
Additional details...

> Http_ClientCredentialTypeTests.HttpExpect100Continue_DigestAuthentication_True

- This test should not even be running in UWP, Expect100Continue is not supported in UWP. Will add skipping logic to the test.

> Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain

- This test was failing because of unexpected side effects from the Expect100Continue failure. This should now work fine as soon as Expect100Continue gets skipped.

> Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException
> Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo

- These two tests were fixed by #3120 and pass when run locally, investigating why they are failing on nightly runs.

**Comment by StephenBonikowsky** [comment]
Just need to spend some time investigating the difference between running this locally versus on VSTS.

**Comment by mconnew** [comment]
Maybe we can fix this by changing it to a runtime check instead of if-def'ing it. We have no difference in what classes are available to us so there's no reason this couldn't be a runtime check.

**Comment by StephenBonikowsky** [comment]
That's an option but it may have uncovered a test infra issue where the uap test run is using the wrong s.p.sm assembly, which would be a bad thing.

**Comment by StephenBonikowsky** [comment]
Confirmed that the tests are now running and passing nightly on the uap runs.
