### ISSUE TITLE
Hi @mlacouture 

### ISSUE THREAD

**Issue by guoming** [dotnet/wcf#3219]
[dotnet-svcutil v1.0.3](https://www.nuget.org/packages/dotnet-svcutil/1.0.3) is now available and it contains a fix for this issue.
thanks

_Originally posted by @mlacouture in https://github.com/dotnet/wcf/issues/3081#issuecomment-417086094_

I have the same problem.

   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, String action, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeBodyContents(Message message, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(Message message, Object[] parameters)
   at System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)

**Comment by dasetser** [comment]
@guoming Can you provide a little more detail about this? Are you saying you still get this exception with dotnet-svcutil v1.0.3? If so can you provide the WSDL or service you're seeing the problem with?

**Comment by dasetser** [comment]
Closing since this doesn't have enough information about the problem or scenario to investigate.
