### ISSUE TITLE
System.ServiceModel.CommunicationException: Error in deserializing body of reply  message for operatio

### ISSUE THREAD

**Issue by guoming** [dotnet/wcf#3221]
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Error in deserializing body of reply message for operation 'fetchTracking'.) --->
System.ServiceModel.CommunicationException: Error in deserializing body of reply message for operation 'fetchTracking'. ---> System.InvalidOperationException: There is an error in XML document (1, 1973). ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.<>c__DisplayClass1_2`2.<GetSetMemberValueDelegateWithType>b__2(Object o, Object p)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.<>c__DisplayClass49_2.<WriteEncodedStructMethod>b__2(Object value)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, Fixup fixup, Member member)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup, CheckTypeSource checkTypeSource)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup, List`1 checkTypeHrefsSource)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(StructMapping structMapping)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.<>c__DisplayClass33_0.<CreateXmlSerializationReadCallback>b__0()
   at System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(String name, String ns, Boolean elementCanBeType, String& fixupReference)
   at System.Xml.Serialization.XmlSerializationReader.ReadReferencedElements()
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(XmlMembersMapping xmlMembersMapping)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateMembersElement(XmlMembersMapping xmlMembersMapping)
   at System.Xml.Serialization.ReflectionXmlSerializationReader.ReadObject()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parameters, Boolean isRequest)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, String action, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeBodyContents(Message message, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(Message message, Object[] parameters)
   at System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
```

**Comment by Lxiamail** [comment]
@guoming Can you share the concrete steps to repro the problem and share the XML payload which caused the problem?

**Comment by j1mb0jay** [comment]
I too am suffering this issue.

**Error in deserializing body of reply message for operation 'fetchTracking'.**

`   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, String action, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeBodyContents(Message message, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(Message message, Object[] parameters)
   at System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at Parcel2Go.Tracking.Api.Features.Tracking.Couriers.Hermes.HermesParcelTracker.BuildTrackingDetailsFromApi(HermesSettings settings, String trackingReference)`

https://www.hermes-europe.co.uk/parceltrackingservice/services/parcelTrackingService?wsdl

**Comment by Lxiamail** [comment]
@j1mb0jay browse to https://www.hermes-europe.co.uk/parceltrackingservice/services/parcelTrackingService?wsdl get hermsworld.com gets moved rediction error message. Can you share the updated swdl endpoint adddress?

**Comment by Lxiamail** [comment]
@guoming and @j1mb0jay , Hope you worked out the issue. Closing the issue due to being inactive for a while.

**Comment by markmario** [comment]
@Lxiamail i have a repro. This issue seems to be occuring in .net 3.1 with the latest version of system.servicemodel

**Comment by Lxiamail** [comment]
@markmario I don't work on WCF anymore. I will let the current WCF repo own to triage the issue.

**Comment by florjon** [comment]
@markmario any workarounds to this working in .net 3.1 ?

**Comment by markmario** [comment]
@florjon I have rewritten this using standard http

**Comment by TimBurris** [comment]
@fudgeboy2000 thank you for your post, I too faced the same issue, using .NET 6 to call Oracle's iQuery web service.  the problem turned out to be exactly what you suggested, the util generated an [int] but it needed to be a nullable int.  changing the generated source to be int? solved my error.
