### ISSUE TITLE
MessageTest.GetMessageVersion unit test fails in NET Native due to SR.Format

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#323]
The assert fails to account for the fact it will get the resource string back with the format specifier still inside it.  Consider making a test helper that reverse-engineers SR.Format's behavior in NET Native by detecting format specifiers in the exception message, splitting the comma-separated parameters, and invoking String.Format to reconstitute the formatted message we would see in CoreCLR.
 --------------------------------
  Running Test: MessageTest.GetMessageVersion
  Assert.Equal:Expected: [Soap12 (http://www.w3.org/2003/05/soap-envelope) Addressing10 (http://www.w3.org/2005/08/addressing)]. Actual:[Soap12 ({0}), http://www.w3.org/2003/05/soap-envelope Addressing10 ({0}), http://www.w3.org/2005/08/addressing]. 
  Xunit.AssertTestException: Assert.Equal: Expected: [Soap12 (http://www.w3.org/2003/05/soap-envelope) Addressing10 (http://www.w3.org/2005/08/addressing)]. Actual:[Soap12 ({0}), http://www.w3.org/2003/05/soap-envelope Addressing10 ({0}), http://www.w3.org/2005/08/addressing]. 
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.Equal(String expected, String actual) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 270
     at Xunit.Assert.Equal(__Canon expected, __Canon actual) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 228
     at MessageTest.GetMessageVersion() in e:\oss\wcf\src\System.ServiceModel.Primitives\tests\Channels\MessageTest.cs:line 74
     at EntryPointMain.b__5() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\unit\System.ServiceModel.Primitives\System.ServiceModel.Primitives.Tests.main.cs:line 18
     at Windows.UI.Core.DispatchedHandler.InvokeOpenStaticThunk()
     at System.ServiceModel.InstanceContextEmptyCallback.Invoke($InstanceContext instanceContext)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by roncain** [comment]
BTW, the fact a format specifier is appearing in the exception message is very odd, and it sounds like either the toolchain is messing up an SR.Format or the place in the product code throwing this error is incorrectly using SR.Format.
