### ISSUE TITLE
Consuming .netstandard library with connected service from Web API 2 project results in System.ServiceModel.CommunicationException

### ISSUE THREAD

**Issue by mscrivo** [dotnet/wcf#3257]
I'm in the process of converting a large asp.net webapi 2 project to asp.net mvc core.  One of the sub projects has a web reference that of course doesn't compile when moving the project from net472 to netstandard2.0, so I recreated it as Connected Service. 

But when trying to use that connected service from the existing web api (net472) project, I get the following error:

> System.ServiceModel.CommunicationException: 'There was an error in serializing one of the headers in message loginRequest: 'Unable to generate a temporary class (result=1).
error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
error CS0012: The type 'System.Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
'.  Please see InnerException for more details.'

I've tried all the various workarounds to reference netstandard in our net472 WebAPI project, to no avail.

Is this scenario not supported? 

Full Stack Trace from InnerException:

```
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GetSerializersFromCache(XmlMapping[] mappings, Type type)
   at System.Xml.Serialization.XmlSerializer.FromMappings(XmlMapping[] mappings, Type type)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.SerializerGenerationContext.GenerateSerializers()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.SerializerGenerationContext.GetSerializer(Int32 handle)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.MessageInfo.get_HeaderSerializer()
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.AddHeadersToMessage(Message message, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)```

**Comment by Lxiamail** [comment]
@mscrivo We need some clarification of your scenario in order to help. Sounds like you are in the progress to convert a net472 WebAPI project to .NET Core, which is a client has a web reference generated from a web service. If so, I have a few questions:
1. why can't you directly using the web reference instead of regenerating one? What problem did you run into when you use the existing web reference?
2. If you convert the net472 project to .NET Core, why do you "trying to use that connected service from the existing WebAPI (net472) project" instead of trying to use the connected service from the .NET Core project?

**Comment by mscrivo** [comment]
1. Because when i converted the project with the web reference to target
netstandard 2.0 instead of net472, it no longer compiled. Unfortunately I
don't have the errors at this point.

2. That's essentially what I'm doing now. I'm converting both the project
with the web reference to netstandard2.0 (with connected service instead of
web reference) and the asp.net project to asp.net core. I was hoping to do
these steps one at a time, that's what this issue is about. But could not
find a way to do that.

Anyhow, now that both are converted, it's working fine.

**Comment by Lxiamail** [comment]
@mscrivo I'm glad to hear that the conversion worked out for you. In net472 project to generate serialization assembly targeting netstandard for web service is not supported. This is because generate serialization assembly for ASMX on .NET Framework still goes through the C# compilation code path  instead of reflection emit, which needs to pass the reference assemblies to C# compiler. In this case, there are multiple problems, one of them is netstandard reference assembly is needed. However, at runtime, we only have netstandard façade assembly.
