### ISSUE TITLE
ExpectedExceptionTests.DuplexCallback_Throws_FaultException_DirectThrow fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#326]
--------------------------------
  Running Test: ExpectedExceptionTests.DuplexCallback_Throws_FaultException_DirectThrow
  Assert.True:Expected 'System.ServiceModel.FaultException`1[FaultDetail]' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.ServiceModel.FaultException`1[FaultDetail]' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
     at Xunit.Assert.Throws(Action action) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at ExpectedExceptionTests.DuplexCallback_Throws_FaultException_DirectThrow($<>c__DisplayClass13 CS$<>8__locals14) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 366
     at EntryPointMain.b__9() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ExpectedExceptions\Client.ExpectedExceptions.Tests.main.cs:line 22
     at System.Func$1.InvokeOpenStaticThunk()
     at System.ServiceModel.Channels.ChainedEndHandler.Invoke(IAsyncResult result)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by roncain** [comment]
May be fixed by combination of Khoa's fixes to serialization and pending fixes to toolchain for SG

**Comment by roncain** [comment]
Passes using latest toolchain:

  --------------------------------
  Running Test: ExpectedExceptionTests.DuplexCallback_Throws_FaultException_DirectThrow
  ---- Test PASSED ---------------
