### ISSUE TITLE
Https_ClientCredentialTypeTests.NtlmAuthentication_RoundTrips_Echo fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#327]
--------------------------------
  Running Test: Https_ClientCredentialTypeTests.NtlmAuthentication_RoundTrips_Echo
  Assert.True:Test Case: NtlmAuthentication FAILED with the following errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
  'BasicHttpBinding with NTLM authentication'
  Exception: System.ServiceModel.CommunicationException: net_http_client_execution_error ---> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.ArgumentException: Arg_ArgumentException
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Net.Http.HttpHandlerToFilter.d__3.MoveNext() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpHandlerToFilter.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Net.Http.HttpClientHandler.d__59.MoveNext() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpClientHandler.cs:line 16707566
     Exception_EndOfInnerExceptionStack
     at System.Net.Http.HttpClientHandler.d__59.MoveNext$catch$1() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpClientHandler.cs:line 410
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter$1.GetResult() in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 496
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__11.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 16707566
     Exception_EndOfInnerExceptionStack
     at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException($HttpRequestException requestException, $HttpRequestMessage request, $HttpAbortReason abortReason) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelHelpers.cs:line 49
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__11.MoveNext$catch$1() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 591
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__34.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__33.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Runtime.TaskHelpers.WaitForCompletion($Task$1<__Canon> task) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs:line 16707566
     at System.ServiceModel.Channels.RequestChannel.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 241
     at System.ServiceModel.Dispatcher.RequestChannelBinder.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\RequestChannelBinder.cs:line 105
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 765
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 139
     at __InterfaceProxies.ServiceChannelProxy_IWcfService.global.IWcfService_P.Echo(String message) in c:\Users\roncain\AppData\Local\Temp\Ilc3770855\Security.TransportSecurity.Tests.ITFProxy.g.cs:line 65
     at ScenarioTestHelpers.RunBasicEchoTest($Binding binding, String address, String variation, StringBuilder errorBuilder, Action$1<$ChannelFactory> factorySettings, Object[] CS$0$0001) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Common\Scenarios\ScenarioTestHelpers.cs:line 56
  
  Xunit.AssertTestException: Assert.True: Test Case: NtlmAuthentication FAILED with the following errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
  'BasicHttpBinding with NTLM authentication'
  Exception: System.ServiceModel.CommunicationException: net_http_client_execution_error ---> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.ArgumentException: Arg_ArgumentException
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Net.Http.HttpHandlerToFilter.d__3.MoveNext() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpHandlerToFilter.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Net.Http.HttpClientHandler.d__59.MoveNext() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpClientHandler.cs:line 16707566
     Exception_EndOfInnerExceptionStack
     at System.Net.Http.HttpClientHandler.d__59.MoveNext$catch$1() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpClientHandler.cs:line 410
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter$1.GetResult() in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 496
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__11.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 16707566
     Exception_EndOfInnerExceptionStack
     at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException($HttpRequestException requestException, $HttpRequestMessage request, $HttpAbortReason abortReason) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelHelpers.cs:line 49
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__11.MoveNext$catch$1() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 591
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__34.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__33.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Runtime.TaskHelpers.WaitForCompletion($Task$1<__Canon> task) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs:line 16707566
     at System.ServiceModel.Channels.RequestChannel.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 241
     at System.ServiceModel.Dispatcher.RequestChannelBinder.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\RequestChannelBinder.cs:line 105
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 765
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 139
     at __InterfaceProxies.ServiceChannelProxy_IWcfService.global.IWcfService_P.Echo(String message) in c:\Users\roncain\AppData\Local\Temp\Ilc3770855\Security.TransportSecurity.Tests.ITFProxy.g.cs:line 65
     at ScenarioTestHelpers.RunBasicEchoTest($Binding binding, String address, String variation, StringBuilder errorBuilder, Action$1<$ChannelFactory> factorySettings, Object[] CS$0$0001) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Common\Scenarios\ScenarioTestHelpers.cs:line 56
  
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.True(Boolean condition, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at Https_ClientCredentialTypeTests.NtlmAuthentication_RoundTrips_Echo(StringBuilder errorBuilder) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\ClientCredentialTypeTests.cs:line 156
     at EntryPointMain.b__4() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 17
     at System.Action.InvokeOpenStaticThunk()
     at System.Threading.SendOrPostCallback.Invoke(Object state)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by zhenlan** [comment]
@mconnew please add instructions of how to validate this in NetCoreForCoreCLR scenario.

**Comment by zhenlan** [comment]
For the first step, we would to identify if the issue is in WCF or some other dependencies.

**Comment by mconnew** [comment]
Here's a cleaner partial exception trace. Technically this issue is in HttpClient but there's something we might be able to do about it.

  Assert.True:Test Case: NtlmAuthentication FAILED with the following errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
  'BasicHttpBinding with NTLM authentication'
  Exception: System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.NotSupportedException: This IRandomAccessStream does not support the GetInputStreamAt method because it requires cloning and this stream does not support cloning.
     at System.IO.NetFxToWinRtStreamAdapter.ThrowCloningNotSuported(String methodName)
     at System.IO.NetFxToWinRtStreamAdapter.GetInputStreamAt(UInt64 position)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Net.Http.HttpHandlerToFilter.d__3.MoveNext()

**Comment by mconnew** [comment]
I made a fix to the NetNative HttpClient which fixes this issue.
