### ISSUE TITLE
HttpsTests.CrossBinding_Soap11_EchoString fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#328]
Running Test: HttpsTests.CrossBinding_Soap11_EchoString
  Assert.True:Test case FAILED with errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
  'Client:: CustomBinding/MessageVersion=Soap11
  Server:: BasicHttpsBinding/DefaultValues'
  Exception: System.ServiceModel.ProtocolException: UnexpectedHttpResponseCode, 400, Bad Request
     at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateResponseStatusCode() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 352
     at System.ServiceModel.Channels.HttpResponseMessageHelper.d__7.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 38
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__15.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__34.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__33.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Runtime.TaskHelpers.WaitForCompletion($Task$1<__Canon> task) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs:line 16707566
     at System.ServiceModel.Channels.RequestChannel.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 241
     at System.ServiceModel.Dispatcher.RequestChannelBinder.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\RequestChannelBinder.cs:line 105
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 765
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 139
     at __InterfaceProxies.ServiceChannelProxy_IWcfService.global.IWcfService_P.Echo(String message) in c:\Users\roncain\AppData\Local\Temp\Ilc3770855\Security.TransportSecurity.Tests.ITFProxy.g.cs:line 65
     at HttpsTests.CrossBinding_Soap11_EchoString(String variationDetails) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\HttpsTests.cs:line 29
  
  Xunit.AssertTestException: Assert.True: Test case FAILED with errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
  'Client:: CustomBinding/MessageVersion=Soap11
  Server:: BasicHttpsBinding/DefaultValues'
  Exception: System.ServiceModel.ProtocolException: UnexpectedHttpResponseCode, 400, Bad Request
     at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateResponseStatusCode() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 352
     at System.ServiceModel.Channels.HttpResponseMessageHelper.d__7.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 38
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__15.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__34.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.ServiceModel.Channels.RequestChannel.d__33.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\src\System.Private.CoreLib\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 66
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\Runtime\CompilerServices\TaskAwaiter.cs:line 186
     at System.Runtime.TaskHelpers.WaitForCompletion($Task$1<__Canon> task) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs:line 16707566
     at System.ServiceModel.Channels.RequestChannel.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 241
     at System.ServiceModel.Dispatcher.RequestChannelBinder.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\RequestChannelBinder.cs:line 105
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 765
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 139
     at __InterfaceProxies.ServiceChannelProxy_IWcfService.global.IWcfService_P.Echo(String message) in c:\Users\roncain\AppData\Local\Temp\Ilc3770855\Security.TransportSecurity.Tests.ITFProxy.g.cs:line 65
     at HttpsTests.CrossBinding_Soap11_EchoString(String variationDetails) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\HttpsTests.cs:line 29
  
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.True(Boolean condition, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at HttpsTests.CrossBinding_Soap11_EchoString(String variationDetails) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\HttpsTests.cs:line 46
     at EntryPointMain.b__6() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 19
     at System.Action.InvokeOpenStaticThunk()
     at System.Threading.SendOrPostCallback.Invoke(Object state)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by hongdai** [comment]
There is a project dependency reference issue(see #331). It could have caused this failure. We should wait until #331 is fixed.

**Comment by zhenlan** [comment]
@hongdai do we know if this is still failing?

**Comment by hongdai** [comment]
Yes. It's still failing.

**Comment by zhenlan** [comment]
Thanks. Then we should move this to current milestone.

**Comment by hongdai** [comment]
This test is passing now.
