### ISSUE TITLE
System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]] : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by christopher-millon-abide** [dotnet/wcf#3310]
Hello folks,

Setup a .NET Core 2.1 Application which tries to call WCF Service.
Upon an 'API' call, I'm getting this error.

```System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]] : Object reference not set to an instance of an object.
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.ListRemoteFiles(ListRemoteFilesRequest )```

Seems like it'd have sort of failed to deseralize? Not sure?

Anyway, any idea if this is a bug, or I might be doing something wrong?

**Comment by Lxiamail** [comment]
@christopher-millon-abide Looks like NullReferenceException may have been thrown from the service side, you may debug into your server code.

**Comment by Lxiamail** [comment]
@christopher-millon-abide Hope you have worked on the issue. Closing the issue due to being inactive for a while.

**Comment by Lxiamail** [comment]
@christopher-millon-abide Thanks for sharing.
