### ISSUE TITLE
System.ServiceModel.Description.TypeLoader.AddBehaviorsAtOneScope

### ISSUE THREAD

**Issue by antsaia** [dotnet/wcf#3384]
I'm referencing these libraries in a .NETCORE2.0 project built to run on AWS Lambda. I need to get this working and wondering if you have any suggestions.

I'm getting an error that Operation is not supported on this platform.: PlatformNotSupportedException
at System.ServiceModel.Description.TypeLoader.AddBehaviorsAtOneScope[IBehavior,TBehaviorCollection](Type type, TBehaviorCollection descriptionBehaviors, ServiceInheritanceCallback`2 callback)
at System.ServiceModel.Description.TypeLoader.AddBehaviors(ContractDescription contractDesc, Type implType, Boolean implIsCallback, ContractReflectionInfo reflectionInfo)
at System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation)
at System.ServiceModel.Description.TypeLoader.LoadContractDescription(Type contractType)
at System.ServiceModel.Description.ContractDescription.GetContract(Type contractType)
at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.CreateBaseServiceEndpoint(Uri serviceUrl, TimeSpan timeout)
at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.CreateServiceEndpoint(Uri serviceUrl, Boolean useStrongTypes, TimeSpan timeout, Assembly strongTypeAssembly)
at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1..ctor(Uri serviceUrl, Boolean useStrongTypes)

**Comment by Lxiamail** [comment]
@antsaia Can you provide the repro program which ran into the issue?

**Comment by rstraszewski** [comment]
I had similiar problem, when I had contract with contract behavior as attribute. When I configured behavior in code (on channel factory), the problem was gone.

**Comment by Lxiamail** [comment]
@rstraszewski Can you share a simple repro?

**Comment by rstraszewski** [comment]
@Lxiamail 
https://github.com/rstraszewski/WcfCoreTestClient/blob/master/WcfCoreTestClient/Program.cs

It would be great, if it also worked for attributes - in our company, most of behaviors is set this way. It would make migration to .net core much easier.

**Comment by samlh** [comment]
It would also be fine if we could disable the error message, and add the behavior manually, so that we could still use existing service definitions without having to make changes to the services.

**Comment by rstraszewski** [comment]
Yep, ignoring attributes, instead throwing exceptions also would be ok - it would make migration simpler.

**Comment by rstraszewski** [comment]
@Lxiamail
Any plans regarding support of attribute based behaviors?

**Comment by Lxiamail** [comment]
@rstraszewski Hope we can support it in the next release.

**Comment by Lxiamail** [comment]
The fix has been checked in by https://github.com/dotnet/wcf/pull/3529
