### ISSUE TITLE
CommunicationException: Unknown error -1 

### ISSUE THREAD

**Issue by peterdeme** [dotnet/wcf#3427]
Hi Team,

We have a huge scaling issue and can't seem to find the root cause and we need help. Details:
Environment: .NET Standard 2 
Libs: System.ServiceModel.Http 4.5.3, System.ServiceModel.Primitives 4.5.3.
Class definition: CyberSource's SOAP Client - https://ics2wsa.ic3.com/commerce/1.x/transactionProcessor/
Hosting environment: Docker `microsoft/dotnet:2.2.1-aspnetcore-runtime` on EC2 machines running `amzn-ami-2017.09.g-amazon-ecs-optimized (ami-28456852)`
Our cluster has 4 EC2 instances running 12 replicas of our app with 1024/768 hard/soft memory limit per container.

The issue: when our microservice receive decent amount of load from the clients (5600 request in 17 minutes), our SOAP client starts to throw this error: 
```
System.ServiceModel.CommunicationException: Unknown error -1 ---> System.Net.Http.HttpRequestException: Unknown error -1 ---> System.Net.Sockets.SocketException: Unknown error -1
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at OurSecretCompanyName.Payment.Pay.cs:line 151
```

We don't seem to get this error when we have average load. We suspect it has something to do with sockets/socket filehandles.

Unfortunately when we google the error, it doesn't help us at all, and the error message is not helping either. We are kind of desperate right now and just because of this issue we are evaluating chances to migrate to this 3rd party's (CyberSource) REST API. Before that, if you can give us any kind of guidance or any tips or best practices we could try, we'd really appreciate it.

Thanks!

**Comment by wfurt** [comment]
check TCP connection assigning something like netstat. If endpoint are limited, (for example you talk to single server) there is possibility for TCP port exhaustion. https://www.cyberciti.biz/tips/linux-increase-outgoing-network-sockets-range.html

Is your scenario using persistent connections or do you use new TCP for every request? 

If this is some kind of perf setup you may want to tune some other TCP parameters as well.

**Comment by peterdeme** [comment]
Thank you @wfurt! We'll investigate this aspect.

**Comment by okarlsson** [comment]
@peterdeme Did you find the root cause of this issue?

**Comment by peterdeme** [comment]
@okarlsson yeah, we needed to use the client as a singleton. it wasn’t documented anywhere though so caught us as surprise.

**Comment by okarlsson** [comment]
> @okarlsson yeah, we needed to use the client as a singleton. it wasn’t documented anywhere though so caught us as surprise.

Thanks @peterdeme, I'll give that a try. 

Im currently facing the same issue where all my outgoing http calls starts to fail with the same error you had. So it looks like the wcf client exhausts some resource in my ec2 instances.. 

```
System.Net.Http.HttpRequestException
Unknown error -1
```

```
System.ServiceModel.CommunicationException
Unknown error -1
```

**Comment by StephenBonikowsky** [comment]
@okarlsson Did that resolve your issue?
@mconnew

**Comment by mconnew** [comment]
@okarlsson, you don't need to use the client as a singleton, but you do need to use a single instance of ChannelFactory. .NET Framework pools connections for the entire process so multiple ChannelFactory instances (as long as you use the same credentials as WCF isolates those into separate pools) will use the same connection pool. On .NET Core, HttpClientHandler owns the connection pool. We share a single instance of HttpClient (which wraps HttpClientHandler) for all clients belonging to a single instance of a ChannelFactory. So as long as all your clients come from a single ChannelFactory, they will share the same connection pool.

**Comment by okarlsson** [comment]
@StephenBonikowsky @mconnew 

I'm using generated clients by dotnet-svcutil, so I'm not really in control of much more than making a new client 

I have now wrapped the client in another singleton class to avoid creating new instances all the time. I've been running this for a couple of days and have not seen the error since. I will report back if it reappears :)

```
public class PermissionClientWrapper
{
        private readonly Permission3SoapClient client = new Permission3SoapClient(Permission3SoapClient.EndpointConfiguration.Permission3Soap);

        private static readonly Lazy<PermissionClientWrapper> lazy = new Lazy<PermissionClientWrapper>(() => new PermissionClientWrapper());

        private PermissionClientWrapper()
        {
        }

        public static PermissionClientWrapper Instance => lazy.Value;
}
```
