### ISSUE TITLE
DataContractTests.NetTcpBinding_DuplexCallback_ReturnsXmlComplexType fails on NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#356]
Running Test: DataContractTests.NetTcpBinding_DuplexCallback_ReturnsXmlComplexType
  Caught Unexpected exception:System.ArgumentNullException: ArgumentNull_Generic
     at Internal.Reflection.Execution.ReflectionExecutionDomainCallbacksImplementation.ActivatorCreateInstance(Type type, Object[] args) in f:\dd\ndp\fxcore\src\System.Private.Reflection.Execution\Internal\Reflection\Execution\ReflectionExecutionDomainCallbacksImplementation.cs:line 34
     at System.Xml.Serialization.XmlMappingTypeReflectionWrapperFactory.GetWrapper(Type type) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\Serialization\XmlMappingTypes.cs:line 329
     at System.Xml.Serialization.XmlReflectionMember..ctor() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\Serialization\XmlMappingTypes.cs:line 221
     at System.ServiceModel.Description.XmlSerializerHelper.GetXmlReflectionMember($XmlName memberName, $XmlName elementName, String ns, Type type, $MemberInfo additionalAttributesProvider, Boolean isMultiple, Boolean isWrapped, $XmlReflectionMember member) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\XmlSerializerOperationBehavior.cs:line 827
     at System.ServiceModel.Description.XmlSerializerHelper.GetXmlReflectionMember($MessagePartDescription part, Boolean isRpc, Boolean isWrapped) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\XmlSerializerOperationBehavior.cs:line 822
     at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.LoadBodyMapping($MessageDescription message, String mappingKey, $MessagePartDescriptionCollection& rpcEncodedTypedMessageBodyParts) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\XmlSerializerOperationBehavior.cs:line 462
     at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.CreateMessageInfo($MessageDescription message, String key) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\XmlSerializerOperationBehavior.cs:line 398
     at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.OperationReflector.EnsureMessageInfos() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\XmlSerializerOperationBehavior.cs:line 347
     at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.EnsureMessageInfos() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\XmlSerializerOperationBehavior.cs:line 190
     at System.ServiceModel.Description.XmlSerializerOperationBehavior.System.ServiceModel.Description.IOperationBehavior.ApplyDispatchBehavior($OperationDescription description, $DispatchOperation dispatch) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\XmlSerializerOperationBehavior.cs:line 137
     at System.ServiceModel.Description.DispatcherBuilder.BindOperations($ContractDescription contract, $ClientRuntime proxy, $DispatchRuntime dispatch) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\DispatcherBuilder.cs:line 255
     at System.ServiceModel.Description.DispatcherBuilder.ApplyClientBehavior($ServiceEndpoint serviceEndpoint, $ClientRuntime clientRuntime) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\DispatcherBuilder.cs:line 200
     at System.ServiceModel.Description.DispatcherBuilder.BuildProxyBehavior($ServiceEndpoint serviceEndpoint, $BindingParameterCollection& parameters) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\DispatcherBuilder.cs:line 44
     at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory($ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose, $ChannelRequirements requirements) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs:line 119
     at System.ServiceModel.ChannelFactory.CreateFactory() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs:line 166
     at System.ServiceModel.ChannelFactory.OnOpening() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs:line 376
     at System.ServiceModel.Channels.CommunicationObject.d__71.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 343
  ---

**Comment by roncain** [comment]
Currently being tested via changes to the Reducer and SG in the toolchain

**Comment by shmao** [comment]
The fix has been check-in into Net Native.
