### ISSUE TITLE
DuplexCallback_Throws_FaultException_ReturnsFaultedTask fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#360]
--------------------------------
  Running Test: ExpectedExceptionTests.DuplexCallback_Throws_FaultException_ReturnsFaultedTask
  Assert.True:Expected 'System.ServiceModel.FaultException`1[FaultDetail]' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.ServiceModel.FaultException`1[FaultDetail]' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
     at Xunit.Assert.Throws(Action action) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at ExpectedExceptionTests.DuplexCallback_Throws_FaultException_ReturnsFaultedTask($<>c__DisplayClass17 CS$<>8__locals18) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 411
     at EntryPointMain.b__a() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ExpectedExceptions\Client.ExpectedExceptions.Tests.main.cs:line 23
     at System.Action.InvokeOpenStaticThunk()
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by roncain** [comment]
This may have been fixed by the combination of Khoa's fixes in serialization as well as a pending fix in the toolchain @shmao and I are working on.

**Comment by roncain** [comment]
Passes in latest set of tests using latest toolchain:

  --------------------------------
  Running Test: ExpectedExceptionTests.DuplexCallback_Throws_FaultException_ReturnsFaultedTask
  ---- Test PASSED ---------------
