### ISSUE TITLE
ServiceContract_TypedProxy_AsyncTask_CallbackReturn fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#361]
Running Test: TypedProxyDuplexTests.ServiceContract_TypedProxy_AsyncTask_CallbackReturn
  Caught Unexpected exception:System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.ServiceModel.CommunicationException: SFxServerDidNotReply
     at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.FinishSend(IAsyncResult result, Boolean completedSynchronously) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1868
     at System.Runtime.AsyncResult.End(IAsyncResult result) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\AsyncResult.cs:line 376
     at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End($SendAsyncResult result) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1899
     at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 807
     at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.b__0(IAsyncResult asyncResult) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 179
     Exception_EndOfInnerExceptionStack
     at System.AggregateException.Handle(Func$2 predicate) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\AggregateException.cs:line 322
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$2() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 202
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Boolean CS$1$0000) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---> AggregateException_InnerExceptionSystem.ServiceModel.CommunicationException: SFxServerDidNotReply
     at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.FinishSend(IAsyncResult result, Boolean completedSynchronously) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1868
     at System.Runtime.AsyncResult.End(IAsyncResult result) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\AsyncResult.cs:line 376
     at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End($SendAsyncResult result) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1899
     at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 807
     at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.b__0(IAsyncResult asyncResult) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 179<---
  
  ---- Test FAILED ---------------

**Comment by hongdai** [comment]
Is this test TypedProxyDuplexTests.ServiceContract_TypedProxy_AsyncTask_CallbackReturn?

If so, I'm getting a more concrete error this week. See below:

 Running Test: TypedProxyDuplexTests.ServiceContract_TypedProxy_AsyncTask_CallbackReturn
  Caught Unexpected exception:System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.ServiceModel.FaultException: A reply message was received for operation 'ServicePingCallback' with action 'http://tempuri.org/IWcfDuplexTaskReturnService/Ping'. However, your client code requires action 'http://tempuri.org/IWcfDuplexTaskReturnService/ServicePingCallbackResponse'.
     at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood($Message reply, $MessageFault fault, String action, $MessageVersion version, $FaultConverter faultConverter) in E:\ProjectK\src\NDP\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1067
     at System.ServiceModel.Channels.ServiceChannel.HandleReply($ProxyOperationRuntime operation, $ProxyRpc rpc) in E:\ProjectK\src\NDP\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 948
     at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result) in E:\ProjectK\src\NDP\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 810
     at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.b__0(IAsyncResult asyncResult) in E:\ProjectK\src\NDP\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 179
     Exception_EndOfInnerExceptionStack
     at System.AggregateException.Handle(Func$2 predicate) in f:\dd\ndp\fxcore\src\System.Private.Threading\System\AggregateException.cs:line 322
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$2() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 202
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Boolean CS$1$0000) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---> AggregateException_InnerExceptionSFxFaultExceptionToString3, System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail], A reply message was received for operation 'ServicePingCallback' with action 'http://tempuri.org/IWcfDuplexTaskReturnService/Ping'. However, your client code requires action 'http://tempuri.org/IWcfDuplexTaskReturnService/ServicePingCallbackResponse'., SFxExceptionDetailFormat
  System.ServiceModel.ProtocolException: A reply message was received for operation 'ServicePingCallback' with action 'http://tempuri.org/IWcfDuplexTaskReturnService/Ping'. However, your client code requires action 'http://tempuri.org/IWcfDuplexTaskReturnService/ServicePingCallbackResponse'.
     at System.ServiceModel.Dispatcher.TaskMethodInvoker.InvokeEnd(Object instance, Object[]& outputs, IAsyncResult result)
     at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeEnd(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage7(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)<---

**Comment by mconnew** [comment]
This means the wrong class is being reflected over to build the service description internally.

**Comment by roncain** [comment]
@mconnew, any ideas why does it occurs only in NET Native?

**Comment by roncain** [comment]
Passes using latest toolchain:

  --------------------------------
  Running Test: TypedProxyDuplexTests.ServiceContract_TypedProxy_AsyncTask_CallbackReturn
  ---- Test PASSED ---------------
