### ISSUE TITLE
Fix TCP scenarios blocked by behaviour difference in Claim ctor

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#387]
There is a behaviour difference in `System.Security.Claims.Claim...ctor` that got introduced between Desktop and CoreCLR that causes an exception to be thrown when trying to create an [AnonymousIdentity]( https://github.com/dotnet/wcf/blob/fb9eedb3bbc464bdf5819ef454a4e21f31f45571/src/System.Private.ServiceModel/src/System/IdentityModel/SecurityUtils.cs#L36). 

Repro: 

    public static void Main()
    {
        System.Security.Principal.GenericIdentity identity = new System.Security.Principal.GenericIdentity(""); 
    }

The difference is a change in the way the constructor works - the empty string (valid value in desktop) is now treated the same as null (an invalid value), and therefore the call fails with the exception below

```
System.ArgumentNullException : Value cannot be null.
Parameter name: value
Stack Trace:
    at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
    at System.Security.Principal.GenericIdentity.AddNameClaim()
```

This issue tracks figuring out the way forward for this issue: either the fix happens in System.Security.Claims or we work around it somehow in WCF Core code on the Identity team's advice.

**Comment by iamjasonp** [comment]
Fix has been made - we expect the change to hit in the package build tonight.

**Comment by iamjasonp** [comment]
The fix is in package System.Security.Claims >= 4.0.1-beta-23408
