### ISSUE TITLE
Scaffolded service reference code contains wrong type annotation- XmlTextAttribute for double[]

### ISSUE THREAD

**Issue by urza** [dotnet/wcf#3980]
After importing this soap service:
https://katastr.cuzk.cz/dokumentace/ws28/wsdp/informace_v28.wsdl
in visual studio 2019, the generated Reference.cs class for this service contains one property with wrong data type annotation:

```
[System.Xml.Serialization.XmlTextAttribute()]
public double[] Text
{
    get
    {
        return this.textField;
    }
    set
    {
        this.textField = value;
    }
}
```
This comes from DirectPositionType which is part of OpenGis namespace types http://www.opengis.net/gml/3.2

When calling this service, it ends with Exception (below).

After deleting the data annotation line `[System.Xml.Serialization.XmlTextAttribute()]` it works.

This behaviour is same for full .NET Framework and for .net core projects.

I am not sure if this is problem in .net/VS or something wrong with the metadata/types definition in given service. If it is wrong on the service side I apologise for taking your time and will inform the service operator. 

Exception:

```
System.InvalidOperationException: There was an error reflecting 'DejMBRParcelResponse'.
 ---> System.InvalidOperationException: There was an error reflecting type 'ServiceReference1.DejMBRParcelResponseType'. ---> System.InvalidOperationException: There was an error reflecting property 'infoList'.
 ---> System.InvalidOperationException: There was an error reflecting type 'ServiceReference1.InfoListType'.
 ---> System.InvalidOperationException: There was an error reflecting property 'MBRList'.
 ---> System.InvalidOperationException: There was an error reflecting type 'ServiceReference1.InfoListTypeMBR'.
 ---> System.InvalidOperationException: There was an error reflecting property 'boundedBy'.
 ---> System.InvalidOperationException: There was an error reflecting type 'ServiceReference1.BoundingShapeType'.
 ---> System.InvalidOperationException: There was an error reflecting property 'Item'.
 ---> System.InvalidOperationException: There was an error reflecting type 'ServiceReference1.EnvelopeType'.
 ---> System.InvalidOperationException: There was an error reflecting property 'Items'.
 ---> System.InvalidOperationException: There was an error reflecting type 'ServiceReference1.DirectPositionType'.
 ---> System.InvalidOperationException: There was an error reflecting property 'Text'.
 ---> System.InvalidOperationException: Member 'Text' cannot be encoded using the XmlText attribute. You may use the XmlText attribute to encode primitives, enumerations, arrays of strings, or arrays of XmlNode.
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(StructModel parent, FieldModel model, XmlAttributes a, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(StructModel parent, FieldModel model, XmlAttributes a, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(StructModel parent, FieldModel model, XmlAttributes a, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(StructModel parent, FieldModel model, XmlAttributes a, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.CreateArrayElementsFromAttributes(ArrayMapping arrayMapping, XmlArrayItemAttributes attributes, Type arrayElementType, String arrayElementNs, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping(ArrayModel model, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(StructModel parent, FieldModel model, XmlAttributes a, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(StructModel parent, FieldModel model, XmlAttributes a, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportMemberMapping(XmlReflectionMember xmlReflectionMember, String ns, XmlReflectionMember[] xmlReflectionMembers, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping(XmlReflectionMember[] xmlReflectionMembers, String ns, Boolean hasWrapperElement, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ChainedAsyncResult.End(IAsyncResult result)
   at System.ServiceModel.ClientBase`1.System.ServiceModel.ICommunicationObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by mconnew** [comment]
I don't think removing the attribute is doing what you intend and I suspect it's not working correctly but you just haven't noticed that you aren't getting your data. In https://katastr.cuzk.cz/dokumentace/xsd/gml.xsd there is a definition of a `<simpleType>` called `doubleList`. I've copied it here excluding non-structural schema elements:  
```xml
<simpleType name="doubleList">
  <list itemType="double"/>
</simpleType>
```
So now you can use a datatype called doubleList to represent a list of doubles, which is where `double[]` comes from in the generated code. If we go to section _4.1.2.2 Deriviation by list_ section of the [w3.org spec for xml schema datatypes](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/datatypes.html#derivation-by-list), it says the following about lists:

> A ·list· datatype must be ·derived· from an ·atomic· or a ·union· datatype, known as the ·itemType· of the ·list· datatype. This yields a datatype whose ·value space· is composed of finite-length sequences of values from the ·value space· of the ·itemType· and whose ·lexical space· is composed of space-separated lists of literals of the ·itemType·.

So this is defining a space separated list of doubles. If you defined an element called `Foo` with the datatype doubleList, it might look something like this in the generated xml:
```xml
<Foo>1.34 6.2353 187.3</Foo>
```
In WCF, when the XmlText attribute is applied, it means the data is included directly in the text part of the element without using a child XML element. To illustrate, here's an example of two classes and their output:
```c#
public class Foo
{
  public int Bar { get; set; }
  public int Ram { get; set; }
}
```
Would produce:
```xml
<Foo>
  <Bar>100</Bar>
  <Ram>200</Ram>
</Foo>
```
Whereas this:
```c#
public class Foo
{
  [XmlText]
  public int Bar { get; set; }
  public int Ram { get; set; }
}
```
Would produce:
```xml
<Foo>100
  <Ram>200</Ram>
</Foo>
```
It removes the wrapping element around the data. .NET only supports (as per the error message) the type of a property with the XmlText attribute applied being primitives, enumerations, arrays of strings, or arrays of XmlNode (basically allows you to process inner XML as a sequence of XmlNode for very custom scenarios). When you removed the XmlText attribute, it will ignore any textual content of the containing class and expect the array of doubles to be represented by child XML elements. When parsing an xml document with real data used in a doubleList, it will ignore the data and set the array of doubles to an empty array (or possibly null).  

Unfortunately .NET doesn't support this type schema automatically. Here's what you need to do to get your data:
```c#
[XmlIgnore]
public List<Double> DoubleList
{
    { get; set; }
}

[System.Xml.Serialization.XmlTextAttribute()]
internal string Text
{
    get
    {
        return string.Join(' ', DoubleList.ToArray())
    }
    set
    {
        string[] doubleStrArr = value.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        List<Double> list = new List<Double>(doubleStrArr.Length);
        foreach(var doubleStr in doubleStrArr)
        {
            // This will throw if the value can't be parsed as a double.
            // This matches similar behavior to what would happen if .NET supported this directly.
            // You might want to use TryParse and swallow/log errors.
            list.Add(double.Parse(doubleStr));
        }
        DoubleList = list;
    }
}
```

**Comment by StephenBonikowsky** [comment]
@urza Hopefully @mconnew provided you with the necessary information to resolve your problem. Let us know if you need anything else.
