### ISSUE TITLE
WebSockets tests fail in Net Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#404]
This may be a dependency issue in our TFS wrapper projects, but it needs to be investigated.
These 3 tests fail running TFS/OSS tests against NET Native: 

Binding_NetHttp_WebSocketTests.DuplexOverWebSocket_Echo_RoundTrips_Guid
Binding_NetHttp_WebSocketTests.RequestResponseOverWebSocketManually_Echo_RoundTrips_Guid
Binding_NetHttp_WebSocketTests.TransportUsageAlways_WebSockets_Synchronous_Call

All fail for what appears to be some MCG interop issue:
 Running Test: Binding_NetHttp_WebSocketTests.TransportUsageAlways_WebSockets_Synchronous_Call
  Caught Unexpected exception:System.ArgumentNullException: ArgumentNull_Generic
  Arg_ParamName_Name, Null_HString. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
     at System.Runtime.InteropServices.McgMarshal.StringToHStringReference(Char* pchPinnedSourceString, String sourceString, $HSTRING_HEADER* pHeader, $HSTRING* phString) in f:\dd\ndp\fxcore\src\System.Private.Interop\Shared\McgMarshal.cs:line 656
     at McgInterop.ForwardComSharedStubs.Proc_ushort__string__($__ComObject __this, UInt16 code, String reason, RuntimeTypeHandle __typeHnd, Int32 __targetIndex, String CS$519$0000) in c:\Users\roncain\AppData\Local\Temp\Ilc1472955632\Binding.NetHttp.Tests.Interop\SharedStubs.g.cs:line 17734
     at System.Net.WebSockets.WinRTWebSocket.CloseOutputAsync($WebSocketCloseStatus closeStatus, String statusDescription, $CancellationToken cancellationToken) in E:\ProjectK\src\NDP\FxCore\src\System.Net.WebSockets.Client\System\Net\WebSockets\WinRTWebSocket.cs:line 210
     at System.Net.WebSockets.ClientWebSocket.CloseOutputAsync($WebSocketCloseStatus closeStatus, String statusDescription, $CancellationToken cancellationToken) in E:\ProjectK\src\NDP\FxCore\src\System.Net.WebSockets.Client\System\Net\WebSockets\ClientWebSocket.cs:line 201
     at System.ServiceModel.Channels.WebSocketTransportDuplexSessionChannel.CloseOutputAsync() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WebSocketTransportDuplexSessionChannel.cs:line 407
     at System.ServiceModel.Channels.WebSocketTransportDuplexSessionChannel.CloseOutputAsync$catch$0() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WebSocketTransportDuplexSessionChannel.cs:line 416
     at System.ServiceModel.Channels.WebSocketTransportDuplexSessionChannel.d__34.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WebSocketTransportDuplexSessionChannel.cs:line 174
     at System.ServiceModel.Channels.WebSocketTransportDuplexSessionChannel.d__34.MoveNext$catch$0() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WebSocketTransportDuplexSessionChannel.cs:line 188

**Comment by mconnew** [comment]
This should be fixed now. I'll verify that this is the case.

**Comment by hongdai** [comment]
Verified the tests are passing with the latest bits.
