### ISSUE TITLE
Reference to - Support Basic Http/Https Binding with TransportWithMessageCredential

### ISSUE THREAD

**Issue by se7vanj** [dotnet/wcf#4045]
#3552 Support Basic Http/Https Binding with TransportWithMessageCredential. This issue was closed with note "merged to WCF Core 3.0", but I have a question on its resolution.

**Issue**: with **DotNet 3.1.100-preview3-014645**, problem still exists, getting below error when consuming a service which requires **wsse:Security**. Am I missing anything..

**Error**: The value 'TransportWithMessageCredential' is not supported in this context for the binding security property 'securityMode'

**Comment by StephenBonikowsky** [comment]
@se7vanj this should be working. We have several tests, [here is one](https://github.com/dotnet/wcf/blob/release/3.1.0/src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs#L15) that run regularly.

Which WCF package version is being used in your project? (DotNet 3.1.100-preview3-014645 is the .NET Core package, but WCF ships separately, see [wcf-library-components](https://github.com/dotnet/wcf#wcf-library-components))
Can you tell us anything more about your binding, maybe provide us with your WSDL?

**Comment by StephenBonikowsky** [comment]
@se7vanj Feel free to re-open this issue if you have any additional info for us.

Thanks.

**Comment by thinhnotes** [comment]
hi @StephenBonikowsky in current in used the .net core 3.1, but when I init the BasicHttpBinding with mode TransportWithMessageCredential it will be return the exception 'The value 'TransportWithMessageCredential' is not supported in this context for the binding security property 'securityMode'.'
Could you please to help me this case.

Thanks,

My Code

`BasicHttpBinding binding = new BasicHttpBinding(BasicHttpSecurityMode.TransportWithMessageCredential);`

**Comment by StephenBonikowsky** [comment]
Message security is not yet supported on WCF Core.
@mconnew can you confirm that `TransportWithMessageCredential` is part of the Message Security feature?

**Comment by mconnew** [comment]
@thinhnotes, you are probably not using the latest System.ServiceModel.* packages. We have scenario tests which exercise this exact scenario [here](https://github.com/dotnet/wcf/blob/d8724e17061fec86c9a6b17596fccd3f05cf758f/src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs#L26).

**Comment by DarkAngel766** [comment]
The scenario does not work for me (neither).
There is an expected header that just doesn't exist:
`   <soapenv:Header>
      <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <wsse:UsernameToken>
            <wsse:Username>XXXXXX</wsse:Username>
            <wsse:Password>XXXXXX</wsse:Password>
         </wsse:UsernameToken>
      </wsse:Security>
   </soapenv:Header>
`

What am I doing wrong???

**Comment by mconnew** [comment]
If you aren't getting that header added then your binding is incorrect. Take a look at the scenario test I linked to for example usage. If that doesn't work, can you provide your binding.

**Comment by DarkAngel766** [comment]
Apologies. I left before I got this response. I'll post t asap Monday.

**Comment by DarkAngel766** [comment]
The binding was taken from your example:
`        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(System.TimeSpan timeout)
        {
            System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding(System.ServiceModel.SecurityMode.TransportWithMessageCredential);
            result.Security.Message.ClientCredentialType = System.ServiceModel.MessageCredentialType.UserName;
            result.MaxBufferPoolSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.ReceiveTimeout = timeout;
            result.SendTimeout = timeout;
            result.OpenTimeout = timeout;
            result.CloseTimeout = timeout;
            return result;
        }
`

Credentials are set on the constructor:
`        public DataLinkServicePortClient(string endpointUrl, System.TimeSpan timeout, string username, string password) :
        base(GetBindingForEndpoint(timeout), GetEndpointAddress(endpointUrl))
        {
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
`

**Comment by DarkAngel766** [comment]
Additional odd behavior. Only the first attribute is read. I have comment everything before USAddress for this to work properly:
`        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CanadaAddress", typeof(CanadaAddressType[]), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ChileAddress", typeof(ChileAddressType[]), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("InternationalAddress", typeof(InternationalAddressType[]), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SpainAddress", typeof(SpainAddressType[]), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UKAddress", typeof(UKAddressType[]), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("USAddress", typeof(USAddress[]), IsNullable=false)]
        public AddressType[] Addresses
`

**Comment by DarkAngel766** [comment]
Please let me know if there's anything else I can provide. Thanks :)

**Comment by DarkAngel766** [comment]
Please reopen this ticket.  I will resolve my issue manually, but your package does not work as advertised.

**Comment by dnascimento** [comment]
Please reopen this issue. This isn't working as expected and it is not well documented.

**Comment by mconnew** [comment]
@DarkAngel766, can you provide more info about about what isn't working? There's multiple things you've listed and I'm not sure what's blocking you and what you have got working. If the problem is with TransportWithMessageCredentials with client credential type of UserName, can you provide the WSDL from the server?  

@dnascimento, this is the first you've commented on here and you have no info as to what your problem is. Can you open a new issue for what your problem is. In that issue, provide your binding info, and any errors you are receiving as well detailing what you are expecting vs what you are experiencing?

**Comment by nyonor** [comment]
Client was generated with dotnet-svcutil. Target framework .net5.0. Console application.

`services.AddTransient<UTL2PortType>(provider =>
                    {
                        var c = new UTL2PortTypeClient(
                            binding: new CustomBinding(new BasicHttpsBinding(BasicHttpsSecurityMode.TransportWithMessageCredential)),
                            new EndpointAddress(context.Configuration["ExternalServices:Utl2:Address"]));
                        c.ClientCredentials.UserName.UserName = context.Configuration["ExternalServices:Utl2:UserName"];
                        c.ClientCredentials.UserName.Password = context.Configuration["ExternalServices:Utl2:Password"];
                        return c;
                    });`

Stacktrace:

System.PlatformNotSupportedException: The value 'TransportWithMessageCredential' is not supported in this context for the binding security property 'securityMode'.
   at System.ServiceModel.BasicHttpsBinding..ctor(BasicHttpsSecurityMode securityMode)
   at Scheduled.Program.<>c__DisplayClass1_0.<CreateHostBuilder>b__2(IServiceProvider provider) in /src/Presentation/Scheduled/Program.cs:line 91
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Coravel.Scheduling.Schedule.Event.ScheduledEvent.GetInvocable(IServiceProvider serviceProvider)
   at Coravel.Scheduling.Schedule.Event.ScheduledEvent.InvokeScheduledEvent(CancellationToken cancellationToken)

Packages installed:

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="10.1.1" />
        <PackageReference Include="AutoMapper.Collection" Version="7.0.1" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
        <PackageReference Include="Coravel" Version="4.0.2" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="5.0.1" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
        <PackageReference Include="MongoDB.Driver" Version="2.13.1" />
        <PackageReference Include="Serilog" Version="2.10.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
        <PackageReference Include="Serilog.Sinks.MongoDB" Version="5.0.0" />
        <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
        <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
        <PackageReference Include="System.ServiceModel.Primitives" Version="4.8.1" />
        <PackageReference Include="System.ServiceModel.Security" Version="4.8.1" />
    </ItemGroup>
