### ISSUE TITLE
Could not load type 'System.ServiceModel.Description.MetadataConversionError' from assembly 'System.ServiceModel

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [dotnet/wcf#4144]
Hello,

i have migrated my project from .NET Framework to .NET core. i have changed this line from

  sp.ServiceConfiguration.CurrentServiceEndpoint.Behaviors.Add(new ProxyTypesBehavior());
to

 sp.ServiceConfiguration.CurrentServiceEndpoint.EndpointBehaviors.Add(new ProxyTypesBehavior());
`
because we used System.ServiceModel.Primitives 
this is my full code 
````````
public static class CRMConnection
    {
        private static OrganizationServiceProxy sp = null;
        private static IWebProxy proxy = WebRequest.DefaultWebProxy;
        private static string URL;
        private static string Login;
        private static string MDP;
        private static string B64_Encoded_MDP;
        private static string Xml_Settings_Path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.FullName + @"\VSMP_Settings_File.xml";
        private static XmlDocument VELBOURN_Settings;

        public static OrganizationServiceProxy InitCRMConnection()
        {
            try
            {


                const SslProtocols _Tls12 = (SslProtocols)0x00000C00;

                const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;

                ServicePointManager.SecurityProtocol = Tls12;

                VELBOURN_Settings = new XmlDocument();
                VELBOURN_Settings.Load(Xml_Settings_Path);
                B64_Encoded_MDP = VELBOURN_Settings.DocumentElement.SelectSingleNode("//CRMConnection_Settings//MDP").InnerText;
                MDP = Base64Decode(B64_Encoded_MDP);
                URL = VELBOURN_Settings.DocumentElement.SelectSingleNode("//CRMConnection_Settings//CRMLink").InnerText;
                Login = VELBOURN_Settings.DocumentElement.SelectSingleNode("//CRMConnection_Settings//Login").InnerText;

                PropertyInfo _WebProxy = proxy.GetType().GetProperty("WebProxy", BindingFlags.NonPublic | BindingFlags.Instance);
                WebProxy wProxy = (WebProxy)_WebProxy.GetValue(proxy, null);
                wProxy.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;
                

                if (string.IsNullOrEmpty(URL) || string.IsNullOrEmpty(Login) || string.IsNullOrEmpty(MDP))
                    throw new Exception("connection failed");

                Uri OrganizationUri = new Uri(Path.Combine(URL + "XRMServices/2011/Organization.svc"));
                ClientCredentials cc = new ClientCredentials();
                ClientCredentials cd = null;

                cc.UserName.UserName = Login;
                cc.UserName.Password = MDP;

                sp = new OrganizationServiceProxy(OrganizationUri, null, cc, cd);
                sp.ServiceConfiguration.CurrentServiceEndpoint.EndpointBehaviors.Add(new ProxyTypesBehavior());

            }
            catch (Exception ex)
            {
                LogHelper.Writer("Erreur lors de la connexion au crm, Message de l'erreur : " + Environment.NewLine + ex.ToString());
            }
            return sp;
        }       
        private static string Base64Decode(string base64EncodedData)
        {
            var base64EncodedBytes = Convert.FromBase64String(base64EncodedData);
            return Encoding.UTF8.GetString(base64EncodedBytes);
        }
    }

````````

but it return `
System.TypeLoadException: Could not load type 'System.ServiceModel.Description.MetadataConversionError' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceConfiguration..ctor(Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateConfiguration[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateConfiguration[TService](Uri serviceUri)
   at Microsoft.Xrm.Sdk.Client.ServiceProxy`1..ctor(Uri uri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy..ctor(Uri uri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)

**Comment by StephenBonikowsky** [comment]
Closing this one, the way I moved it from the runtime repo lost the conversation history.

See #4147 instead.

**Comment by tesfayegari** [comment]
Did this issue get resolved. What is the best way to make this work in .NET Core please help I am having same problem

**Comment by StephenBonikowsky** [comment]
@tesfayegari Please monitor #4147
