### ISSUE TITLE
WCF on DotNet Core 3.1 gives AccessViolationException when CreateChannel is called

### ISSUE THREAD

**Issue by gaganjyot** [dotnet/wcf#4165]
**Describe the bug**
WCF on DotNet Core 3.1 gives AccessViolationException when CreateChannel is called

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**To Reproduce**

```Code
            var binding = new NetTcpBinding(SecurityMode.None);
            var endpoint = new EndpointAddress("net.tcp://localhost:51111/zservice");
            var singlexchannel = new ChannelFactory<IBasicCalculator>(binding, endpoint);
            var _client = singlexchannel.CreateChannel();  // Throws the exception
```

**StackTrace:**

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Reflection.DispatchProxyGenerator+ProxyAssembly..ctor()
   at System.Reflection.DispatchProxyGenerator..cctor()
   at System.Reflection.DispatchProxyGenerator.GetProxyType(System.Type, System.Type)
   at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(System.Type, System.Type)
   at System.Reflection.DispatchProxy.Create[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
   at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ServiceModel.Description.MessageDirection, System.ServiceModel.Channels.ServiceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ServiceModel.Description.MessageDirection, System.ServiceModel.Channels.ServiceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ServiceModel.EndpointAddress, System.Uri)
   at System.ServiceModel.ChannelFactory`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateChannel(System.ServiceModel.EndpointAddress, System.Uri)

**Expected behavior**
Create channel should proceed succesfully without any exceptions.

**Comment by StephenBonikowsky** [comment]
@gaganjyot Thank you for reporting this, could you please provide us with a little additional info?

- What OS is this occurring on?
- Can you get us a full copy of the contract interface you are using? (IBasicCalculator)
- The exact version of .NET Core you are using.

Thank you!

**Comment by StephenBonikowsky** [comment]
@gaganjyot An AccessViolationException can only be thrown by unmanaged code. Based on the last line of the call stack this issue should be opened in the https://github.com/dotnet/runtime repo.

They will most likely also need the additional info we requested here.

Please open a new issue in that repo, thanks!
