### ISSUE TITLE
Https scenario tests fail on Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#417]
The Https tests fail under Linux when BridgeClient attempts to work with certificates:

   Contract.Message.Tests  Total: 5, Errors: 0, Failed: 0, Skipped: 0, Time: 3.266s
   Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
            at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
            at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
            at Infrastructure.Common.BridgeClientCertificateManager.AddToStoreIfNeeded(StoreName storeName, StoreLocation storeLocation, X509Certificate2 certificate)
            at Infrastructure.Common.BridgeClientCertificateManager.InstallCertificateToRootStore(X509Certificate2 certificate)
            at Infrastructure.Common.BridgeClientCertificateManager.InstallRootCertificateFromBridge()
            at Endpoints.get_Https_BasicAuth_Address()
            at Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo()
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by roncain** [comment]
The X509Store implementation of Linux appears post-RTM:
https://github.com/dotnet/corefx/issues/3690

**Comment by roncain** [comment]
Closing because this is a dup of #438
