### ISSUE TITLE
ExpectedExceptionTests.NotExistentHost_Throws_EndpointNotFoundException fails on Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#419]
ExpectedExceptionTests.NotExistentHost_Throws_EndpointNotFoundException [FAIL]

      Assert.Throws() Failure
      Expected: typeof(System.ServiceModel.EndpointNotFoundException)
      Actual:   typeof(System.ServiceModel.CommunicationException): An error occurred while sending the request.
      Stack Trace:
            at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)
            at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__11.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__34.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__33.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Runtime.TaskHelpers.WaitForCompletion[TResult](Task`1 task)
            at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
            at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
            at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
            at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
            at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
            at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
            at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
            at generatedProxy_1.Echo(String )
            at ExpectedExceptionTests.<>c__DisplayClass0_0.<NotExistentHost_Throws_EndpointNotFoundException>b__0()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
            at generatedProxy_1.Echo(String )
            at ExpectedExceptionTests.<>c__DisplayClass0_0.<NotExistentHost_Throws_EndpointNotFoundException>b__0()

**Comment by mconnew** [comment]
HttpClient on Linux is returning an HResult in the inner exception of 0x6. I've opened bug dotnet/corefx#4148 to have this fixed.

**Comment by roncain** [comment]
The fact this fails always on Linux and is flakey on CI machines suggests possible timing issues and difference in behavior between Windows and Linux async handling.  Consider adding an explicit open of the client proxy to eliminate the chances of the implicit open logic affecting the timing.

**Comment by zhenlan** [comment]
Current plan is WCF will at least handle most common failures on Linux (Map Linux HResult error to what we know).

**Comment by roncain** [comment]
Latest discovery: Linux HttpClient is now returning HResult 0x80131620, an I/O error during streaming. The original issue was seeing HResult 0x6.
