### ISSUE TITLE
Creating CustomBinding with UsernameTransport in .net core 3.1

### ISSUE THREAD

**Issue by gdodd1977** [dotnet/wcf#4227]
I'm trying to consume a WCF service that creates a binding like this in a full framework project.

```xml
<customBinding>
	<binding name="CustomBinding_IClaimService">
		<security defaultAlgorithmSuite="Default" authenticationMode="UserNameOverTransport" requireDerivedKeys="true" includeTimestamp="true" messageSecurityVersion="WSSecurity11WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10">
			<localClientSettings detectReplays="false" />
			<localServiceSettings detectReplays="false" />
		</security>
		<textMessageEncoding messageVersion="Soap12" />
		<httpsTransport />
	</binding>
	<binding name="CustomBinding_IIssueService">
		<security defaultAlgorithmSuite="Default" authenticationMode="UserNameOverTransport" requireDerivedKeys="true" includeTimestamp="true" messageSecurityVersion="WSSecurity11WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10">
			<localClientSettings detectReplays="false" />
			<localServiceSettings detectReplays="false" />
		</security>
		<textMessageEncoding messageVersion="Soap12" />
		<httpsTransport />
	</binding>
</customBinding>
```

I can't seem to get this replicated in a .net core 3.1 project though. I am getting this error message no matter what kind of binding I try programatically.

> The message with Action '' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver. Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).

**Comment by mconnew** [comment]
Can you provide the code you wrote to create this binding in .NET Core?

**Comment by mconnew** [comment]
I just checked and this looks like a regular WSHttpBinding using using SecurityMode TransportWithMessageCredentials and client credential type of Username.

**Comment by gdodd1977** [comment]
That is the binding that gets generated when I consume that WCF service in a full .net framework project. I'm trying to consume that WCF service in a .net core 3.1 project, but I am unable to replicate that generated binding in that .net core project programatically because WsHttpBinding isn't supported in .net core.

**Comment by mconnew** [comment]
WSHttpBinding is supported in .NET Core. Make sure you are using the latest package versions (currently 4.7.x).

**Comment by Heraisu** [comment]
@mconnew  Saying WsHttpBinding is supported in 4.7.x does not seem accurate. It is possible I am missing something, though.
When making a new client with a new WSHttpBinding(SecurityMode.TransportWithMessageCredential) (or just Transport mode), after you ask it to send any message out at runtime, it will fault with variations of "System.NotSupportedException" and similar. The same does not happen with other binding types. This does not sound like "supported" to me. Please clarify. Am I missing one of the required packages? I have all the System.ServiceModel.* at 4.7, and tried adding System.Private.ServiceModel for good measure.
MSDN does not show WsHttpBinding as being supported in .NET Standard or .NET Core.
Any guidance would be appreciated, if this is supposed to work.

**Comment by mconnew** [comment]
Not all features of WSHttpBinding are supported.Based on your binding config, everything you need should be supported. We don't support everything, for example we don't currently support all client credential types. But the client credential type you are using is supported. Can you provide the code you converted your binding config to and the call stack of the exception?

**Comment by Heraisu** [comment]
Yes, I am not the original poster, thank you for still offering to give feedback on my issue. The following is enough to reproduce the error:

var wsBinding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);
            wsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

(Are Certificates one of the things that, as you mentioned, are unsupported?)
The call stack:
`   at System.ServiceModel.MessageSecurityOverHttp.CreateSecurityBindingElement(Boolean isSecureTransportMode, Boolean isReliableSession, MessageSecurityVersion version)
   at System.ServiceModel.WSHttpSecurity.CreateMessageSecurity(Boolean isReliableSessionEnabled, MessageSecurityVersion version)
   at System.ServiceModel.WSHttpBinding.CreateMessageSecurity()
   at System.ServiceModel.WSHttpBindingBase.CreateBindingElements()
   at System.ServiceModel.WSHttpBinding.CreateBindingElements()
   at System.ServiceModel.Channels.Binding.EnsureInvariants(String contractName)
   at System.ServiceModel.Description.ServiceEndpoint.EnsureInvariants()
   at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory(ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose)
   at System.ServiceModel.ChannelFactory.CreateFactory()
   at System.ServiceModel.ChannelFactory.OnOpening()
   at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__84.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__83.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannelInternal()
   at System.ServiceModel.ClientBase`1.get_Channel()`

**Comment by mconnew** [comment]
@Heraisu , I see your problem. I'm not sure if it's your intention, but you are actually trying to make a mixed mode binding. You are specifying client certificate for transport, but Windows for Message. So you are requesting using the Negotiate protocol over SOAP messages. I suspect this is actually what you want:
```c#
var wsBinding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);
wsBinding.Security.Message.ClientCredentialType = MessageCredentialType.Certificate;
```
You were setting transport security credential type to Certificate, but not setting message security credential type. That defaults to Windows which isn't supported.
