### ISSUE TITLE
WsHttpBinding throws PlatformNotSupportedException .Net Core 3.1

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/wcf#4233]
**Describe the bug**
WsHttpBinding throws PlatformNotSupportedException .Net Core 3.1

**To Reproduce**
On windows
Create a .Net core 3.1 project and add WCF references.

Replace the main file with:

```csharp
using System.ServiceModel;

namespace Client
{
    [ServiceContract]
    public interface IService
    {
        [OperationContract]
        string EchoWithGet(string s);

        [OperationContract]
        string EchoWithPost(string s);
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            using (var cf = new ChannelFactory<IService>(new WSHttpBinding(), new EndpointAddress("http://localhost:8000")))
            {
                var channel = cf.CreateChannel();
            }
        }
    }
}
```

**Expected behavior**
Runs without exception

**Actual Behaviour**

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ServiceModel.MessageSecurityOverHttp.CreateSecurityBindingElement(Boolean isSecureTransportMode, Boolean isReliableSession, MessageSecurityVersion version)
   at System.ServiceModel.WSHttpSecurity.CreateMessageSecurity(Boolean isReliableSessionEnabled, MessageSecurityVersion version)
   at System.ServiceModel.WSHttpBinding.CreateMessageSecurity()
   at System.ServiceModel.WSHttpBindingBase.CreateBindingElements()
   at System.ServiceModel.WSHttpBinding.CreateBindingElements()
   at System.ServiceModel.Channels.Binding.EnsureInvariants(String contractName)
   at System.ServiceModel.Description.ServiceEndpoint.EnsureInvariants()
   at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory(ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose)
   at System.ServiceModel.ChannelFactory.CreateFactory()
   at System.ServiceModel.ChannelFactory.OnOpening()
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at Client.Program.Main(String[] args) in C:\Users\yairh\source\repos\WcfServiceLibrary1\Client\Program.cs:line 21
```

Note that changing the target framework to net472 the program runs without exception

**Comment by mconnew** [comment]
The default constructor for WSHttpBinding uses security mode Message which isn't supported. You need to use either None, Transport, or TransportWithMessageCredential.

**Comment by YairHalberstadt** [comment]
Thanks

**Comment by sachinninawe25** [comment]
@mconnew I am also facing the same issue and tried multiple work around to work but didn't succeeded.

Is there any latest release related to wshttpbinding support in .net core?

Thanks
