### ISSUE TITLE
The project format is incorrect

### ISSUE THREAD

**Issue by michal-ciechan** [dotnet/wcf#4278]
**Describe the bug**
dotnet-svcutil fails with `The project format is incorrect.` when there is a package reference without an "Include" attribute.

Error:
```
Error: The value 'Wcf.csproj' specified for the option 'projectFile' is not valid.
The project format is incorrect.

If you would like more help, type "dotnet-svcutil -h"
Error: The value 'Wcf.csproj' specified for the option 'projectFile' is not valid.
The project format is incorrect.   at Microsoft.Tools.ServiceModel.Svcutil.MSBuildProj.GetItemIdentity(XElement itemName) in E:\A\_work\1\s\dotnet-svcutil-lib\Source\Shared\MSBuildProj.cs:line 395
   at Microsoft.Tools.ServiceModel.Svcutil.MSBuildProj.ParseAsync(String projectText, String projectFullPath, ILogger logger, CancellationToken cancellationToken) in E:\A\_work\1\s\dotnet-svcutil-lib\Source\Shared\MSBuildProj.cs:line 191
   at Microsoft.Tools.ServiceModel.Svcutil.MSBuildProj.FromPathAsync(String filePath, ILogger logger, CancellationToken cancellationToken) in E:\A\_work\1\s\dotnet-svcutil-lib\Source\Shared\MSBuildProj.cs:line 116
```

**To Reproduce**
1. Add `<PackageReference Update="Microsoft.CodeAnalysis.CSharp" Version="3.5.0" />`
2. Run dotnet-svcutil

**Expected behavior**
Either correct find the version, or ignore this package reference.

**Additional context**
If this is something you guys think is worth fixing, I am more than happy at creating a PR.

Also what about including more details when it fails to help debug/diagnose the issue. E.g. would be nice to know it couldn't find "Include" attribute on `<PackageReference Update="Microsoft.CodeAnalysis.CSharp" Version="3.5.0" />`

**Comment by dasetser** [comment]
Thanks for reporting this. We've had previous reports of this throwing errors when trying to parse a csproj file. In general I think the better approach would be to ignore the package reference if it's not the format we're expecting rather than throwing like this. We haven't been able to prioritize fixing this, but you're welcome to submit a PR and we'll review it. 

You can find the file doing this parsing in [MSBuildProj.cs](https://github.com/dotnet/wcf/blob/master/src/dotnet-svcutil/lib/src/Shared/MSBuildProj.cs), most likely in the ParseAsync method.

**Comment by The-MAZZTer** [comment]
Sorry to post in a closed issue, but it looks like the latest release in 2.0.1 despite 2.0.03 being slated for earlier this year.

However as suggested users can work around this issue by temporarily commenting out PackageReferences that this tool does not like. Namely, it does not like the Microsoft.NETCore.App reference. This is probably only an issue in .NET Core 3, since the project version number suggest to me it is only compatible with .NETCore 2 and earlier. The tool itself complained my .NET Core 3 app used a version of .NET Core that was unsupported.

With the reference commented out I was able to generate classes for the API calls I needed. Presumably I can manually tweak things that incompatibilities between .NET Core 2/3 break.
