### ISSUE TITLE
X509Store throws NotImplemented for read/Write on Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#434]
Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ServiceModel.Security.MessageSecurityException)
      Actual:   typeof(System.NotImplementedException): The method or operation is not implemented.
      Stack Trace:
            at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
            at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
            at Infrastructure.Common.BridgeClientCertificateManager.AddToStoreIfNeeded(StoreName storeName, StoreLocation storeLocation, X509Certificate2 certificate)
            at Infrastructure.Common.BridgeClientCertificateManager.InstallCertificateToRootStore(X509Certificate2 certificate)
            at Infrastructure.Common.BridgeClientCertificateManager.InstallRootCertificateFromBridge()
            at Endpoints.get_Https_BasicAuth_Address()
            at Https_ClientCredentialTypeTests.<>c.<BasicAuthenticationInvalidPwd_throw_MessageSecurityException>b__4_0()

**Comment by iamjasonp** [comment]
Test bug - related to BridgeClientCertificateManager. This is being looked at as part of #407

**Comment by iamjasonp** [comment]
Is this a dupe of #417?

**Comment by roncain** [comment]
Let's retitle this one to be that the BridgeClientCertificateManager needs to be fixed.  Once we get past that, we'll know of #417 can be closed or fails for a new reason

**Comment by roncain** [comment]
Changing BridgeClientCertificateManager to use CurrentUser gets past this failure. #438 tracks the failure after this point.
