### ISSUE TITLE
Https functional tests fail in Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#438]
Currently the Https functional tests fail on Linux because the cryptographic libraries are not fully functional on Linux.  Failure is currently method-not-supported from X509Store.Open(ReadWrite).

There may also be other issues of certificate handling hiding behind this early failure.

**Comment by roncain** [comment]
If update BridgeClientCertificateManager to use CurrentUser rather than LocalMachine, this is the failure:

=== TEST EXECUTION SUMMARY ===
   Contract.Message.Tests  Total: 5, Errors: 0, Failed: 0, Skipped: 0, Time: 6.386s
   HttpsTests.SameBinding_Soap12_EchoString [FAIL]
      Test case FAILED with errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
      'Client:: CustomBinding/MessageVersion=Soap12
      Server:: CustomBinding/MessageVersion=Soap12'
      Exception: System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
         at System.Net.Http.CurlHandler.ThrowIfCURLEError(Int32 error)
         at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, Int32 messageResult)
         --- End of inner exception stack trace ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__11.MoveNext()
         --- End of inner exception stack trace ---
         at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)
         at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__11.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__34.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__33.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.Runtime.TaskHelpers.WaitForCompletion[TResult](Task`1 task)
         at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
         at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
         at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
         at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
         at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
         at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
         at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
         at generatedProxy_1.Echo(String )
         at HttpsTests.SameBinding_Soap12_EchoString()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
         at generatedProxy_1.Echo(String )
         at HttpsTests.SameBinding_Soap12_EchoString()
      Inner exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
         at System.Net.Http.CurlHandler.ThrowIfCURLEError(Int32 error)
         at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, Int32 messageResult)
         --- End of inner exception stack trace ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__11.MoveNext()
      Inner exception: System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
         at System.Net.Http.CurlHandler.ThrowIfCURLEError(Int32 error)
         at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, Int32 messageResult)

      Expected: True
      Actual:   False
      Stack Trace:
            at HttpsTests.SameBinding_Soap12_EchoString()
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by roncain** [comment]
@iamjasonp is fixing this with https://github.com/dotnet/wcf/pull/446

**Comment by roncain** [comment]
Closing this issue because a separate issue has now been opened for each unique test failure
