### ISSUE TITLE
Streamed Http tests fail in Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#441]
ServiceContractTests.DefaultSettings_Echo_RoundTrips_String_StreamedRequest [FAIL]
      System.NotSupportedException : Specified method is not supported.
      Stack Trace:
            at System.Net.Http.CurlHandler.HttpContentAsyncStream.Write(Byte[] buffer, Int32 offset, Int32 count)
            at System.Xml.XmlStreamNodeWriter.FlushBuffer()
            at System.Xml.XmlStreamNodeWriter.Flush()
            at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.<WriteMessageAsync>d__39.MoveNext()

We believe this will be fixed by #341

**Comment by roncain** [comment]
Fixed by CoreFx https://github.com/dotnet/corefx/pull/4078
