### ISSUE TITLE
InvalidCastException with two WCF Services in two different assemblies, loaded during runtime

### ISSUE THREAD

**Issue by X39** [dotnet/wcf#4552]
**Describe the bug**
I am currently facing issues that, to me at least, seem kinda random.
The situation is as follows: I have a system that may be extended, using "plugins", providing additional capabilities utilizing common interfaces. When i now have my two plugins (eBay and DHL) both with WCF services running, one of them always is failing with the following exception:
```
System.Exception: See Inner Exception
 ---> System.InvalidCastException: Unable to cast object of type 'generatedProxy_2' to type 'System.ServiceModel.Channels.ServiceChannelProxy'.
   at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannelInternal()
   at System.ServiceModel.ClientBase`1.get_Channel()
   at eBay.Soap.eBayAPIInterfaceClient.eBay.Soap.eBayAPIInterface.GetOrdersAsync(GetOrdersRequest request) in D:\Source\ExternProvider.Ebay\Connected Services\eBay.Soap\Reference.cs:line 122351
   at eBay.Soap.eBayAPIInterfaceClient.GetOrdersAsync(CustomSecurityHeaderType RequesterCredentials, GetOrdersRequestType GetOrdersRequest1) in D:\Source\ExternProvider.Ebay\Connected Services\eBay.Soap\Reference.cs:line 122359
   at ExternProvider.Ebay.SyncHandler.<>c__DisplayClass13_0.<<ImportOrdersTraditional>b__0>d.MoveNext() in D:\Source\ExternProvider.Ebay\SyncHandler.cs:line 188
--- End of stack trace from previous location ---
   at ExternProvider.Ebay.SyncHandler.SOAP[T](String method, Func`3 func) in D:\Source\ExternProvider.Ebay\SyncHandler.Utils.cs:line 551
   at ExternProvider.Ebay.SyncHandler.ImportOrdersTraditional(DateTime LastSyncDateTime, DateTime SyncToDateTime) in D:\Source\ExternProvider.Ebay\SyncHandler.cs:line 188
   at ExternProvider.Ebay.SyncHandler.Synchronize() in D:\Source\ExternProvider.Ebay\SyncHandler.cs:line 129
   at ExternProvider.Ebay.PluginMain.Sync(ExternAuthority externAuthority, List`1 packages, CancellationToken cancellationToken) in D:\Source\ExternProvider.Ebay\PluginMain.cs:line 78
   at Server.ExternAuthoritySyncWorker.ExecuteSafe() in D:\Source\SyncWorker.cs:line 162
   --- End of inner exception stack trace ---
   at Server.ExternAuthoritySyncWorker.ExecuteSafe() in D:\Source\SyncWorker.cs:line 207
```
While this already might seem strange, given that both plugins individual work perfectly fine, things do not stop here. The plugin, that was last build, always works, while the other does not. This might be explained away with weird sorting behavior in `System.IO.Directory.EnumerateDirectories` though.
The two assemblies do not interact in any way, the hosting application is also not receiving any of that generated code (both WCF services thus are fully contained inside of those assemblies, source code wise)

**Expected behavior**
Both WCF Services should work as if they where individually hosted

**Comment by X39** [comment]
Some new insight: I created a new assembly, put both service references in there and refer to them in the other two assemblies now. Issue remains.

**Comment by X39** [comment]
![image](https://user-images.githubusercontent.com/1886428/110316539-2a715c80-800b-11eb-9626-de1d07044064.png)
Stepping through the callchain, it seems like the actual issue is "assembly hell" that is causing issues in `System.Reflection.DispatchProxyGenerator`

```
+		Assembly	{System.Private.ServiceModel, Version=4.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	System.Reflection.Assembly {System.Reflection.RuntimeAssembly}
		EscapedCodeBase	"file:///C:/Git/wawi/SimplifySoft.Pecuniarius.Server/bin/Debug/net5.0/System.Private.ServiceModel.dll"	string

+		Assembly	{System.Private.ServiceModel, Version=4.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}	System.Reflection.Assembly {System.Reflection.RuntimeAssembly}
		EscapedCodeBase	"file:///C:/Users/Marco.Silipo/.nuget/packages/system.private.servicemodel/4.8.1/lib/netstandard2.0/System.Private.ServiceModel.dll"	string
```

**Comment by X39** [comment]
Solved the issue by solving the differences in plugins `csproj`:
```xml

  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.8.1" />
  </ItemGroup>
```
got changed to (what the other plugin already had)
```
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.*" />
  </ItemGroup>
```

I suspect my loading is faulty. This still should provide proper erroring (but is not directly related to this project)
