### ISSUE TITLE
System.InvalidOperationException: The required UserNameSecurityToken was not provided

### ISSUE THREAD

**Issue by dimalyshev** [dotnet/wcf#4562]
Configuring proxy with AuthenticationSchemes.Basic (see code) results in error in title: 
Related issue #4557
```
                var customBinding = new CustomBinding(result);

                var htbe = customBinding.Elements.Find<HttpTransportBindingElement>();
                htbe.ProxyAuthenticationScheme = AuthenticationSchemes.Basic; // Or whatever authentication mechanism your proxy server uses
                htbe.BypassProxyOnLocal = true;
                htbe.UseDefaultWebProxy = false;

                htbe.ProxyAddress = new Uri("http://user:pass@someproxy");
```

**Comment by dimalyshev** [comment]
Exception stack for #4562 here:

```
System.InvalidOperationException: The required UserNameSecurityToken was not provided.
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) in \wcf\System.Private.ServiceModel\src\Internals\System\Runtime\AsyncResult.cs:line 354
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result) in \wcf\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1909
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result) in wcf\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 806
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult) in \wcf\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by dimalyshev** [comment]
@mconnew why not to label this issue as bug ? 
Now there is no bypass to use proxy with Basic auth along with WCF libraries.

May be it'll speedup including patch into release?

**Comment by mconnew** [comment]
PR merge auto closed this issue so reopening. Marking it as a bug won't make any difference to how quickly this will get resolved. It's used for book keeping only, and we use ZenHub to manage issues that need working on so it's not really used to prioritize or organize.

**Comment by dimalyshev** [comment]
Thank a lot...

**Comment by HongGit** [comment]
Close as this issue is already resolved.
