### ISSUE TITLE
SocketException (10054) while using .NET 5 only when large request is sent

### ISSUE THREAD

**Issue by MichalLabuzz** [dotnet/wcf#4751]
Hi,

I am migrating my WCF client from .NET Framework 4.6.1 to .NET 5 and I am facing SocketException every time I am sending big requests (like 500KB). Below you can find exception, Server config, .NET Framework config and .NET 5 config.

**Exception:** 
```
System.ServiceModel.CommunicationException: Error while copying content to a stream.
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|177_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.ServiceModel.Channels.BufferedMessageContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendRequestContentWithExpect100ContinueAsync(HttpRequestMessage request, Task`1 allowExpect100ToContinueTask, HttpContentWriteStream stream, Timer expect100Timer, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location ---
   at EQ.SP.SOS.Adapter.Application.Services.AlertsService.GetUnreadAlertsAsync() in C:\Repozytoria\ShareholderPlatform\APP\EQ.SP.SOS.Adapter\EQ.SP.SOS.Adapter.Application\Services\AlertsService.cs:line 53
   at EQ.SP.SOS.Adapter.API.Controllers.AlertsController.GetUnreadAlerts() in C:\Repozytoria\ShareholderPlatform\APP\EQ.SP.SOS.Adapter\EQ.SP.SOS.Adapter.API\Controllers\AlertsController.cs:line 26
   at lambda_method537(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at EQ.SP.SOS.Adapter.API.Middleware.RequestTransferAgentMiddleware.Invoke(HttpContext context, ITransferAgentContext transferAgentContext) in C:\Repozytoria\ShareholderPlatform\APP\EQ.SP.SOS.Adapter\EQ.SP.SOS.Adapter.API\Middleware\RequestTransferAgentMiddleware.cs:line 22
   at EQ.SP.SOS.Adapter.API.Middleware.RequestMetaDataMiddleware.Invoke(HttpContext context, IMetaDataContext metadataContext, IConfiguration config) in C:\Repozytoria\ShareholderPlatform\APP\EQ.SP.SOS.Adapter\EQ.SP.SOS.Adapter.API\Middleware\RequestMetaDataMiddleware.cs:line 22
   at EQ.SP.SOS.Adapter.API.Middleware.RequestUserDataMiddleware.Invoke(HttpContext context, IUserDataContext userDataContext, IConfiguration config) in C:\Repozytoria\ShareholderPlatform\APP\EQ.SP.SOS.Adapter\EQ.SP.SOS.Adapter.API\Middleware\RequestUserMiddleware.cs:line 24
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Server config:**

```
<wsHttpBinding>
	<binding name="wsbinding" closeTimeout="10:01:00" openTimeout="10:01:00" receiveTimeout="10:10:00" sendTimeout="10:01:00" bypassProxyOnLocal="false" transactionFlow="false" hostNameComparisonMode="StrongWildcard" maxBufferPoolSize="2147483647" maxReceivedMessageSize="2147483647" messageEncoding="Text" textEncoding="utf-8" useDefaultWebProxy="false" allowCookies="false">
		<readerQuotas maxDepth="2147483647" maxStringContentLength="2147483647" maxArrayLength="2147483647" maxBytesPerRead="2147483647" maxNameTableCharCount="2147483647" />
		<security mode="Transport">
			<transport clientCredentialType="Certificate" />
		</security>
	</binding>
<wsHttpBinding>
```

**.NET Framework 4.6.1 client config:**
```
<wsHttpBinding>
	<binding name="wsbinding" closeTimeout="00:10:00" openTimeout="00:10:00" receiveTimeout="00:10:00" sendTimeout="00:10:00" bypassProxyOnLocal="false" transactionFlow="false" hostNameComparisonMode="StrongWildcard" maxBufferPoolSize="2147483647" maxReceivedMessageSize="2147483647" messageEncoding="Text" textEncoding="utf-8" useDefaultWebProxy="true" allowCookies="false">
		<readerQuotas maxDepth="2147483647" maxStringContentLength="2147483647" maxArrayLength="2147483647" maxBytesPerRead="2147483647" maxNameTableCharCount="2147483647" />
		<reliableSession ordered="true" inactivityTimeout="00:10:00" enabled="false" />
		<security mode="Transport">
			<transport clientCredentialType="Certificate" />
		</security>
	</binding>
</wsHttpBinding>
```
**.NET 5 client config:**
```
private static void RegisterWcfClient<TIService, TClient>(this IServiceCollection services, string baseUrl,
    string serviceName, string certName, string storeLocation)
    where TIService : class
    where TClient : ClientBase<TIService>, new()
{

    services.AddScoped(servicesCollection =>
    {

        var client = new TClient();
        var customBinding = new CustomBinding();

        var httpsBindingElement = new HttpsTransportBindingElement
        {
            AllowCookies = true,
            MaxBufferSize = int.MaxValue,
            MaxReceivedMessageSize = int.MaxValue,
            RequireClientCertificate = true
        };

        customBinding.Elements.Add(httpsBindingElement);

        client.Endpoint.Binding = customBinding;
        client.Endpoint.Address = new EndpointAddress($"{baseUrl}/{serviceName}");

        var storeLocationEnum = ToStoreLocationEnum(storeLocation);
        client.ClientCredentials.ClientCertificate.SetCertificate(storeLocationEnum, StoreName.My,
            X509FindType.FindBySubjectName, certName);

        return client;
    });

    services.AddScoped(servicesCollection =>
    {
        var factory = servicesCollection.GetService<TClient>()?.ChannelFactory;
        return factory.CreateChannel();
    });
}
```

**.NET 5 alternative config:**
```
private static void RegisterWcfClient<TIService, TClient>(this IServiceCollection services, string baseUrl,
    string serviceName, string certName, string storeLocation)
    where TIService : class
    where TClient : ClientBase<TIService>, new()
{
    services.AddScoped(servicesCollection =>
    {
        var client = new TClient();
        var customBinding = new WSHttpBinding(SecurityMode.Transport, false);


        customBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
        customBinding.ReaderQuotas.MaxDepth = 2147483647;
        customBinding.ReaderQuotas.MaxStringContentLength = 2147483647;
        customBinding.ReaderQuotas.MaxArrayLength = 2147483647;
        customBinding.ReaderQuotas.MaxBytesPerRead = 2147483647;
        customBinding.ReaderQuotas.MaxNameTableCharCount = 2147483647;

        customBinding.CloseTimeout = new TimeSpan(0, 10, 0);
        customBinding.OpenTimeout = new TimeSpan(0, 10, 0);
        customBinding.ReceiveTimeout = new TimeSpan(0, 10, 0);
        customBinding.SendTimeout = new TimeSpan(0, 10, 0);
        customBinding.BypassProxyOnLocal = false;
        customBinding.TransactionFlow = false;
        customBinding.MaxBufferPoolSize = 2147483647;
        customBinding.MaxReceivedMessageSize = 2147483647;
        customBinding.TextEncoding = Encoding.UTF8;
        customBinding.UseDefaultWebProxy = true;
        customBinding.AllowCookies = false;


        customBinding.ReliableSession.Ordered = true;
        customBinding.ReliableSession.InactivityTimeout = new TimeSpan(0, 10, 0);

        client.Endpoint.Binding = customBinding;
        client.Endpoint.Address = new EndpointAddress($"{baseUrl}/{serviceName}");


        var storeLocationEnum = ToStoreLocationEnum(storeLocation);
        client.ClientCredentials.ClientCertificate.SetCertificate(storeLocationEnum, StoreName.My,
            X509FindType.FindBySubjectName, certName);

        return client;
    });

    services.AddScoped(servicesCollection =>
    {
        var factory = servicesCollection.GetService<TClient>()?.ChannelFactory;
        return factory.CreateChannel();
    });
}
```

It works fine for small requests but for bigger requests I am getting mentioned exception. 
I created .NET 4.6.1 WCF client from the scratch basing on configuration I have in .NET 5 and it all works fine on .NET 4.6.1

I dont have an idea whats the root cause of this error. It seems like a server-side problem but then why is it working fine for .NET 4.6.1 client?

Any idea what could be wrong there?

**Comment by mconnew** [comment]
How long does it take from start of the request to the exception happening? Can you check the WCF event log in Event Viewer on the server side for any warnings or errors? The logs can be found in the Event Viewer path Applications and Services Logs -> Microsoft -> Windows -> Application Server-Applications. There might be a warning or error recorded explaining what the reason was for closing the connection on the server side.
