### ISSUE TITLE
SQL Server Reporting Services generation issue with 4.9.0

### ISSUE THREAD

**Issue by IgorMenshikov** [dotnet/wcf#4784]
**Describe the bug**
I have NET Core application. It generates some reports using SQL Server Reporting Services (ReportExecutionServiceSoapClient and ReportingService2010SoapClient). Things worked OK till we upgraded to 4.9.0.

Previous version 4.8.1 works OK.

Now it gives the following error:
```
System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'NTLM'.
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location ---
```

**To Reproduce**
It fails on any SSRS call like
```C#
RS.TrustedUserHeader? trustHandler = null;
var response = await rsService!.GetItemParametersAsync(trustHandler, "NAME", null, false, null, null).ConfigureAwait(false);
```

**Expected behavior**
A report to be generated

**Comment by mconnew** [comment]
I just took another look at your exception and I missed something the first time. The exception is saying you have configured your client to use anonymous authentication and the server is requesting NTLM authentication. This means your binding is misconfigured. Try setting binding.Security.Transport.ClientCredentialType to HttpClientCredentialType.Windows as that will then allow use of NTLM authentication. I don't know how it was working before as when you specify client credential type of None, WCF doesn't provide any credentials to HttpClient, not even default credentials.

**Comment by IgorMenshikov** [comment]
The code has been generated at times of NET 1 for SQL Server Reporting Service API by dotnet-svcutil ("ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf") and worked few years till NET 6.0 upgrade. Once I changed used libraries to 4.8.1 it started to work again:
```
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.8.1" />
  </ItemGroup>
```

Here is the part of the generated code
```C#
        public ReportExecutionServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportExecutionServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportExecutionServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ReportExecutionServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportExecutionServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/SSRS17/ReportExecution2005.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ReportExecutionServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/SSRS17/ReportExecution2005.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ReportExecutionServiceSoap,
            
            ReportExecutionServiceSoap12,
        }
```
This code has no any changes for few years already.

**Comment by IgorMenshikov** [comment]
> Did you upgrade the version of .NET at the same time?

Yes. Libraries have been upgraded together with NET Core 6.0 upgrade,

**Comment by Kramomat** [comment]
Hello,
I have a comparable issue, I am getting the following error by SQL Server Reporting Services, after migrating my code from Classic .Net Framework 4.8 to .Net Core 5.0 (using most recent WCF version 4.9.0):

`System.ServiceModel.Security.MessageSecurityException: "Die HTTP-Anforderung ist beim Clientauthentifizierungsschema "Ntlm" nicht autorisiert. Vom Server wurde der Authentifizierungsheader "NTLM" empfangen."`

I am setting the Authentication as HttpClientCredentialType.Ntlm on the basicHttpBinding.

Chaning the Binding from Ntlm to Windows leads to a different error message:

`System.ServiceModel.Security.MessageSecurityException: "Die HTTP-Anforderung ist beim Clientauthentifizierungsschema "Negotiate" nicht autorisiert. Vom Server wurde der Authentifizierungsheader "NTLM" empfangen."`

**Comment by mconnew** [comment]
@IgorMenshikov, I don't know how it's authenticating if that's really the code you are using as you aren't specifying an AuthenticationScheme on the HttpTransportBindingElement and it default to Anonymous, which matches your original error. This would mean HttpClientHandler should have UseDefaultCredentials set to false and Credentials set to null. There's only been one recent change made to handling credentials, and that's if you specify HttpTransportBindingElement.AuthenticationScheme to be WindowsIntegratedAuthentication, then we now add any explicitly provided credentials to a CredentialsCache for use with NTLM or Negotiate. If you don't specify credentials at all, any authentication scheme other than Anonymous will result in use of default credentials being set to true on the HttpClientHandler and should result in NTLM auth working. That's the only recent change to authentication that has happened on the WCF side.

@Kramomat, the difference in response is what I would expect to see when changing from Ntlm to Windows. This response means that the server has replied with a 401 Unauthorized response and is giving the client a challenge asking for credentials to be provided via the "WWW-Authenticate" header requesting NTLM credentials. For some reason credentials (or working credentials) aren't being provided. I suspect no credentials are being provided as I would expect a Forbidden response If you provide the wrong ones. If you don't provide any explicit credentials to ClientCredentials, it will tell HttpClientHandler to use the same credentials as was used to log on to the machine, otherwise it will use the ones you provide, but they are restricted to only be used for the host that you are communicating with. So if your service is available at "https://myservice.contoso.com/MyService.svc", then the credentials will be restricted to only use with "https://myservice.contoso.com/". Is there any chance redirection is happening? I.e. the server is returning a 3xx response initially? If you are using the default credentials, can you try setting the credentials explicitly on `ClientCredentials.Windows.ClientCredential` and see if that works?  
If none of this helps, can you capture a fiddler trace to get the headers sent and received? Please replace the base64 NTLM blob on any client sent authentication headers which start with `Authentication: NTLM ......` as that blob can be used as a surrogate for real credentials and you don't want to expose that. Just replace with `[removed]` or something similar. If in doubt, don't provide any seemingly random string of numbers and letters from HTTP headers as they often can act as credentials.

**Comment by Kramomat** [comment]
It took me some time to analyze everything.
So far I can see the behaviour when accessing reportservice2010.asmx:

1. Request sending the trusted UserHeader, resulting in http 401 requesting WWW-Authenticate: NTLM
2. In classic .Net a second request is being send with the Authorization: NTLM Header
Then the communication proceeds in classic .net
No redirection is done.

Using .net core the same request as #1 is sent (traced with fiddler):
`POST http://192.168.178.107/ReportServer/reportservice2010.asmx HTTP/1.1
Host: 192.168.178.107
Cache-Control: no-cache, max-age=0
SOAPAction: "http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer/FindItems"
Expect: 100-continue
Accept-Encoding: gzip, deflate
Content-Type: text/xml; charset=utf-8
Content-Length: 893

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:TrustedUserHeader xmlns:h="http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer" xmlns="http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><UserName>.\Mark</UserName></h:TrustedUserHeader></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><FindItems xmlns="http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer"><Folder>/Allgemein</Folder><BooleanOperator>And</BooleanOperator><SearchOptions/><SearchConditions><SearchCondition><Condition>Equals</Condition><Values><Value>Testbericht</Value></Values><Name>Name</Name></SearchCondition></SearchConditions></FindItems></s:Body></s:Envelope>`

Response:
`HTTP/1.1 401 Unauthorized
Content-Length: 0
WWW-Authenticate: NTLM
Date: Wed, 20 Apr 2022 11:23:34 GMT
Proxy-Support: Session-Based-Authentication`

So far, so good.
But then, instead sending the second request, the exception is being raised.

I am trying this code (rsService is a generated class ReportingService2010SoapClient by Microsoft.Tools.ServiceModel.Svcutil version 2.0.3):
`            using (ReportingService2010.ReportingService2010SoapClient rsService = new ReportingService2010.ReportingService2010SoapClient(basicHttpBinding, new EndpointAddress(serviceUrl)))
                ReportingService2010.TrustedUserHeader trusteduserHeader;
                rsService.ClientCredentials.Windows.ClientCredential = clientCredentials;
                rsService.ClientCredentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;
                rsService.ClientCredentials.UserName.UserName = UserName;
                rsService.ClientCredentials.UserName.Password = UserPassword;
            trusteduserHeader = new ReportingService2010.TrustedUserHeader();
            trusteduserHeader.UserName = clientCredentials.UserName;
            
                            ReportingService2010.SearchCondition condition = new ReportingService2010.SearchCondition();
                condition.Condition = ReportingService2010.ConditionEnum.Equals;
                condition.ConditionSpecified = true;
                condition.Name = "Name";
                condition.Values = new string[] { ReportName };
                ReportingService2010.SearchCondition[] conditions = new ReportingService2010.SearchCondition[1];
                conditions[0] = condition;
                ReportingService2010.CatalogItem[] foundItems = null;
                rsService.FindItems(trusteduserHeader
                    , "/" + ReportFolder.TrimStart('/').TrimEnd('/')
                    , ReportingService2010.BooleanOperatorEnum.And
                    , new ReportingService2010.Property[0]
                    , conditions
                    , out foundItems);`

The last line (FindItems Method) is resulting in this. It also happens, when I try any other method of the SOAP service class.

**Comment by lawrentiy** [comment]
The same issue.
Client: NET6 C#, System.ServiceModel 4.9.0
Server: WCF NET4.5 C#

Downgrade to 4.8.1 helps to solve it.
Will try to remove that WCF services. RIP

**Comment by mconnew** [comment]
@Kramomat, sorry I missed your reply. It's all pointing to the client credential type being wrong. If your binding looks like the code snippet provided by @IgorMenshikov, then there's 2 changes that need to happen. First, the constructor of BasicHttpBinding needs to be passed `BasicHttpSecurityMode.Transport`. Second, `BasicHttpBinding.Security.Transport.ClientCredentialType` needs to be set to `HttpClientCredentialType.Ntlm`. As configured in that binding code snippet, HttpClientHandler won't respond to any authentication challenges and won't send any credentials.
