### ISSUE TITLE
Cannot find a token authenticator for the 'System.IdentityModel.Tokens.X509SecurityToken' token type

### ISSUE THREAD

**Issue by OleksandrBorovenskyi** [dotnet/wcf#5170]
Hi,

I am trying to integrate with an external web service with generated proxy (Connected Services), using message security.
I know message security is not supported currently and you are blocked.
Therefore I have a solution with custom `MessageHeader`, `IEndpointBehavior`, and `IClientMessageInspector`.

As a result, I can successfully authorize.
I can say it because looking at the response from the external web service in Fiddler I see the correct (expected) XML response.

But the problem is that generated proxy client throws an exception:
`System.ServiceModel.Security.MessageSecurityException : Cannot find a token authenticator for the 'System.IdentityModel.Tokens.X509SecurityToken' token type. Tokens of that type cannot be accepted according to current security settings.`

Looks like regardless of the message security is not supported there is some check (validation) of the token sent in response.

Could you please help to find a solution?

Maybe I need just one of the following:
1) disable this token check (if it is not critical for security)
2) create some custom check (maybe smth dummy) and put it in the correct place
3) set up generated clients with existing properties in .NET Core (.NET 6)
But currently, I have no clue how to do any of this.

**Comment by mconnew** [comment]
What's the call stack for the exception?

**Comment by OleksandrBorovenskyi** [comment]
Call stack:
`
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location ---
   at Service.UnitTests.Services.ServiceTests.<Integration_Cancel_Client>d__11.MoveNext() in C:\Repositories\Service\Tests\UnitTests\Services\ServiceTests.cs:line 169
`

I have modified 2 last lines because of sensitive information about the project I am working on.
But it should not affect understanding of the issue.



Also here is a response (sensitive info is obfuscated) from the web service I am trying to connect with:
`
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Header xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
		<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
			<wsu:Timestamp wsu:Id="Timestamp-2d576bd4-76f6-4e29-8fc3-859aa3b208d9" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
				<wsu:Created>2023-05-29T15:04:23Z</wsu:Created>
				<wsu:Expires>2023-05-29T15:09:23Z</wsu:Expires>
			</wsu:Timestamp>
			<wsse:BinarySecurityToken ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" wsu:Id="SecurityToken-e01e4d82-49ce-45c2-842c-e885f88e4ed9" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">{{ Token b64 bytes come here }}</wsse:BinarySecurityToken>
			<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
				<SignedInfo>
					<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
					<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
					<Reference URI="#Id-3e397e8e-a545-466b-9403-44b1b5c8db29">
						<Transforms>
							<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</Transforms>
						<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
						<DigestValue>{{ value comes here }}</DigestValue>
					</Reference>
					<Reference URI="#Timestamp-2d576bd4-76f6-4e29-8fc3-859aa3b208d9">
						<Transforms>
							<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						</Transforms>
						<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
						<DigestValue>{{ value comes here }}=</DigestValue>
					</Reference>
				</SignedInfo>
				<SignatureValue>{{ b64 bytes come here }}</SignatureValue>
				<KeyInfo>
					<wsse:SecurityTokenReference>
						<wsse:Reference URI="#SecurityToken-e01e4d82-49ce-45c2-842c-e885f88e4ed9" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>
					</wsse:SecurityTokenReference>
				</KeyInfo>
			</Signature>
		</wsse:Security>
	</soapenv:Header>
	<s:Body wsu:Id="Id-3e397e8e-a545-466b-9403-44b1b5c8db29" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
		<s:Fault>
			<faultcode>s:Client</faultcode>
			<faultstring xml:lang="{{ culture code }}">Missing from or to date, the reference date</faultstring>
		</s:Fault>
	</s:Body>
</s:Envelope>
`


Let me know if any information from me might help:)
Thanks

**Comment by OleksandrBorovenskyi** [comment]
I solved the issue by changing
`binding.Security.Mode = BasicHttpsSecurityMode.Transport;`
Previously it was `TransportWithMessageCredential`.

Here is the binding I am using:
```
private BasicHttpsBinding CreateHttpsBinding()
    {
        var binding = new BasicHttpsBinding();

        binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
        binding.Security.Mode = BasicHttpsSecurityMode.Transport;
        
        return binding;
    }
```
And then I specify the certificate:
```
client.ClientCredentials.ClientCertificate.Certificate = cert;
```

But I still do not understand why.
Because I actually send the client certificate (`<wsse:BinarySecurityToken />`) along with credentials (`<wsse:UsernameToken>`) as security headers to the server.
Therefore `TransportWithMessageCredential` seemed suitable, but actually not.


Also, I found out that such a binding and no need to set the certificate anymore also works well:
```
  private BasicHttpsBinding CreateHttpsBinding()
    {
        var binding = new BasicHttpsBinding();
        binding.Security.Mode = BasicHttpsSecurityMode.Transport; 

        return binding;
    }
```

----

@mconnew, 
Could you please confirm whether I understand correctly 
1) what certificate is used for HTTPS connection if I do not specify any
GIVEN: HTTPS binding (`BasicHttpsBinding`) 
    AND `binding.Security.Mode = BasicHttpsSecurityMode.Transport;`
WHEN: I do not specify a particular certificate via `client.ClientCredentials.ClientCertificate.Certificate = cert;`
THEN: Some default certificate of my machine (laptop) is taken for establishing an HTTPS connection?

2) why the second version of the binding works well as the first one:
GIVEN: HTTPS binding (`BasicHttpsBinding`) 
    AND `binding.Security.Mode = BasicHttpsSecurityMode.Transport;`
    AND I send the required security header Username 
    AND I send the required security header BinarySecurityToken with a special certificate
WHEN: I get a successfully authorized response (and without exception on behalf of generated proxy client)
THEN: we can assume the server is configured with `binding.Security.Mode = BasicHttpsSecurityMode.TransportWithMessageCredential;`
             so the server does not require a certificate on the Transport level but rather on the Message level.
And the only difference between the 2 versions of the binding is which certificate is used for establishing an HTTPS connection.
And both bindings are equally secured
