### ISSUE TITLE
TcpClientCredentialType_Certificate_CustomValidator_EchoString test fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#523]
--------------------------------
  Running Test: Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString
  Caught Unexpected exception:System.NotSupportedException: UnsupportedSecuritySetting, Transport.ClientCredentialType, Certificate
     at System.ServiceModel.NetTcpBinding.CheckSettings() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\NetTcpBinding.cs:line 167
     at System.ServiceModel.NetTcpBinding.CreateBindingElements() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\NetTcpBinding.cs:line 174
     at System.ServiceModel.Channels.Binding.EnsureInvariants(String contractName) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Binding.cs:line 218
     at System.ServiceModel.Description.ServiceEndpoint.EnsureInvariants() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Description\ServiceEndpoint.cs:line 195
     at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory($ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose, $ChannelRequirements requirements) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs:line 111
     at System.ServiceModel.ChannelFactory.OnOpening() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs:line 376
     at System.ServiceModel.Channels.CommunicationObject.d__71.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 343

**Comment by zhenlan** [comment]
This is not working because we have not upgrading WinRT stream with SSL.

**Comment by StephenBonikowsky** [comment]
Closing and using #834 for this failure.
