### ISSUE TITLE
IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException test fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#525]
--------------------------------
  Running Test: IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException
  Assert.True:Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.PlatformNotSupportedException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.PlatformNotSupportedException' was thrown.
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.Throws(Action action, Object[] CS$0$0000) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException($ICommunicationObject[] CS$0$0000) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\IdentityTests.cs:line 57
     at EntryPointMain.b__11() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 30
     at System.Func$1.InvokeOpenStaticThunk()
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by StephenBonikowsky** [comment]
Closing and using #833 for this failure.
