### ISSUE TITLE
WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed test hangs in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#526]
May be known issue with WebSockets hang, but confirming it happens in NET Native too:
  
--------------------------------
  Running Test: WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed

--------------------------------------------------------------------------------

TEXT_EXPECTED_RETURN_CODE = 0
TEXT_ACTUAL_RETURN_CODE = -1 (0xffffffff)

**Comment by roncain** [comment]
Duplicated this today (12/1/2015).  Because this test hangs and is the first one run, it is unclear what other websockets tests would have passed or failed.

**Comment by hongdai** [comment]
It hangs for me on the latest bit as well.

 Running Test: WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed
  Assert.True:Test case timeout was reached while waiting for the stream response from the Service. Timeout was: 00:20:00
  Xunit.AssertTestException: Assert.True: Test case timeout was reached while waiting for the stream response from the Service. Timeout was: 00:20:00
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.True(Boolean condition, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed($ICommunicationObject[] CS$0$0000) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Extensibility\WebSockets\WebSocketTests.cs:line 131
     at EntryPointMain.b__1() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Extensibility\WebSockets\Extensibility.WebSockets.Tests.main.cs:line 14
     at Windows.UI.Core.DispatchedHandler.InvokeOpenStaticThunk()
     at System.ServiceModel.Channels.ChainedEndHandler.Invoke(IAsyncResult result)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by StephenBonikowsky** [comment]
On my runs today I got all the WebSocket tests to run and there are three that fail for this issue...
WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed
WebSocketTests.WebSocket_Https_Duplex_BinaryStreamed
WebSocketTests.WebSocket_Https_Duplex_TextStreamed

**Comment by StephenBonikowsky** [comment]
Adding ActiveIssues for these tests in NET Native.

**Comment by zhenlan** [comment]
The fix of this issue needs windows runtime websocket API changes to support true streaming for UWP. Move this issue to future as it is just tracking the future change in Windows.

**Comment by roncain** [comment]
Confirmed all tests mentioned above continue to timeout using the new (non-ToF) UWP test environment.

@zhenlan or @mconnew -- do we know which API changes are needed for this?  Is there a matching CoreFx issue we can reference?

**Comment by zhenlan** [comment]
This is pending WebSocket work from Networking team.

**Comment by mconnew** [comment]
The networking team have implemented partial receive for UWP, but partial send hasn't been implemented yet. Without partial send, our tests still fail.
