### ISSUE TITLE
Rampart Interoperability: MessageSecurityException

### ISSUE THREAD

**Issue by brian-mouton-at-fis** [dotnet/wcf#5273]
**Describe the bug**
WCF code is not handling security headers in SOAP responses.

**To Reproduce**
I have a Java based web application running axis2 and rampart. I am attempting to upgrade it and in the process it appears to have added a security header. The header is causing a problem in .NET and I have already made attempts to remove the header.

```xml
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope xmlns:soapenv= "http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header>
        <wsse:Security xmlns:wsse= "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu= "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soapenv:mustUnderstand= "1">
            <wsu:Timestamp wsu:Id= "TS-CDB87B833148B9045F169349683637320">
                <wsu:Created>2023-08-31T15:47:16.373Z</wsu:Created>
                <wsu:Expires>2023-08-31T15:52:16.373Z</wsu:Expires>
            </wsu:Timestamp>
        </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>
        <!-- Redacted -->
    </soapenv:Body>
</soapenv:Envelope>

```
I apologize for redacting some of the content.

The version of axis2 is 1.7.6 with the rampart module for (WS-Security) version 1.7.1.

Unfortunately I can't provide sample code yet.

**Expected behavior**
I expect the response to be parsed and returned to the calling code.

Instead what I am getting is <b>MessageSecurityException: Message security verification failed.</b>.

**Screenshots**
![image](https://github.com/dotnet/wcf/assets/89533240/7426d6e0-edfb-4e19-99b6-578dcd0e9ddf)

**Additional context**
Call stack
```
Unhandled exception. System.ServiceModel.Security.MessageSecurityException: Message security verification failed.
 ---> System.ServiceModel.MessageHeaderException: Multiple headers with name 'Security' and namespace 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and role '' found.
   at System.ServiceModel.Channels.MessageHeaders.FindHeader(String name, String ns, String[] actors)
   at System.ServiceModel.Security.SecurityVersion.TryCreateReceiveSecurityHeader(Message message, String actor, SecurityStandardsManager standardsManager, SecurityAlgorithmSuite algorithmSuite, MessageDirection direction)
   at System.ServiceModel.Security.SecurityStandardsManager.TryCreateReceiveSecurityHeader(Message message, String actor, SecurityAlgorithmSuite algorithmSuite, MessageDirection direction)
   at System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessageCore(Message& message, TimeSpan timeout)
   at System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessage(Message& message, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location ---
```

I've attempted to debug the WCF source and found the point where things fail:
![image](https://github.com/dotnet/wcf/assets/89533240/5bf40c32-fbc2-4a05-bbef-eb8f7bf543d8)

The data structure for the Message looks wrong but I am not an expert at this source so I can't say for sure.
This is what the private variable looks like. Notice the _headers array has 4 items in it with the first two identical.
![image](https://github.com/dotnet/wcf/assets/89533240/11c22bf6-be31-4f92-97e7-8ed34d8b90cd)

Meanwhile when I look at the results view of the object, it only shows 2 headers.
![image](https://github.com/dotnet/wcf/assets/89533240/c2282ad9-f8c4-4d64-8c93-cf0e6c2e0a8b)

I suspect that there is a problem parsing the headers into this object but I am having trouble finding where this logic exists let alone understanding what is going wrong.

**Comment by brian-mouton-at-fis** [comment]
Looks like a custom binding was the root of the problem. The custom binding was adding the additional security header. I would like to say this Custom Binding code was copied from a sample online on how to use WS-Security in .NET but I can't find it.
