### ISSUE TITLE
Https_ClientCredentialTypeTests.DigestAuthentication_RoundTrips_Echo failed

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#529]
Note that this test needs to run on a domain machine. 

The failure message:
Additional information: The HTTP request is unauthorized with client authentication scheme 'Digest'. The authentication header received from the server was 'Digest qop="auth",algorithm=MD5-sess,nonce="+Upgraded+v1462d90d70fbc29277bf5589bf8263f9004c4ca2d9120d10168c85f1ea8d5f69a0bae2604ab48ad88326108cf562747b46106fd544acf3a20",charset=utf-8,realm="Digest"'.

Call stack:
at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
	   at System.ServiceModel.Channels.HttpResponseMessageHelper.<ParseIncomingResponse>d__7.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<ReceiveReplyAsync>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__34.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__33.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
	   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
	   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
	   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
	   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
	   at generatedProxy_1.Echo(String )
	   at ScenarioTestHelpers.RunBasicEchoTest(Binding binding, String address, String variation, StringBuilder errorBuilder, Action`1 factorySettings) in c:\users\hongdai\documents\visual studio 2015\Projects\rc1app\src\rc1app\ScenarioTestHelpers.cs:line 64

**Comment by hongdai** [comment]
This is a test issue. The test needs to be updated to have a domain user name and pwd before running it.
