### ISSUE TITLE
WCF support for WebAssembly

### ISSUE THREAD

**Issue by denisbredikhin** [dotnet/wcf#5335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Hello, We have old application based on .NET Framework + WCF (recently migrated to CoreWCF) on backend. 

We are developing new frontend based on Blazor Server. There are quite some reasons for us to migrate to Blazor WebAssembly, but the absence of support of WCF is blocking us from this.

I've found some questions related to this topic several years ago, but what is changed since that time is that there is now nice CoreWCF project, which is well maintained and can be used to develop moden .NET 6-8 WCF-based solutions.

Please consider adding support of WCF client side to Blazor WebAssembly.

**Comment by Dennis-Petrov** [comment]
It looks like the main obstacle is the lack of ability to inject Blazor's `HttpClient` into request channel:

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_AutomaticDecompression(DecompressionMethods value)
   at System.Net.Http.HttpClientHandler.set_AutomaticDecompression(DecompressionMethods value)
   at System.ServiceModel.Channels.HttpChannelFactory`1.<GetHttpClientAsync>d__54[[System.ServiceModel.Channels.IRequestChannel, System.ServiceModel.Primitives, Version=8.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
```

Is there any other pitfalls?
