### ISSUE TITLE
ServiceContract with C#11 static virtual/abstract members crashes with TypeLoadException in ProxyBuilder

### ISSUE THREAD

**Issue by Rans4ckeR** [dotnet/wcf#5551]
**Describe the bug**
Using [Static abstract members in interfaces](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/static-abstracts-in-interfaces) crashes at runtime when invoking an operation.

**To Reproduce**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="8.0.0" />
  </ItemGroup>
</Project>
```

```C#
using System.ServiceModel;

await new Client().SomeOperationAsync();

[ServiceContract]
file interface IContract
{
    static virtual string SomeProperty => string.Empty;

    [OperationContract]
    Task SomeOperationAsync();
}

file sealed class Client() : ClientBase<IContract>(new BasicHttpBinding(), new(new Uri("http://localhost"))), IContract
{
    public Task SomeOperationAsync() => Channel.SomeOperationAsync();
}
```

```
System.TypeLoadException
  HResult=0x80131522
  Message=Signature of the body and declaration in a method implementation do not match.  Type: 'generatedProxy_1'.  Assembly: 'ProxyBuilder, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeInfoImpl()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType()
   at System.Reflection.DispatchProxyGenerator.ProxyAssembly.GenerateProxyType(Type baseType, Type interfaceType, String interfaceParameter, String proxyParameter)
   at System.Reflection.DispatchProxyGenerator.ProxyAssembly.GetProxyType(Type baseType, Type interfaceType, String interfaceParameter, String proxyParameter)
   at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type baseType, Type interfaceType, String interfaceParameter, String proxyParameter)
   at System.Reflection.DispatchProxy.Create[T,TProxy]()
   at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannelInternal()
   at System.ServiceModel.ClientBase`1.get_Channel()
   at <Program>FADE159A2B5D427B87AB7F31CE3E0D8F842B338E0D21DDA0E0CF708583A04D027__Client.SomeOperationAsync() in Program.cs:line 16
   at Program.<<Main>$>d__0.MoveNext() in Program.cs:line 3
```

**Comment by mconnew** [comment]
When you have a service contract interface, WCF provides a proxy which implements the interface, with the implementation of each of the member methods making a SOAP call. When you create two separate channels from the channel factory, they are distinctly separate instances. If you are using a sessionful binding (eg NetTcpBinding with transport sessions, or something like WSHttpBinding with sessions enabled), each channel has its own session. What do you expect the behavior to be with a static abstract interface method? As it's static, it doesn't have a channel to send any requests over.  

I suspect you are trying to attach some extra behavior to the generated client and not have that static method send anything? The difficulty is that DispatchProxy (the library we use to generate the proxy) doesn't have support for this. But I think you can still achieve what you are wanting. The generic interface type specified in the base type declaration for ClientBase\<TChannel\> can't have an abstract method, but you can still have your client type have it. You can do something like this:
```c#
[ServiceContract]
file interface IContract
{
    [OperationContract]
    Task SomeOperationAsync();
}

file interface IContractExt : IContract
{
    static virtual string SomeProperty => string.Empty;
}

file sealed class Client() : ClientBase<IContract>(new BasicHttpBinding(), new(new Uri("http://localhost"))), IContractExt
{
    public Task SomeOperationAsync() => Channel.SomeOperationAsync();
}
```
With this, you still have a single interface `IContractExt` that you can pass around and not have consumers worry about casting to a different interface to use SomeProperty. If your intention is to use this with a client generated by dotnet-svcutil, there's a useful trick you can use. The types generated by dotnet-svcutil are partial, so you can add your own source file redeclaring the client class and adding the extra interface. In your own code you would also declare the extended interface derived from the generated one adding your static property.  

Does this help you achieve what you are wanting to do? If not, can you explain your use case a bit more.

**Comment by mconnew** [comment]
As this is a super niche application, unless you are willing to submit a PR to enable this in DispatchProxy, there's a low chance of getting support for it in a reasonable time frame. That might not be a big task as it might simply require recognizing it's a virtual member (you would want to throw if it's abstract) and ignore it. From the WCF side, I don't think we'd need to do anything special. Even if we don't specify we only want instance members on the interface when reflecting over it, we look for the OperationContract attribute and ignore it if absent. 

As long as the urls are constant strings, you could achieve something similar using your own custom attribute and an extension method which gets the custom attribute data from the interface type and retrieves the value. If you can wait until c#13 which is in development, they are adding support for extension properties so you could still have a property which gets the data from an attribute.

**Comment by Rans4ckeR** [comment]
> As this is a super niche application, unless you are willing to submit a PR to enable this in DispatchProxy, there's a low chance of getting support for it in a reasonable time frame. That might not be a big task as it might simply require recognizing it's a virtual member (you would want to throw if it's abstract) and ignore it. From the WCF side, I don't think we'd need to do anything special. Even if we don't specify we only want instance members on the interface when reflecting over it, we look for the OperationContract attribute and ignore it if absent.

I submitted a PR for dotnet/runtime/issues/102716, feel free to close this issue.
