### ISSUE TITLE
ClientBaseOfT_Sync_RoundTrip_Call_Using_NetTcpTransport fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#558]
Running Test: ClientBaseTests.ClientBaseOfT_Sync_RoundTrip_Call_Using_NetTcpTransport
  Caught Unexpected exception:System.IO.IOException: An existing connection was forcibly closed by the remote host.
  
  An existing connection was forcibly closed by the remote host.
   ---> System.Exception: An existing connection was forcibly closed by the remote host.
  
  An existing connection was forcibly closed by the remote host.
  
     Exception_EndOfInnerExceptionStack
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 60
     at System.IO.StreamOperationAsyncResult.ThrowWithIOExceptionDispatchInfo(Exception e) in E:\ProjectK\src\NDP\FxCore\src\System.Runtime.WindowsRuntime\System\IO\StreamOperationAsyncResult.NETNative.cs:line 13
     at System.IO.StreamOperationAsyncResult.ProcessCompletedOperation() in E:\ProjectK\src\NDP\FxCore\src\System.Runtime.WindowsRuntime\System\IO\StreamOperationAsyncResult.cs:line 231
     at System.IO.WinRtToNetFxStreamAdapter.EndRead(IAsyncResult asyncResult) in E:\ProjectK\src\NDP\FxCore\src\System.Runtime.WindowsRuntime\System\IO\WinRtToNetFxStreamAdapter.cs:line 509
     at System.IO.WinRtToNetFxStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count) in E:\ProjectK\src\NDP\FxCore\src\System.Runtime.WindowsRuntime\System\IO\WinRtToNetFxStreamAdapter.cs:line 564
     at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count) in E:\ProjectK\src\NDP\FxCore\src\System.Runtime.WindowsRuntime\System\IO\BufferedStream.cs:line 555
     at System.ServiceModel.Channels.RTSocketConnection.ReadCore$catch$2() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RTSocketConnection.cs:line 430
     at System.ServiceModel.Channels.SocketConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SocketConnection.cs:line 324
     at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Connection.cs:line 99
     at System.ServiceModel.Channels.SessionConnectionReader.Receive(TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SessionConnectionReader.cs:line 212
     at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SynchronizedMessageSource.cs:line 113
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.Receive(TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TransportDuplexSessionChannel.cs:line 100
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceive(TimeSpan timeout, $Message& message) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TransportDuplexSessionChannel.cs:line 195
     at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\DuplexChannelBinder.cs:line 484
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 765
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 139
     at __InterfaceProxies.ServiceChannelProxy_IWcfServiceGenerated.global.IWcfServiceGenerated_P.Echo(String message) in c:\Users\roncain\AppData\Local\Temp\Ilc612745778\Client.ClientBase.Tests.ITFProxy.g.cs:line 332
     at ClientBaseTests.ClientBaseOfT_Sync_RoundTrip_Call_Using_NetTcpTransport($BindingElement[] CS$0$0000) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Client\ClientBase\ClientBaseTests.cs:line 165
     at EntryPointMain.b__4() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ClientBase\Client.ClientBase.Tests.main.cs:line 17
     at System.Func$1.InvokeOpenStaticThunk()
     at System.ServiceModel.Channels.ChainedEndHandler.Invoke(IAsyncResult result)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Boolean CS$1$0000) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------

**Comment by roncain** [comment]
Closing because did not repro after a fresh sync.
