### ISSUE TITLE
DigestAuthentication_Echo_RoundTrips_String_No_Domain fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#564]
I believe this issue is known due to inability to rewind stream in NET Native.  This issue is to track fixing it in NET Native.
  --------------------------------
  Running Test: Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain
  Caught Unexpected exception:System.ServiceModel.CommunicationException: net_http_client_execution_error ---> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.NotSupportedException: NotSupported_CloningNotSupported, GetInputStreamAt
     at System.IO.NetFxToWinRtStreamAdapter.GetInputStreamAt(UInt64 position) in E:\ProjectK\src\NDP\FxCore\src\System.Runtime.WindowsRuntime\System\IO\NetFxToWinRtStreamAdapter.cs:line 455
     at Windows.Storage.Streams.IRandomAccessStream__Impl.Vtbl.GetInputStreamAt__STUB(IntPtr pComThis, UInt64 unsafe_position, $Vtbl*** unsafe_stream__retval, Int32 CS$1$0000) in c:\Users\roncain\AppData\Local\Temp\Ilc1835401177\Security.TransportSecurity.Tests.Interop\ImplTypes.g.cs:line 53999
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
     at System.Net.Http.HttpHandlerToFilter.d__3.MoveNext() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpHandlerToFilter.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
     at System.Net.Http.HttpClientHandler.d__62.MoveNext() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpClientHandler.cs:line 16707566
     Exception_EndOfInnerExceptionStack
     at System.Net.Http.HttpClientHandler.d__62.MoveNext$catch$1() in E:\ProjectK\src\NDP\FxCore\src\System.Net.Http\NETNative\System\Net\HttpClientHandler.cs:line 427
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
     at System.Runtime.CompilerServices.TaskAwaiter$1.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 320
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__13.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 16707566
     Exception_EndOfInnerExceptionStack
     at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException($HttpRequestException requestException, $HttpRequestMessage request, $HttpAbortReason abortReason) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelHelpers.cs:line 116
     at System.ServiceModel.Channels.HttpChannelFactory$1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.d__13.MoveNext$catch$1() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 955
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
     at System.ServiceModel.Channels.RequestChannel.d__34.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 268
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
     at System.ServiceModel.Channels.RequestChannel.d__33.MoveNext() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 16707566
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
     at System.ServiceModel.Channels.RequestChannel.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 241
     at System.ServiceModel.Dispatcher.RequestChannelBinder.Request($Message message, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\RequestChannelBinder.cs:line 105
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, $ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 765
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService($MethodCall methodCall, $ProxyOperationRuntime operation) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke($MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 139
     at __InterfaceProxies.ServiceChannelProxy_IWcfService.global.IWcfService_P.Echo(String message) in c:\Users\roncain\AppData\Local\Temp\Ilc1835401177\Security.TransportSecurity.Tests.ITFProxy.g.cs:line 65
     at Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain($ICommunicationObject[] CS$0$0000) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Http\ClientCredentialTypeTests.cs:line 32
     at EntryPointMain.b__b() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 24
     at Windows.UI.Core.DispatchedHandler.InvokeOpenStaticThunk()
     at System.AsyncCallback.Invoke(IAsyncResult ar)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Boolean CS$1$0000) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------

**Comment by zhenlan** [comment]
May related to #327

**Comment by mconnew** [comment]
I made a fix to the NetNative HttpClient which fixes this issue.
