### ISSUE TITLE
TypeInitializationException when upgrading from 8.0.0 to 8.1.0

### ISSUE THREAD

**Issue by rdeherder** [dotnet/wcf#5700]
**Describe the bug**
Using dotnet 8, after upgrading from 8.0.0 to 8.1.0 I get a TypeInitializationException:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception.
  Source=System.IdentityModel.Tokens.Jwt
  StackTrace:
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.get_Serializer()
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
   at System.IdentityModel.Tokens.Jwt.JwtHeader.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection, String tokenType, IDictionary`2 additionalHeaderClaims, IDictionary`2 additionalInnerHeaderClaims)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
   at Gigantisch.Services.LegacyAuthenticationService.<LogIn>d__4.MoveNext() in C:\Projects\GigantischV3\Gigantisch.Services\LegacyAuthenticationService.cs:line 72

  This exception was originally thrown at this call stack:

Inner Exception 1:
TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=8.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

when calling the JwtSecurityTokenHandler.CreateToken();

**To Reproduce**
Create an Asp.NET 8 project targeting .net 8.
Add System.ServiceModel.Federation package reference.
Add code that tries to create a token from a SecurityTokenDescriptor instance that only has Subject, Expires and SigningCredentials properties filled in.

**Expected behavior**
The JwtSecurityTokenHandler returns a token when calling CreateToken().

**Comment by mconnew** [comment]
The package Microsoft.IdentityModel.Protocols.WsTrust hasn't had any new releases since 6.8.0, which is over 2 years ago. Due to some transitive dependencies of that package having vulnerable versions, we added the Microsoft.IdentityModel.* dependencies of WsTrust to Federation to get up to date. This included Microsoft.IdentityModel.Tokens which we updated to 8.2.0. Looking at their source code, JsonConvert was an internal copy of some Newtonsoft implementation that they shipped inside Microsoft.IdentityModel.Tokens in an earlier version. They have configured M.IM.Tokens to have internals visible to System.IdentityModel.Tokens.Jwt which looks like it was using it. Later versions of System.IdentityModel.Tokens.Jwt use the new System.Text.Json serializer instead so they removed the JsonConvert implementation from Tokens. Basically the team that owns System.IdentityModel.Tokens.Jwt and System.IdentityModel.Tokens made a backwards incompatible breaking change at some point.  

Things should work if you add a reference to System.IdentityModel.Tokens.Jwt which is 8.2.0 or later.

**Comment by rdeherder** [comment]
> Things should work if you add a reference to System.IdentityModel.Tokens.Jwt which is 8.2.0 or later.

I switched from the default System.IdentityModel.Tokens.Jwt to its nuget package version and it works. Tested from version 7.1.2 to 8.3.0. Thanks.

**Comment by samhanes** [comment]
I'm confused as to why this was closed. It looks as though System.ServiceModel.Federation >= 8.1.0 has a hidden dependency to System.IdentityModel.Tokens.Jwt >= 8.2.0. Shouldn't that dependency be made explicit?
