### ISSUE TITLE
SameBinding_SecurityModeTransport_ClientCredentialTypeCertificate_EchoString fails CoreCLR ToF

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#580]
Running Test: Tcp_ClientCredentialTypeTests.SameBinding_SecurityModeTransport_ClientCredentialTypeCertificate_EchoString
  Caught Unexpected exception:System.NotSupportedException: The requested security protocol is not supported.
     at System.Net.SecurityProtocol.ThrowOnNotAllowed(SslProtocols protocols, Boolean allowNone) in E:\ProjectK\src\ndp\fxcore\Open\src\Common\src\System\Net\SecurityProtocol.cs:line 21
     at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Net.Security\src\System\Net\SecureProtocols\SslStream.cs:line 201
     at System.ServiceModel.Channels.SslStreamSecurityUpgradeInitiator.d__19.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SslStreamSecurityUpgradeProvider.cs:line 602
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.d__14.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\StreamSecurityUpgradeInitiatorBase.cs:line 91
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.ServiceModel.Channels.ConnectionUpgradeHelper.d__3.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs:line 581
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 124
     at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.d__10.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs:line 256
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.ConnectionPoolHelper.d__15.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ConnectionPoolHelper.cs:line 113
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.d__12.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs:line 319
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.CommunicationObject.d__71.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 348
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.ServiceChannel.d__149.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1351
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.CommunicationObject.d__71.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 348
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.CommunicationObject.d__70.MoveNext() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 323
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 172
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\ProjectK\src\NDP\clr\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 152
     at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1976
     at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 2043
     at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 502
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 747
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 371
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 136
  --- End of stack trace from previous location where exception was thrown ---
     at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Reflection.DispatchProxy\src\System\Reflection\DispatchProxyGenerator.cs:line 161
     at generatedProxy_2.Echo(String )
     at Tcp_ClientCredentialTypeTests.SameBinding_SecurityModeTransport_ClientCredentialTypeCertificate_EchoString() in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\ClientCredentialTypeTests.cs:line 142
     at EntryPointMain.b__f() in e:\ProjectK\src\QA\ToF\PK\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests\Security.TransportSecurity.Tests.main.cs:line 28
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest(TestInfo t) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------

**Comment by iamjasonp** [comment]
Closed via #599
