### ISSUE TITLE
ServiceIdentityNotMatch_Throw_MessageSecurityException test fails CoreCLR ToF

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#585]
Running Test: IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException
  Assert.True:Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.NotSupportedException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.NotSupportedException' was thrown.
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.Throws[T](Action action) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException() in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\IdentityTests.cs:line 56
     at EntryPointMain.b__14() in e:\ProjectK\src\QA\ToF\PK\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests\Security.TransportSecurity.Tests.main.cs:line 33
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by iamjasonp** [comment]
Closed via #599
