### ISSUE TITLE
Https_ClientCredentialTypeTests.NtlmAuthentication_RoundTrips_Echo test fails in Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#606]
I believe the failure indicates System.Security.Principal.Windows is being used, but there is no Linux implementation for it.  See issue #604 to resolve that part of this.

Https_ClientCredentialTypeTests.NtlmAuthentication_RoundTrips_Echo [FAIL]
      Test Case: NtlmAuthentication FAILED with the following errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
      'BasicHttpBinding with NTLM authentication'
      Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processthreads-l1-1-0.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
         at Interop.mincore.GetCurrentThread()
         at Interop.mincore.OpenThreadToken(TokenAccessLevels desiredAccess, WinSecurityContext openAs, SafeAccessTokenHandle& tokenHandle)
         at System.Security.Principal.WindowsIdentity.GetCurrentToken(TokenAccessLevels desiredAccess, Boolean threadOnly, Boolean& isImpersonating, Int32& hr)
         at System.Security.Principal.WindowsIdentity.GetCurrentInternal(TokenAccessLevels desiredAccess, Boolean threadOnly)
         at System.ServiceModel.Security.SecurityUtils.NetworkCredentialHelper.GetCurrentUserIdAsString(NetworkCredential credential)
         at System.ServiceModel.Security.SecurityUtils.AppendWindowsAuthenticationInfo(String inputString, NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel)
         at System.ServiceModel.Channels.HttpChannelFactory`1.AppendWindowsAuthenticationInfo(String inputString, NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel)
         at System.ServiceModel.Channels.HttpChannelFactory`1.GetConnectionGroupName(NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel, SecurityTokenContainer clientCertificateToken)
         at System.ServiceModel.Channels.HttpChannelFactory`1.GetHttpClient(EndpointAddress to, NetworkCredential credential, TokenImpersonationLevel impersonationLevel, AuthenticationLevel authenticationLevel, SecurityTokenContainer clientCertificateToken)
         at System.ServiceModel.Channels.HttpChannelFactory`1.<GetHttpClientAsync>d__45.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.<GetHttpClientAsync>d__25.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.ServiceModel.Channels.HttpsChannelFactory`1.HttpsClientRequestChannel.<GetHttpClientAsync>d__14.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__34.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__33.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.Runtime.TaskHelpers.WaitForCompletion[TResult](Task`1 task)
         at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
         at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
         at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
         at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
         at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
         at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
         at generatedProxy_2.Echo(String )
         at ScenarioTestHelpers.RunBasicEchoTest(Binding binding, String address, String variation, StringBuilder errorBuilder, Action`1 factorySettings)

**Comment by roncain** [comment]
Should be fixed by #604

**Comment by iamjasonp** [comment]
Fixed - disabled by #627
