### ISSUE TITLE
ExpectedExceptionTests.NotExistentHost_Throws_EndpointNotFoundException fails in Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#621]
ExpectedExceptionTests.NotExistentHost_Throws_EndpointNotFoundException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ServiceModel.EndpointNotFoundException)
      Actual:   typeof(System.ServiceModel.CommunicationException): An error occurred while sending the request.
      Stack Trace:
            at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)
            at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__34.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__33.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Runtime.TaskHelpers.WaitForCompletion[TResult](Task`1 task)
            at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
            at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
            at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
            at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
            at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
            at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
            at generatedProxy_1.Echo(String )
            at ExpectedExceptionTests.<>c__DisplayClass0_0.<NotExistentHost_Throws_EndpointNotFoundException>b__0()

**Comment by iamjasonp** [comment]
IIRC, this test has always been really flaky; I haven't figured out why sometimes we get an EndpointNotFoundException and sometimes we get a CommunicationException

**Comment by roncain** [comment]
I realize this is a dupe of #419 and am closing it.
