### ISSUE TITLE
Create a scenario test for channel extensibility model

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#623]
The goal is to verify if channel extensibility model works. Example scenario is Custom Message Interceptor(https://msdn.microsoft.com/library/ms751495(v=vs.100).aspx)

The code coverage shows that we don't cover various LayeredChannel. This test should cover those.

**Comment by zhenlan** [comment]
@khdang can you work on this?

**Comment by khdang** [comment]
I give it a first try and there is this error:

```
System.PlatformNotSupportedException : Operation is not supported on this platform.
        Stack Trace:
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs(233,0): at System.ServiceModel.ChannelFactory.InitializeEndpoint(String configurationName, EndpointAddress address)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs(449,0): at System.ServiceModel.ChannelFactory`1..ctor(String endpointConfigurationName, EndpointAddress remoteAddress)
           e:\Open\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs(430,0): at System.ServiceModel.ChannelFactory`1..ctor(String endpointConfigurationName)
           e:\Open\wcf\src\System.Private.ServiceModel\tests\Scenarios\Binding\Custom\CustomBindingTests.cs(80,0): at CustomBindingTests.CustomBinding_Message_Interceptor()
```
I'm looking to understand this.

**Comment by khdang** [comment]
I've created another issue to track the second part of this issue, adding coverage for LayerChannel, which is not covered by MessageInterceptor scenario yet. I'm closing this issue.
