### ISSUE TITLE
ServiceKnownTypeTests.ServiceKnownType_DataContract_AttrOnMethod_Test Fails in Net Native

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#628]
This test fails in Net Native. The cause is that the reducer does not check whether an operation contract method is marked with ServiceKnownTypeAttribute.

**Comment by roncain** [comment]
Incidentally, failure looks like this:
  Running Test: ServiceKnownTypeTests.ServiceKnownType_DataContract_AttrOnMethod_Test
  Caught Unexpected exception:System.ServiceModel.CommunicationException: net_http_client_execution_error ---> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.Runtime.Serialization.InvalidDataContractException: SerializationCodeIsMissingForType, Widget0
     at System.Runtime.Serialization.DataContract.GetDataContractFromGeneratedAssembly(Type type, $DataContract dataContract) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContract.cs:line 99
     at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, Type type) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContract.cs:line 702
     at System.Runtime.Serialization.DataContract.GetDataContract(Type type, $SerializationMode mode) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContract.cs:line 126
     at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType($XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 217
     at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize($XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 136
     at Type25.WriteArrayOfanyTypeToXml($XmlWriterDelegator A_0, Object A_1, $XmlObjectSerializerWriteContext A_2, $CollectionDataContract A_3)
     at System.Runtime.Serialization.XmlFormatCollectionWriterDelegate.InvokeOpenStaticThunk($XmlWriterDelegator xmlWriter, Object obj, $XmlObjectSerializerWriteContext context, $CollectionDataContract dataContract)
     at System.Runtime.Serialization.CollectionDataContract.WriteXmlValue($XmlWriterDelegator xmlWriter, Object obj, $XmlObjectSerializerWriteContext context) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\CollectionDataContract.cs:line 1413
     at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType($DataContract dataContract, $XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs:line 153
     at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent($XmlWriterDelegator writer, Object graph, $DataContractResolver dataContractResolver) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs:line 337
     at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject($XmlWriterDelegator writer, Object graph, $DataContractResolver dataContractResolver) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs:line 230
     at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions($XmlWriterDelegator writer, Object graph, $DataContractResolver dataContractResolver) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs:line 70
     at System.Runtime.Serialization.XmlObjectSerializer.WriteObject($XmlDictionaryWriter writer, Object graph) in E:\ProjectK\src\ndp\fxcore\Open\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs:line 56
     at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameterPart($XmlDictionaryWriter writer, $PartInfo part, Object graph) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\DataContractSerializerOperationFormatter.cs:line 234
     at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameter($XmlDictionaryWriter writer, $PartInfo part, Object graph) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\DataContractSerializerOperationFormatter.cs:line 227
     at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameters($XmlDictionaryWriter writer, $PartInfo[] parts, Object[] parameters) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\DataContractSerializerOperationFormatter.cs:line 212
     at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeBody($XmlDictionaryWriter writer, $MessageVersion version, String action, $MessageDescription messageDescription, Object returnValue, Object[] parameters, Boolean isRequest) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\DataContractSerializerOperationFormatter.cs:line 201
     at System.ServiceModel.Dispatcher.OperationFormatter.SerializeBodyContents($XmlDictionaryWriter writer, $MessageVersion version, Object[] parameters, Object returnValue, Boolean isRequest) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\OperationFormatter.cs:line 349
     at System.ServiceModel.Dispatcher.OperationFormatter.OperationFormatterMessage.OperationFormatterBodyWriter.OnWriteBodyContents($XmlDictionaryWriter writer) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\OperationFormatter.cs:line 720
     at System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents($XmlDictionaryWriter writer) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Message.cs:line 1052
     at System.ServiceModel.Channels.Message.WriteMessage($XmlDictionaryWriter writer) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\Message.cs:line 621
     at System.ServiceModel.Channels.BufferedMessageWriter.WriteMessage($Message message, $BufferManager bufferManager, Int32 initialOffset, Int32 maxSizeQuota) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\BufferedMessageWriter.cs:line 50
     at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessageAsync($Message message, Int32 maxMessageSize, $BufferManager bufferManager, Int32 messageOffset) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TextMessageEncoder.cs:line 496
     at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessage($Message message, Int32 maxMessageSize, $BufferManager bufferManager, Int32 messageOffset) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TextMessageEncoder.cs:line 463
     at System.ServiceModel.Channels.BufferedMessageContent.CreateContentReadStreamAsync() in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageContent.cs:line 218
     at System.Net.Http.HttpContent.ReadAsStreamAsync() in E:\ProjectK\src\ndp\fxcore\Open\src\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 288

**Comment by shmao** [comment]
The fix has been checked-in to Net Native. The CS # is 1562667.
