### ISSUE TITLE
WebSockets RequestReply tests fail when Bridge is on other machine

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#677]
These tests failed when Bridge is running on another machine:
    WebSocketTests.WebSocket_Https_RequestReply_BinaryBuffered
    WebSocketTests.WebSocket_Https_RequestReply_TextBuffered_KeepAlive
    WebSocketTests.WebSocket_Http_RequestReply_TextBuffered
    WebSocketTests.WebSocket_Http_RequestReply_BinaryBuffered_KeepAlive

This was observed in GitHub as well as ToF tests for both CoreCLR and NET Native.  It was done by starting the Bridge on a separate machine (StartBridge /allowRemote), and setting the ENV var BridgeHost to be the name of that machine when running the test on another machine.

The Assert should also be improved to understand what it *did* find, rather than what it failed to find.
  --------------------------------
  Running Test: WebSocketTests.WebSocket_Https_RequestReply_BinaryBuffered
  Assert.True:RemoteEndpointMessageProperty did not contain the address of this machine. Expected to find: 172.30.169.220
  Xunit.AssertTestException: Assert.True: RemoteEndpointMessageProperty did not contain the address of this machine. Expected to find: 172.30.169.220
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.True(Boolean condition, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at WebSocketTests.WebSocket_Https_RequestReply_BinaryBuffered($BindingElement[] CS$0$0000) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Extensibility\WebSockets\WebSocketTests.cs:line 665
     at EntryPointMain.b__3() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Extensibility\WebSockets\Extensibility.WebSockets.Tests.main.cs:line 16
     at System.Func$1.InvokeOpenStaticThunk()
     at Windows.System.Threading.TimerElapsedHandler.Invoke($ThreadPoolTimer timer)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by roncain** [comment]
This is a test bug.  Many of the WebSockets tests are written to verify the RemoteEndpointMessageProperty contains an address of the server, which works only when the remote endpoint is on the server.  Cross-machine, the RemoteEndpointMessageProperty refers to the client address.

**Comment by roncain** [comment]
@StephenBonikowsky -- how would you like to handle this?  I see 2 issues: (1) the WCF service itself is doing verification.  It should just capture data in the log and let the test (the client) do the verification.  We're trying to keep all verification code in the xunit tests and make the services just capture data.  The 2nd issue is that the WSRequestReplyService is checking the RemoteEndpointMessageProperty against all the addresses where it (i.e. the Bridge) is running and emits that failure message if it can't find a match.  But it cannot match when the remote endpoint is on a different machine.
