### ISSUE TITLE
Latest RC2 builds fail a few scenarios due to a dependency on missing System.IO, Version=4.1.0.0

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#711]
Here is a typical error we get:
~~~
System.IO.FileLoadException: Could not load file or assembly 'System.IO, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exce
ption from HRESULT: 0x80131040)
File name: 'System.IO, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.ServiceModel.Description.ServiceReflector.ValidateParameterMetadata(MethodInfo methodInfo)
   at System.ServiceModel.Description.TypeLoader.CreateOperationDescriptions(ContractDescription contractDescription, ContractReflectionInfo reflectionInfo, Type contractToGetMethodsFrom, ContractDescription declaringContract, MessageDirection direction)
   at System.ServiceModel.Description.TypeLoader.CreateContractDescription(ServiceContractAttribute contractAttr, Type contractType, Type serviceType, ContractReflectionInfo& reflectionInfo, Object serviceImplementation)
   at System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation)
   at System.ServiceModel.ChannelFactory`1.CreateDescription()
   at System.ServiceModel.ChannelFactory.InitializeEndpoint(Binding binding, EndpointAddress address)
   at System.ServiceModel.ChannelFactory`1..ctor(Binding binding, EndpointAddress remoteAddress)
   at SharedPoolsOfWCFObjects.TestHelpers.CreateChannelFactory[C](EndpointAddress a, Binding b) in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\TestHelpers.cs:line 214
   at SharedPoolsOfWCFObjects.CommonTest`2.CreateChannelFactory() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\Tests\CommonTest.cs:line 57
   at SharedPoolsOfWCFObjects.CreateAndCloseFactoryAndChannelFullCycleTest`3.<>c.<CreateFactoriesAndChannelsUseAllOnceCloseAll>b__2_1() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\SharedPoolsOfWCFObjects.cs:line 40
   at SharedPoolsOfWCFObjects.FactoryAndPoolOfItsObjects`2..ctor(Func`1 createFactoryInstance, Action`1 destroyFactoryInstance, Int32 maxPooledObjects, Func`2 createObject, Action`1 destroyObject) in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObject
s\PoolOfThings.cs:line 311
   at SharedPoolsOfWCFObjects.CreateAndCloseFactoryAndChannelFullCycleTest`3.<>c.<CreateFactoriesAndChannelsUseAllOnceCloseAll>b__2_0() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\SharedPoolsOfWCFObjects.cs:line 38
   at SharedPoolsOfWCFObjects.PoolOfThings`1.GetPooledInstance(Int32 i) in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\PoolOfThings.cs:line 113
   at SharedPoolsOfWCFObjects.PoolOfThings`1.AllPooledInstancesCollection.<GetEnumerator>d__2.MoveNext() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\PoolOfThings.cs:line 91
   at SharedPoolsOfWCFObjects.CreateAndCloseFactoryAndChannelFullCycleTest`3.CreateFactoriesAndChannelsUseAllOnceCloseAll() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\SharedPoolsOfWCFObjects.cs:line 50
   at SharedPoolsOfWCFObjects.Program.Run10KPerfTests[ChannelType,TestTemplate,TestParams]() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\Program.cs:line 675
   at SharedPoolsOfWCFObjects.Program.<>c__DisplayClass13_0.<RunFirstNIterations>b__0() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\Program.cs:line 446
   at SharedPoolsOfWCFObjects.Program.<>c__DisplayClass15_0.<<RunFirstNIterationsAsyncImpl>b__0>d.MoveNext() in C:\WCFClientStressTests\Core\src\SharedPoolsOfWCFObjects\Program.cs:line 480
~~~

The error shows up regardless of the project.json trying to point out to System.IO from the same build or relying on the dependency graph to get the relevant assembly automatically.

**Comment by zhenlan** [comment]
@mconnew while you are working on #706, do you have any idea about this one?

**Comment by mconnew** [comment]
I expect this to be fixed now.

**Comment by KKhurin** [comment]
as we hoped this went away with the latest build
