### ISSUE TITLE
Streaming on NetTcp does not work

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#713]

**Comment by zhenlan** [comment]
This is unexpected. @KKhurin can you please share a repo and more details of the failure?

**Comment by KKhurin** [comment]
Here is the relevant part of call stack:
~~~
System.PlatformNotSupportedException: StreamedFramingRequestChannel not yet implemented
   at System.ServiceModel.Channels.ConnectionOrientedTransportChannelFactory`1.OnCreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.ServiceChannelFactory.ServiceChannelFactoryOverRequest.CreateInnerChannelBinder(EndpointAddress to, Uri via)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateServiceChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
~~~
