### ISSUE TITLE
Many tests fail on Linux attempting to load winhttp.dll

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#716]
Running OuterLoop tests on Linux see many tests fail with this stack trace.  Possibly due to new changes to build for each OSGroup.  Needs investigation.   

```
 CustomBindingTests.DefaultSettings_Https_Text_Echo_RoundTrips_String [FAIL]
Test case FAILED with errors : warning : Unexpected exception was caught while doing the basic echo test for variation... [/home/roncain/git/wcf/src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.Tests.csproj]
        'Client:: CustomBinding/DefaultValues
        Server:: CustomBinding/DefaultValues'
        Exception: System.DllNotFoundException: Unable to load DLL 'winhttp.dll': The specified module could not be found.
         (Exception from HRESULT: 0x8007007E)
           at Interop.WinHttp.WinHttpOpen(IntPtr userAgent, UInt32 accessType, String proxyName, String proxyBypass, Int32 flags)
           at System.Net.Http.WinHttpHandler.EnsureSessionHandleExists(WinHttpRequestState state)
           at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
```

**Comment by roncain** [comment]
This issue no longer repros.  Likely fixed by fixes to .builds and .csproj files to account for OSGroup, etc.
