### ISSUE TITLE
.Net native: ExpectedExceptionTests.DuplexCallback_Throws_FaultException_DirectThrow failed

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#769]
Running Test: ExpectedExceptionTests.DuplexCallback_Throws_FaultException_DirectThrow
  Assert.True:Expected 'System.ServiceModel.FaultException`1[FaultDetail]' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.ServiceModel.FaultException`1[FaultDetail]' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.Throws(Action action, Object[] CS$0$0000) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at ExpectedExceptionTests.DuplexCallback_Throws_FaultException_DirectThrow(DuplexTaskReturnServiceCallback callbackService) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 372
     at EntryPointMain.b__9() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ExpectedExceptions\Client.ExpectedExceptions.Tests.main.cs:line 22
     at System.Func$1.InvokeOpenStaticThunk()
     at System.ServiceModel.Dispatcher.MessageRpcProcessor.Invoke($MessageRpc rpc)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by hongdai** [comment]
Note that running test with only one worker failed as well.

**Comment by hongdai** [comment]
This is caused by a Missing metadata exception:
 'System.ServiceModel.Dispatcher.FaultFormatter.OperationFault<>' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859

The fix is to add the OperationFault to s.p.sm rd.xml explicitly so that toolchain knows we need it.

After add the OperationFault into the s.p.sm rd.xml, we hit a toolchain issue that tracked by bug 189994: Reflection blocking applying to namespaces in unblocked assemblies.

**Comment by roncain** [comment]
This is a significant regression for [FaultContract] scenarios and can break existing UWP WCF apps.  We should work to ensure this is fixed asap.

**Comment by StephenBonikowsky** [comment]
I also have ExpectedExceptionTests.DuplexCallback_Throws_FaultException_ReturnsFaultedTask failing for apparently the same reason, same call stack.

Adding an Active Issue for both of these tests on NET Native only, when this Issue gets fixed the ActiveIssue needs to be removed.

**Comment by hongdai** [comment]
This bug is pushed back on us. There are 3 options to solve this problem:
1) make FaultFormatter a public type.
2) Remove __BlockReflection attribute on our assembly level and use the rd.xml file to limit reflection.
3) Change our product code to NOT to reflect on type OperationFault.

We need to discuss the options.
