### ISSUE TITLE
Https BasicAuthentication tests fail when Bridge is allowed to auto-start

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#788]
These 2 tests fail when run in ToF on CoreCLR *without* first starting the Bridge, relying on the new auto-start feature of the Bridge.
  Failed tests:
    Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo
    Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException

These tests succeed if the Bridge is started manually first.  When the Bridge is not started manually, it now self-starts for each test .csproj.  The fact the test fail in this mode suggests either a timing issue or that some other tests that run before these configures the Bridge in some way that is critical to these tests.

Stack trace looks like this:
```
Running Test: Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo
  Assert.True:Test Case: BasicAuthentication FAILED with the following errors: Basic echo test.
  Test variation:...
  BasicAuthentication_RoundTrips_Echo
  Using address: 'https://localhost:44285/BridgeAppDomain0/https-basic'
  Unexpected exception was caught: System.ServiceModel.CommunicationException: An error occurred while receiving the HTTP response to https://localhost:44285/BridgeAppDomain0/https-basic. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
```

```
 --------------------------------
  Running Test: Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException
  Assert.True:Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.ServiceModel.Security.MessageSecurityException' to be thrown, however 'System.ServiceModel.CommunicationException' was thrown.
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.Throws[T](Action action) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException() in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\ClientCredentialTypeTests.cs:line 68
     at EntryPointMain.b__1() in e:\ProjectK\src\QA\ToF\PK\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests\Security.TransportSecurity.Tests.main.cs:line 14
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------
  
```

**Comment by zhenlan** [comment]
This is caused by infrastructure issue. If we see this from lab runs, we will disable these tests for now. For the long term, we will find a better solution for the infrastructure.
