### ISSUE TITLE
WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed fails in ToF (CoreCLR)

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#805]
Running Test: WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed
  Assert.True:Expected channel to be in state Faulted but was in state Opened
  Xunit.AssertTestException: Assert.True: Expected channel to be in state Faulted but was in state Opened
     at Xunit.Assert.HandleFail(String assertionName, String message) in n:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.True(Boolean condition, String message) in n:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed() in n:\dd\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Extensibility\WebSockets\WebSocketTests.cs:line 132
     at EntryPointMain.b__0() in n:\dd\ProjectK\src\QA\ToF\PK\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Extensibility\WebSockets\Extensibility.WebSockets.Tests\Extensibility.WebSockets.Tests.main.cs:line 13
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in n:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by iamjasonp** [comment]
I'm trying to figure out why this is happening: 

```
error : The contract 'System.Runtime.Serialization.Primitives' version '4.1.1.0' cannot be resolved. The version specified is not available, but others are: 
error : Version: '4.0.0.0' 
error : Version: '4.1.0.0' 
error : Version: '4.0.10.0' 
```

**Comment by roncain** [comment]
We had to update the targets files in TFS used by our ToF wrapper projects to use the newer serialization versions for CLRTestContractReference. I don't know why WebSockets would fail when the others do not, as it doesn't include any other CLRTestContractReference entries.  This is a ToF-only change, because ToF does not use package versions.  OSS was resolved by changing project.jsons.

**Comment by iamjasonp** [comment]
Great. I'm seeing build failures because of this; investigating.

**Comment by iamjasonp** [comment]
It turns out that S.R.Serialization.Primitives 4.1.1.0 doesn't exist in stable form yet, only 4.1.0.0. I switched these over in the build for TFS, verified the build works. 

```
  --------------------------------
  Running Test: WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed
  ---- Test PASSED ---------------
  ```

**Comment by roncain** [comment]
This is exactly the opposite of what we were experiencing before the TFS checkin -- where all the WcfOpen ToF tests failed due to having the older serialization dependencies, If we back-out the TFS checkin, either one of 2 things will be true (1) all WcfOpen ToF tests will fail to build again, or (2) we have changes in serialization versions that contradict what was true a few days ago.  I recommend we wait for a clean TFS build and verify pass/fail of the WcfOpen ToF tests both with and without the proposed changes to revert the dependencies.

**Comment by iamjasonp** [comment]
This doesn't seem to be failing for me anymore... I'm cleaning out my machine now to retest, and shall see if it fails to repro again. If so, will close.

**Comment by iamjasonp** [comment]
Test passes on latest sync, CoreCLR ToF running OSS tests. Closing.
