### ISSUE TITLE
PlatformNotSupportedException: Windows Stream Security is not supported

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#832]
|Failing Test Cases |
|--------------------------|
|**Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString**|
|**Tcp_ClientCredentialTypeTests.SameBinding_SecurityModeTransport_EchoString**|

**Comment by StephenBonikowsky** [comment]
Call Stack

  Running Test: Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString
  Caught Unexpected exception:System.PlatformNotSupportedException: Windows Stream Security is not supported
     at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream, OutWrapper`1 remoteSecurity)
     at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.d__14.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.ConnectionUpgradeHelper.d__3.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.d__10.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.ConnectionPoolHelper.d__15.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.d__12.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.CommunicationObject.d__71.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.ServiceChannel.d__149.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.CommunicationObject.d__71.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.CommunicationObject.d__70.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
     at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
     at generatedProxy_2.Echo(String )
     at Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\ClientCredentialTypeTests.cs:line 35
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in e:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 174
     at CoreFXTestLibrary.Internal.Runner.RunTest(TestInfo t) in e:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------

**Comment by StephenBonikowsky** [comment]
Closing Issues #810 and #812

**Comment by zhenlan** [comment]
These tests failed because windows auth is not supported in UWP due to lack of NegotiateStream (which is default code path for nettcp binding).

**Comment by zhenlan** [comment]
This is a dup of #1235. Closing this out. @StephenBonikowsky please let me know if you want to keep this opened.
