### ISSUE TITLE
PlatformNotSupportedException: SslStreamSecurityUpgradeInitiator.InInitiateUpgradeAsync

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#833]
|Failing Test Cases |
|--------------------------|
|**Tcp_ClientCredentialTypeTests.SameBinding_SecurityModeTransport_ClientCredentialTypeCertificate_EchoString**|
|**Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_With_ServerAltName_EchoString**|
|**IdentityTests.VerifyServiceIdentityMatchDnsEndpointIdentity**|
|**IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException**|
|**ExpectedExceptionTests.TCP_ServiceCertExpired_Throw_MessageSecurityException**|
|**ExpectedExceptionTests.TCP_ServiceCertRevoked_Throw_MessageSecurityException**|

**Comment by StephenBonikowsky** [comment]
Stack Trace

  Running Test: IdentityTests.VerifyServiceIdentityMatchDnsEndpointIdentity
  Caught Unexpected exception:System.PlatformNotSupportedException: SslStreamSecurityUpgradeInitiator.InInitiateUpgradeAsync
     at System.ServiceModel.Channels.SslStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream, OutWrapper`1 remoteSecurityWrapper)
     at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.d__14.MoveNext()

.....

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
     at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
     at generatedProxy_2.Echo(String )
     at IdentityTests.VerifyServiceIdentityMatchDnsEndpointIdentity() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\IdentityTests.cs:line 28
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in e:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 174
     at CoreFXTestLibrary.Internal.Runner.RunTest(TestInfo t) in e:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------

**Comment by StephenBonikowsky** [comment]
Closing Issues #813 and #815 and #816 and #525

**Comment by StephenBonikowsky** [comment]
The fix for this issue will also resolve the following two test cases...

- Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString
- Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString

The original issue for these two tests is #834
