### ISSUE TITLE
System.NotSupportedException: The value 'Certificate' is not supported in this context for the binding security property 'Transport.ClientCredentialType'

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#834]
|Failing Test Cases |
|--------------------------|
|**Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString**|
|**Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString**|

**Comment by StephenBonikowsky** [comment]
Stack Trace

  Running Test: Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString
  Caught Unexpected exception:System.NotSupportedException: The value 'Certificate' is not supported in this context for the binding security property 'Transport.ClientCredentialType'.
     at System.ServiceModel.NetTcpBinding.CheckSettings()
     at System.ServiceModel.NetTcpBinding.CreateBindingElements()
     at System.ServiceModel.Channels.Binding.EnsureInvariants(String contractName)
     at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory(ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose)
     at System.ServiceModel.ChannelFactory.OnOpening()
     at System.ServiceModel.Channels.CommunicationObject.d__71.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.Channels.CommunicationObject.d__70.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.ServiceModel.ChannelFactory.EnsureOpened()
     at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
     at Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString() in c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\ClientCredentialTypeTests.cs:line 228
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in e:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 174
     at CoreFXTestLibrary.Internal.Runner.RunTest(TestInfo t) in e:\dd\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------

**Comment by StephenBonikowsky** [comment]
Closing Issues #522 and #523

**Comment by zhenlan** [comment]
The fix of #833 will fix this as well.

@StephenBonikowsky to update activeissue of 834 to 833.

**Comment by StephenBonikowsky** [comment]
Have updated #833 to include these two test cases.
Will then close this Issue as part of a PR to update the ActiveIssue on the test cases.
