### ISSUE TITLE
Failure to load System.Security.Principal.Windows on Linux in scenario tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#904]
When running OuterLoops on Linux, I get this exception in 2 tests:
```
     Https_ClientCredentialTypeTests.WindowsAuthentication_RoundTrips_Echo [FAIL]
        Test Case: WindowsAuthentication FAILED with the following errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
        'BasicHttpBinding with Windows authentication'
        Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
        
        File name: 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
           at System.ServiceModel.Security.SecurityUtils.NetworkCredentialHelper.GetCurrentUserIdAsString(NetworkCredential credential)
           at System.ServiceModel.Security.SecurityUtils.AppendWindowsAuthenticationInfo(String inputString, NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel)
           at System.ServiceModel.Channels.HttpChannelFactory`1.AppendWindowsAuthenticationInfo(String inputString, NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel)
           at System.ServiceModel.Channels.HttpChannelFactory`1.GetConnectionGroupName(NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel, SecurityTokenContainer clientCertificateToken)
           at System.ServiceModel.Channels.HttpChannelFactory`1.GetHttpClient(EndpointAddress to, NetworkCredential credential, TokenImpersonationLevel impersonationLevel, AuthenticationLevel authenticationLevel, SecurityTokenContainer clientCertificateToken)
           at System.ServiceModel.Channels.HttpChannelFactory`1.<GetHttpClientAsync>d__42.MoveNext()
```

**Comment by iamjasonp** [comment]
Currently waiting on the Linux build to be fixed (#925)

**Comment by iamjasonp** [comment]
This is next up to investigate for me. This should have been fixed but I need to reverify this.

**Comment by iamjasonp** [comment]
Verified - We get the following

```
   Https_ClientCredentialTypeTests.WindowsAuthentication_RoundTrips_Echo [FAIL]
      Test Case: WindowsAuthentication FAILED with the following errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
      'BasicHttpBinding with Windows authentication'
      Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
         at System.Security.Principal.WindowsIdentity.GetCurrent()
         at System.ServiceModel.Security.SecurityUtils.NetworkCredentialHelper.GetCurrentUserIdAsString(NetworkCredential credential)
         at System.ServiceModel.Security.SecurityUtils.AppendWindowsAuthenticationInfo(String inputString, NetworkCredential credential, AuthenticationLevel authenticationLevel, TokenImpersonationLevel impersonationLevel)
```

Which is expected on this platform.
