### ISSUE TITLE
BasicHttp_Echo_Streamed_Async_Delayed_Throws_TimeoutException test fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#939]
The newly added functional test #936 to verify the fix for #931 has turned up another issue.
In CoreCLR, a TimeoutException is thrown, but in NET Native, a TaskCancelledException is thrown.

We need to determine which is correct and then fix the one that is not.

```
  --------------------------------
  Running Test: ServiceContractTests.BasicHttp_Echo_Streamed_Async_Delayed_Throws_TimeoutException
  Assert.True:Expected 'System.TimeoutException' to be thrown, however 'System.Threading.Tasks.TaskCanceledException' was thrown.
  Xunit.AssertTestException: Assert.True: Expected 'System.TimeoutException' to be thrown, however 'System.Threading.Tasks.TaskCanceledException' was thrown.
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
     at Xunit.Assert.Throws(Action action, Object[] CS$0$0000) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
     at ServiceContractTests.BasicHttp_Echo_Streamed_Async_Delayed_Throws_TimeoutException($ICommunicationObject[] CS$0$0000) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Contract\Service\ServiceContractTests.cs:line 273
     at EntryPointMain.b__7() in e:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Contract\Service\Contract.Service.Tests.main.cs:line 20
     at System.Func$1.InvokeOpenStaticThunk()
     at System.AsyncCallback.Invoke(IAsyncResult ar)
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------
```

**Comment by roncain** [comment]
@mconnew -- do you have some insight into the CoreCLR/NET Native differences under the hood that would account for this difference?  The functional test effectively forces a timeout to happen during the send portion and expects a TimeoutException to be thrown.

**Comment by roncain** [comment]
Update: here is more detailed stack information in NET Native:
```
  System.Threading.Tasks.TaskCanceledException: TaskCanceledException_ctor_DefaultMessage
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task, ExceptionDispatchInfo oceEdi) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 174
     at System.ServiceModel.Channels.RequestChannel.EndRequest(IAsyncResult result) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\RequestChannel.cs:line 237
     at System.ServiceModel.Dispatcher.RequestChannelBinder.EndRequest(IAsyncResult result) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\RequestChannelBinder.cs:line 95
     at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.FinishSend(IAsyncResult result, Boolean completedSynchronously) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1862
     at System.Runtime.AsyncResult.End(IAsyncResult result, __Canon asyncResult) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\Internals\System\Runtime\AsyncResult.cs:line 376
     at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End($SendAsyncResult result) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 1898
     at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs:line 806
     at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.b__0(IAsyncResult asyncResult) in E:\ProjectK\src\ndp\fxcore\WcfOpen\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs:line 179
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task, ExceptionDispatchInfo oceEdi) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182
     at System.Runtime.CompilerServices.ConfiguredTaskAwaitable$1.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 482
     at ServiceContractTests.BasicHttp_Echo_Streamed_Async_Delayed_Throws_TimeoutException($TaskAwaiter$1<$Stream> CS$0$0000) in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Contract\Service\ServiceContractTests.cs:line 279
```

**Comment by mconnew** [comment]
We aren't catching a TaskCanceledException somewhere and converting it to a TimeoutException. The TimeoutException is the correct one. The difficulty with this one is it looks like the exception isn't being thrown at it's source, instead a Task is being converted to Apm semantics and that's where we're throwing it. I should be able to work out from the code how this is happening on Monday.

**Comment by roncain** [comment]
Root cause was due to the test itself which fault-injected an abort then a timeout.  Reversing that to allow the timeout to happen first did, indeed allow the CT to be cancelled properly and allowed the TimeoutException to be thrown. And it still exercised the previously fixed null reference exception in this failure path.
