### ISSUE TITLE
The NegotiateStream_Tcp_AmbientCredentials test fails in Windows (CoreCLR and UWP)

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#948]
This test failed in both a ToF run (N-from-K) as well as a Helix run.  It is hard to know the failure reason, because it is the Assert.True(success) in the finally block that fires.  Recommend the test explicitly catch and report an exception rather than Boolean so that it is clear where and why the 'success = true' statement is bypassed. The test is disabled in Linux-only for other reasons.
```
Running Test: NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_AmbientCredentials
Assert.True:Credentials passed:
  NegotiateTestRealm : 'DOMAIN.CONTOSO.COM'
  NegotiateTestDomain : 'DOMAIN'
  NegotiateTestUserName : 'testuser'
  NegotiateTestPassword : 'hunter2'
  NegotiateTestSpn : 'testhost.domain.contoso.com'
  NegotiateTestUpn : 'testuser@DOMAIN.CONTOSO.COM'

Xunit.AssertTestException: Assert.True: Credentials passed:
  NegotiateTestRealm : 'DOMAIN.CONTOSO.COM'
  NegotiateTestDomain : 'DOMAIN'
  NegotiateTestUserName : 'testuser'
  NegotiateTestPassword : 'hunter2'
  NegotiateTestSpn : 'testhost.domain.contoso.com'
  NegotiateTestUpn : 'testuser@DOMAIN.CONTOSO.COM'

   at Xunit.Assert.HandleFail(String assertionName, String message) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
   at Xunit.Assert.True(Boolean condition, String message) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
   at NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_AmbientCredentials$fin$0() in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Negotiate\NegotiateStream_Tcp_Tests.cs:line 92
   at EntryPointMain.<>c.
b__0_19() in E:\ProjectK\src\QA\ToF\PN\amd64\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 32
   at Windows.Foundation.AsyncOperationProgressHandler$2.Invoke($IAsyncOperationWithProgress$2 asyncInfo, UInt32 progressInfo)
   at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
---- Test FAILED ---------------
```

**Comment by iamjasonp** [comment]
I'll take a further look. I suspect the Helix test machine isn't domain joined and thus doesn't present an "ambient" credential.

**Comment by roncain** [comment]
The same is probably true for the ToF machines where it also fails.  But I can't explain why the Http version of this test failed in Helix (#949) but not in ToF.

**Comment by iamjasonp** [comment]
Verified manually - NegotiateStream_Tcp_AmbientCredentials passes on CoreCLR, but does not on UWP. On UWP, we are blocked as NegotiateStream is not supported on UWP. See #1235
